In [5]:
import kagglehub
import pandas as pd
import numpy as np

LTV model:
The LTV model is predictive. To evaluate whether a new feature impacts LTV, we need causal methods like A/B testing or uplift modeling.

In [ ]:

# Download latest version
path = kagglehub.dataset_download("yasserh/instacart-online-grocery-basket-analysis-dataset")

print("Path to dataset files:", path)

In [9]:
from pathlib import Path

folder_path = Path(path)
for file_path in folder_path.glob("*.csv"): # Use .glob("*.extension")
    if file_path.is_file(): # Ensure it's a file, not a directory
        content = file_path.read_text(encoding='utf-8')
        # Process the content here
        print(f"Content of {file_path.name}: {content[:50]}...")

Content of products.csv: product_id,product_name,aisle_id,department_id
1,C...
Content of orders.csv: order_id,user_id,eval_set,order_number,order_dow,o...
Content of order_products__train.csv: order_id,product_id,add_to_cart_order,reordered
1,...
Content of departments.csv: department_id,department
1,frozen
2,other
3,bakery...
Content of aisles.csv: aisle_id,aisle
1,prepared soups salads
2,specialty...
Content of order_products__prior.csv: order_id,product_id,add_to_cart_order,reordered
2,...

In [16]:
products = pd.read_csv('{}/{}'.format(path,'products.csv'))
orders = pd.read_csv('{}/{}'.format(path,'orders.csv'))
departments = pd.read_csv('{}/{}'.format(path,'departments.csv'))
aisles = pd.read_csv('{}/{}'.format(path,'aisles.csv'))
order_products_prior = pd.read_csv('{}/{}'.format(path,'order_products__prior.csv'))

In [17]:
products.head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

In [18]:
orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [20]:
departments.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [21]:
aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [22]:
order_products_prior.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

# Synthetic

In [23]:
import pandas as pd
import numpy as np

np.random.seed(42)

# -------------------------
# CONFIG
# -------------------------
n_users = 5000
max_days = 60

start_date = pd.Timestamp("2025-01-01")

platforms = ["ios", "android", "web"]
countries = ["US", "CA", "UK", "IN"]

data = []

# -------------------------
# GENERATE USERS
# -------------------------
for user_id in range(n_users):
    
    # user start offset
    start_offset = np.random.randint(0, 30)
    user_start = start_date + pd.Timedelta(days=int(start_offset))
    
    # user type (affects behavior)
    user_type = np.random.choice(
        ["low", "medium", "high"], 
        p=[0.6, 0.3, 0.1]
    )
    
    # base activity level
    if user_type == "low":
        base_sessions = np.random.uniform(0.2, 1)
        spend_prob = 0.02
    elif user_type == "medium":
        base_sessions = np.random.uniform(1, 3)
        spend_prob = 0.05
    else:
        base_sessions = np.random.uniform(3, 6)
        spend_prob = 0.1

    platform = np.random.choice(platforms)
    country = np.random.choice(countries)
    
    # simulate user lifetime
    lifetime = np.random.randint(5, max_days)
    
    for day in range(lifetime):
        
        date = user_start + pd.Timedelta(days=int(day))
        
        # sessions decay over time
        sessions = np.random.poisson(base_sessions * np.exp(-day / 30))
        
        if sessions == 0:
            continue
        
        # play time correlated with sessions
        play_time = sessions * np.random.uniform(5, 20)
        
        # creator interaction
        creator_id = np.random.randint(1, 1000)
        
        # spend (skewed, heavy-tail)
        spend = 0
        if np.random.rand() < spend_prob:
            spend = np.random.exponential(scale=5)
        
        data.append([
            user_id,
            date,
            sessions,
            play_time,
            spend,
            creator_id,
            platform,
            country
        ])

# -------------------------
# CREATE DATAFRAME
# -------------------------
df = pd.DataFrame(data, columns=[
    "user_id",
    "date",
    "sessions",
    "play_time",
    "spend",
    "creator_id",
    "platform",
    "country"
])

df = df.sort_values(["user_id", "date"])

print(df.head())
print("Rows:", len(df))
print("Users:", df["user_id"].nunique())

   user_id       date  sessions  play_time  spend  creator_id platform country
0        0 2025-01-07         1  11.888733    0.0         373      ios      US
1        0 2025-01-08         1  19.548648    0.0         492      ios      US
2        0 2025-01-10         3  16.037809    0.0         475      ios      US
3        0 2025-01-13         1  16.777639    0.0         563      ios      US
4        0 2025-01-14         3  35.272466    0.0         274      ios      US
Rows: 70558
Users: 4978

In [24]:
df

,user_id,date,sessions,play_time,spend,creator_id,platform,country
0,0,2025-01-07,1,11.888733,0.000000,373,ios,US
1,0,2025-01-08,1,19.548648,0.000000,492,ios,US
2,0,2025-01-10,3,16.037809,0.000000,475,ios,US
3,0,2025-01-13,1,16.777639,0.000000,563,ios,US
4,0,2025-01-14,3,35.272466,0.000000,274,ios,US
...,...,...,...,...,...,...,...,...
70553,4999,2025-01-26,3,32.599466,0.000000,688,web,IN
70554,4999,2025-01-27,2,16.721781,0.000000,450,web,IN
70555,4999,2025-01-28,2,18.727887,8.605824,83,web,IN
70556,4999,2025-01-29,2,18.667530,0.000000,767,web,IN
70557,4999,2025-01-30,3,57.009896,2.185158,560,web,IN

## Prompt 1: Build a model to predict 30-day LTV for users from their first 7 days of behavior

Using suggorate metrics to predict LTV - need assumptions
Obervation window:  Day 0-6 (features)
Prediction window : Day 7-29 (labels)
Train, test by cohort time

Features:
1. volume: total # of sessions, total play time, total spend
2. retention: active days within 7days, d1 retention, d7 retention
3. trend: last active day
4. marketplace: unique # of creators
5. platform and country

In [ ]:
with base as
(
    select
        user_id,
        date as event_date,
        sessions,
        play_time,
        spend,
        creator_id,
        platform,
        country,
        MIN(date) over(partition by user_id) as first_date
    from df_table
),
date_diff_t as (
    select
        *,
        DATEDIFF('day', first_date, event_date) as date_diff
    from base
)

select
    user_id,
    MAX(platform),
    MAX(country),
    MIN(first_date) as joining_date,
    COUNT(DISTINCT creator_id) as unique_creators,
    SUM(CASE WHEN date_diff BETWEEN 0 AND 6 THEN sessions ELSE 0 END) as total_session_7d,
    SUM(CASE WHEN date_diff BETWEEN 0 AND 6 THEN play_time ELSE 0 END) as total_playtime_7d,
    SUM(CASE WHEN date_diff BETWEEN 0 AND 6 THEN spend ELSE 0 END) as total_spend_7d,
    COUNT(DISTINCT CASE WHEN date_diff BETWEEN 0 AND 6 THEN event_date END) as active_days_7d,
    MAX(CASE WHEN date_diff = 1 THEN 1 ELSE 0 END) as d1_retention_flag,
    MAX(CASE WHEN date_diff = 6 THEN 1 ELSE 0 END) as d7_retention_flag,
    SUM(CASE WHEN date_diff BETWEEN 7 AND 29 THEN spend ELSE 0 END) AS ltv_30d
from date_diff_t
group by user_id, platform, country

In [57]:
processed_df = pd.read_csv("/Users/zhuangdiezhou/Documents/Documents - Zhuangdie Alan Zhou's MacBook Pro - 1/Hi_Sexy/Interview/Roblox/user_activity_processed_updated.csv")

In [58]:
processed_df.head()

,user_id,MAX(platform),MAX(country),joining_date,unique_creators,total_session_7d,total_playtime_7d,total_spend_7d,active_days_7d,d1_retention_flag,d7_retention_flag,ltv_30d
0,0,ios,US,2025-01-07,19,6,64.252830,0.0,4,1,1,0.0
1,1,ios,US,2025-01-26,2,2,14.305001,0.0,2,0,0,0.0
2,2,ios,UK,2025-01-02,19,7,102.255638,0.0,3,0,0,0.0
3,3,android,IN,2025-01-19,6,3,31.861878,0.0,3,0,1,0.0
4,4,android,CA,2025-02-05,6,4,32.449207,0.0,3,1,0,0.0

In [59]:
processed_df.describe(include = 'all')

,user_id,MAX(platform),MAX(country),joining_date,unique_creators,total_session_7d,total_playtime_7d,total_spend_7d,active_days_7d,d1_retention_flag,d7_retention_flag,ltv_30d
count,4978.000000,4978,4978,4978,4978.000000,4978.000000,4978.000000,4978.000000,4978.000000,4978.000000,4978.000000,4978.000000
unique,NaN,3,4,45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,web,US,2025-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1716,1277,198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,2500.483126,NaN,NaN,NaN,14.032543,9.167738,114.566627,0.945910,4.361189,0.588188,0.508437,1.915623
std,1443.721875,NaN,NaN,NaN,9.794480,8.237568,105.341417,3.171391,1.846891,0.492211,0.499979,5.114650
min,0.000000,NaN,NaN,NaN,1.000000,1.000000,5.073930,0.000000,1.000000,0.000000,0.000000,0.000000
25%,1251.250000,NaN,NaN,NaN,6.000000,3.000000,42.178059,0.000000,3.000000,0.000000,0.000000,0.000000
50%,2499.500000,NaN,NaN,NaN,11.000000,6.000000,77.171421,0.000000,4.000000,1.000000,1.000000,0.000000
75%,3751.750000,NaN,NaN,NaN,19.000000,12.000000,152.329670,0.000000,6.000000,1.000000,1.000000,0.000000
max,4999.000000,NaN,NaN,NaN,51.000000,55.000000,798.519567,44.112869,7.000000,1.000000,1.000000,55.597312

In [60]:
processed_df[num_cols].skew() # sqrt/log transform

user_id             -0.000363
unique_creators      1.037530
total_session_7d     1.721187
total_playtime_7d    1.819218
total_spend_7d       5.064800
active_days_7d      -0.080272
d1_retention_flag   -0.358478
d7_retention_flag   -0.033763
ltv_30d              3.955807
dtype: float64

In [61]:
processed_df.isna().sum()

user_id              0
MAX(platform)        0
MAX(country)         0
joining_date         0
unique_creators      0
total_session_7d     0
total_playtime_7d    0
total_spend_7d       0
active_days_7d       0
d1_retention_flag    0
d7_retention_flag    0
ltv_30d              0
dtype: int64

## Feature engineering

In [62]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split

In [63]:
processed_df.dtypes

user_id                int64
MAX(platform)         object
MAX(country)          object
joining_date          object
unique_creators        int64
total_session_7d       int64
total_playtime_7d    float64
total_spend_7d       float64
active_days_7d         int64
d1_retention_flag      int64
d7_retention_flag      int64
ltv_30d              float64
dtype: object

In [64]:
num_cols = processed_df.select_dtypes(include = 'number').columns
num_cols

Index(['user_id', 'unique_creators', 'total_session_7d', 'total_playtime_7d',
       'total_spend_7d', 'active_days_7d', 'd1_retention_flag',
       'd7_retention_flag', 'ltv_30d'],
      dtype='object')

In [65]:
cat_cols = processed_df.select_dtypes(include = 'object').columns
cat_cols

Index(['MAX(platform)', 'MAX(country)', 'joining_date'], dtype='object')

In [131]:
processed_df = processed_df.sort_values(by = 'joining_date').reset_index(drop = True)

In [132]:
processed_df.head()

,user_id,MAX(platform),MAX(country),joining_date,unique_creators,total_session_7d,total_playtime_7d,total_spend_7d,active_days_7d,d1_retention_flag,d7_retention_flag,ltv_30d
0,2499,web,UK,2025-01-01,6,7,80.359712,0.0,5,1,0,0.000000
1,2127,ios,UK,2025-01-01,20,8,90.376932,0.0,6,1,0,3.909909
2,2084,web,IN,2025-01-01,26,11,138.710523,0.0,5,1,1,0.510291
3,267,android,US,2025-01-01,10,5,50.855062,0.0,4,1,0,0.000000
4,694,android,US,2025-01-01,29,39,608.039224,0.0,7,1,1,7.960739

In [133]:
# split train test to avoid leakage
X = processed_df.drop(columns = ['user_id','ltv_30d'])
y = processed_df[['joining_date','ltv_30d']]

In [134]:
X,y

(     MAX(platform) MAX(country) joining_date  unique_creators  \
 0              web           UK   2025-01-01                6
 1              ios           UK   2025-01-01               20
 2              web           IN   2025-01-01               26
 3          android           US   2025-01-01               10
 4          android           US   2025-01-01               29
 ...            ...          ...          ...              ...
 4973       android           US   2025-02-13                3
 4974           web           CA   2025-02-13                1
 4975           web           UK   2025-02-14                5
 4976       android           US   2025-02-14                1
 4977       android           UK   2025-02-17                2

       total_session_7d  total_playtime_7d  total_spend_7d  active_days_7d  \
 0                    7          80.359712             0.0               5
 1                    8          90.376932             0.0               6
 2                   11         138.710523             0.0               5
 3                    5          50.855062             0.0               4
 4                   39         608.039224             0.0               7
 ...                ...                ...             ...             ...
 4973                 1          16.979310             0.0               1
 4974                 1          19.540930             0.0               1
 4975                 3          38.767414             0.0               3
 4976                 1          13.558387             0.0               1
 4977                 1          16.229255             0.0               1

       d1_retention_flag  d7_retention_flag
 0                     1                  0
 1                     1                  0
 2                     1                  1
 3                     1                  0
 4                     1                  1
 ...                 ...                ...
 4973                  0                  0
 4974                  0                  0
 4975                  0                  1
 4976                  0                  0
 4977                  0                  0

 [4978 rows x 10 columns],
      joining_date   ltv_30d
 0      2025-01-01  0.000000
 1      2025-01-01  3.909909
 2      2025-01-01  0.510291
 3      2025-01-01  0.000000
 4      2025-01-01  7.960739
 ...           ...       ...
 4973   2025-02-13  0.000000
 4974   2025-02-13  0.000000
 4975   2025-02-14  0.000000
 4976   2025-02-14  0.000000
 4977   2025-02-17  0.000000

 [4978 rows x 2 columns])

In [135]:
num_cols = X.select_dtypes(include = 'number').columns
num_cols

Index(['unique_creators', 'total_session_7d', 'total_playtime_7d',
       'total_spend_7d', 'active_days_7d', 'd1_retention_flag',
       'd7_retention_flag'],
      dtype='object')

In [136]:
X[num_cols].skew()

unique_creators      1.037530
total_session_7d     1.721187
total_playtime_7d    1.819218
total_spend_7d       5.064800
active_days_7d      -0.080272
d1_retention_flag   -0.358478
d7_retention_flag   -0.033763
dtype: float64

In [137]:
y['ltv_30d'].skew()

np.float64(3.9558069791817996)

In [138]:
X['total_spend_7d'] = np.sqrt(X['total_spend_7d'])

In [139]:
y['ltv_30d'] = np.log1p(y['ltv_30d'])

/var/folders/qh/wcp4hdh55d56zf2h540jdxlr0000gn/T/ipykernel_62040/1748337833.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['ltv_30d'] = np.log1p(y['ltv_30d'])

In [140]:
X['total_spend_7d'].skew()

np.float64(2.828359525631683)

In [141]:
y['ltv_30d'].skew()

np.float64(1.8455205967175072)

In [142]:
upper = y['ltv_30d'].quantile(0.995)
y['ltv_30d'] = y['ltv_30d'].clip(upper = upper)

/var/folders/qh/wcp4hdh55d56zf2h540jdxlr0000gn/T/ipykernel_62040/711435594.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['ltv_30d'] = y['ltv_30d'].clip(upper = upper)

In [145]:
processed_df['joining_date'] = pd.to_datetime(processed_df['joining_date'])

In [151]:
cut_ind = int(len(processed_df.index)*0.8)

In [155]:
cut_date = processed_df.loc[cut_ind]['joining_date']

In [156]:
cut_date

Timestamp('2025-01-26 00:00:00')

In [125]:
# split train and test based on first joining date
# cutoff = processed_df['joining_date'].nunique() * 0.8

In [126]:
# cutoff

In [157]:
X_train = X[pd.to_datetime(X['joining_date'])<=cutoff]
X_test = X[pd.to_datetime(X['joining_date'])>cutoff]
y_train = y[pd.to_datetime(y['joining_date'])<=cutoff]
y_test = y[pd.to_datetime(y['joining_date'])>cutoff]

In [158]:
X_train.shape,X_test.shape

((4117, 10), (861, 10))

In [160]:
861/X.shape[0]

0.17296102852551226

In [161]:
X_train.head()

,MAX(platform),MAX(country),joining_date,unique_creators,total_session_7d,total_playtime_7d,total_spend_7d,active_days_7d,d1_retention_flag,d7_retention_flag
0,web,UK,2025-01-01,6,7,80.359712,0.0,5,1,0
1,ios,UK,2025-01-01,20,8,90.376932,0.0,6,1,0
2,web,IN,2025-01-01,26,11,138.710523,0.0,5,1,1
3,android,US,2025-01-01,10,5,50.855062,0.0,4,1,0
4,android,US,2025-01-01,29,39,608.039224,0.0,7,1,1

In [162]:
X_test.head()

,MAX(platform),MAX(country),joining_date,unique_creators,total_session_7d,total_playtime_7d,total_spend_7d,active_days_7d,d1_retention_flag,d7_retention_flag
4117,ios,CA,2025-01-27,7,3,25.171890,0.000000,2,0,0
4118,android,CA,2025-01-27,2,2,25.546162,0.000000,2,0,0
4119,web,CA,2025-01-27,19,23,244.130490,0.453127,7,1,1
4120,ios,IN,2025-01-27,9,2,17.892521,0.000000,2,0,0
4121,web,UK,2025-01-27,22,15,193.350842,0.000000,7,1,1

In [163]:
y_train.head()

  joining_date   ltv_30d
0   2025-01-01  0.000000
1   2025-01-01  1.591255
2   2025-01-01  0.412302
3   2025-01-01  0.000000
4   2025-01-01  2.192853

In [164]:
y_test.head()

     joining_date   ltv_30d
4117   2025-01-27  2.395777
4118   2025-01-27  0.000000
4119   2025-01-27  2.217846
4120   2025-01-27  0.000000
4121   2025-01-27  2.739300

In [165]:
# Baseline
from sklearn.linear_model import LinearRegression

In [167]:
num_pipeline = Pipeline([
    ('impute', SimpleImputer(strategy = 'median')),
    ('norm', StandardScaler())
])

NameError: name 'SimpleImputer' is not defined

In [106]:
cardinality = dict(X_train[cat_cols].nunique())
cardinality

{'MAX(platform)': np.int64(3),
 'MAX(country)': np.int64(4),
 'joining_date': np.int64(26)}

In [168]:
cat_pipeline = Pipeline([
    ('onehot', OneHotEncoder(sparse_output = False, handle_unknown = 'ignore')),
])

In [169]:
cat_pipeline

Pipeline(steps=[('onehot',
                 OneHotEncoder(handle_unknown='ignore', sparse_output=False))])

In [174]:
preprocessor = ColumnTransformer([
    ('cat',cat_pipeline, ['MAX(platform)','MAX(country)']),
    ('num','passthrough', num_cols)
])

In [175]:
preprocessor

ColumnTransformer(transformers=[('cat',
                                 Pipeline(steps=[('onehot',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['MAX(platform)', 'MAX(country)']),
                                ('num', 'passthrough',
                                 Index(['unique_creators', 'total_session_7d', 'total_playtime_7d',
       'total_spend_7d', 'active_days_7d', 'd1_retention_flag',
       'd7_retention_flag'],
      dtype='object'))])

In [179]:
baseline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [180]:
baseline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['MAX(platform)',
                                                   'MAX(country)']),
                                                 ('num', 'passthrough',
                                                  Index(['unique_creators', 'total_session_7d', 'total_playtime_7d',
       'total_spend_7d', 'active_days_7d', 'd1_retention_flag',
       'd7_retention_flag'],
      dtype='object'))])),
                ('regressor', LinearRegression())])

In [182]:
X_train

,MAX(platform),MAX(country),joining_date,unique_creators,total_session_7d,total_playtime_7d,total_spend_7d,active_days_7d,d1_retention_flag,d7_retention_flag
0,web,UK,2025-01-01,6,7,80.359712,0.000000,5,1,0
1,ios,UK,2025-01-01,20,8,90.376932,0.000000,6,1,0
2,web,IN,2025-01-01,26,11,138.710523,0.000000,5,1,1
3,android,US,2025-01-01,10,5,50.855062,0.000000,4,1,0
4,android,US,2025-01-01,29,39,608.039224,0.000000,7,1,1
...,...,...,...,...,...,...,...,...,...,...
4112,web,US,2025-01-26,23,6,65.497016,0.000000,5,0,1
4113,android,CA,2025-01-26,32,23,224.306994,0.000000,7,1,1
4114,android,CA,2025-01-26,12,2,23.720831,0.000000,2,1,0
4115,web,UK,2025-01-26,19,13,134.728210,1.263190,6,1,1
4116,ios,CA,2025-01-26,19,44,463.467865,3.656657,7,1,1

In [183]:
baseline.fit(X_train.drop(columns = 'joining_date'),y_train.drop(columns = 'joining_date'))

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['MAX(platform)',
                                                   'MAX(country)']),
                                                 ('num', 'passthrough',
                                                  Index(['unique_creators', 'total_session_7d', 'total_playtime_7d',
       'total_spend_7d', 'active_days_7d', 'd1_retention_flag',
       'd7_retention_flag'],
      dtype='object'))])),
                ('regressor', LinearRegression())])

In [226]:
baseline.named_steps['regressor'].coef_

array([[ 2.64261400e-03, -2.11507566e-02,  1.85081426e-02,
         1.10282491e-03,  3.08644978e-02, -7.80980607e-05,
        -3.18892246e-02,  4.11297687e-02,  3.08928773e-02,
         7.34306074e-05,  2.66063714e-02, -7.73100846e-02,
        -1.94707838e-02, -9.45869690e-03]])

In [227]:
np.exp(-2.11507566e-02) - 1

np.float64(-0.020928648025228425)

In [204]:
y_pred_baseline = baseline.predict(X_test)

In [206]:
y_pred_baseline = np.maximum(y_pred_baseline, 0)

In [207]:
y_pred_baseline

array([[1.28392948e-01],
       [0.00000000e+00],
       [8.92121053e-01],
       [2.08986753e-01],
       [7.51401562e-01],
       [0.00000000e+00],
       [4.21919170e-01],
       [5.31524742e-01],
       [6.46341360e-02],
       [1.17731300e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.19617639e-01],
       [4.37389664e-01],
       [2.81078855e-01],
       [1.18855212e-01],
       [2.69239746e+00],
       [0.00000000e+00],
       [3.62161102e-01],
       [8.10959499e-01],
       [1.10915740e-01],
       [0.00000000e+00],
       [1.01208370e+00],
       [0.00000000e+00],
       [3.77528151e-01],
       [1.75244054e+00],
       [2.04132271e-01],
       [0.00000000e+00],
       [2.22091689e-01],
       [1.37501994e+00],
       [3.68034108e-01],
       [9.31061871e-01],
       [1.11171985e-01],
       [0.00000000e+00],
       [1.38302557e-01],
       [1.93312242e-01],
       [2.20018466e-01],
       [1.42900052e+00],
       [2.29690062e-01],
       [1.37508101e+00],
       [1.99852745e-01],
       [7.41894308e-01],
       [1.35131684e+00],
       [2.00398814e-01],
       [0.00000000e+00],
       [5.97070601e-01],
       [1.45623968e+00],
       [3.55778331e-01],
       [1.27700474e+00],
       [4.38028469e-02],
       [5.42303286e-02],
       [6.80784645e-01],
       [1.13778123e+00],
       [0.00000000e+00],
       [6.66188345e-01],
       [2.05556369e-02],
       [2.40460278e-01],
       [4.11244304e-01],
       [2.29787279e-01],
       [0.00000000e+00],
       [1.47722297e-01],
       [8.80027045e-01],
       [6.16677740e-01],
       [1.61987132e-01],
       [0.00000000e+00],
       [1.86683727e+00],
       [1.20826899e+00],
       [3.56620282e-01],
       [4.15989315e-01],
       [3.34879158e-02],
       [2.74452768e-01],
       [7.96916006e-01],
       [1.56183125e-01],
       [4.54071858e-01],
       [3.10126540e-01],
       [2.25599550e-01],
       [4.83115037e-01],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.93949717e-01],
       [1.42327376e+00],
       [4.48282004e-01],
       [2.75517756e-01],
       [4.33931864e-01],
       [1.17787417e+00],
       [2.46479514e-01],
       [5.69568661e-01],
       [9.56144006e-01],
       [0.00000000e+00],
       [1.02978793e+00],
       [1.91903638e+00],
       [4.81088941e-01],
       [2.05304405e+00],
       [1.48441727e-01],
       [2.41054334e-01],
       [1.83222304e+00],
       [5.30279419e-02],
       [3.70007465e-01],
       [1.73096981e-01],
       [5.86305881e-01],
       [1.12206637e-01],
       [4.16297430e-01],
       [9.95329870e-02],
       [3.88950863e-01],
       [0.00000000e+00],
       [5.30483278e-01],
       [1.48669304e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.82735759e-01],
       [2.57477900e-01],
       [8.36493009e-02],
       [6.86464498e-01],
       [5.49891719e-01],
       [0.00000000e+00],
       [1.05168932e+00],
       [1.37658136e+00],
       [4.37547734e-01],
       [2.38407277e-01],
       [7.26477767e-01],
       [2.36110365e-01],
       [2.50764248e-01],
       [2.15833169e-01],
       [1.71906113e-01],
       [1.12849311e-01],
       [0.00000000e+00],
       [9.07935942e-01],
       [7.44741347e-01],
       [2.46845475e-01],
       [3.73520738e-01],
       [7.82014970e-01],
       [9.39483946e-02],
       [1.12280019e+00],
       [7.64376177e-02],
       [2.83482869e-01],
       [1.44809775e-03],
       [2.64724486e-01],
       [2.38400993e-01],
       [8.14607050e-02],
       [1.78908892e-01],
       [8.78398099e-01],
       [1.56409948e-01],
       [4.67685880e-01],
       [1.91290253e+00],
       [2.47648176e-01],
       [1.00951346e+00],
       [5.10984064e-01],
       [0.00000000e+00],
       [1.02183808e+00],
       [1.95930192e-01],
       [7.92029155e-01],
       [6.86896724e-02],
       [1.02880733e-01],
       [8.05822257e-02],
       [2.04174539e-01],
       [7.42738293e-01],
       [0.00000000e+00],
       [2.84684472e-01],
       [1.07752573e+00],
       [1.98026777e+00],
       [9.77303572e-01],
       [2.84109907e-01],
       [0.00000000e+00],
       [0.00000000e+00],
       [3.63832697e-01],
       [1.40369473e-01],
       [1.78140755e+00],
       [1.47667281e+00],
       [2.74112163e-01],
       [4.15730031e-01],
       [4.54753143e-01],
       [1.90391174e-02],
       [0.00000000e+00],
       [2.38518836e-01],
       [8.68030200e-01],
       [6.23003189e-01],
       [1.18910336e+00],
       [5.15259837e-01],
       [6.68986734e-01],
       [1.33448089e-03],
       [8.25061514e-01],
       [1.26259188e-01],
       [1.51601214e-01],
       [7.02487717e-01],
       [0.00000000e+00],
       [7.28201184e-01],
       [1.32151668e+00],
       [3.27209787e-01],
       [4.17655214e-01],
       [6.84261569e-02],
       [0.00000000e+00],
       [1.47627021e+00],
       [9.06730663e-02],
       [0.00000000e+00],
       [3.59771969e-01],
       [0.00000000e+00],
       [7.50894537e-01],
       [4.17245172e-01],
       [4.92408846e-01],
       [1.54416364e-01],
       [5.53085546e-02],
       [2.66727461e-02],
       [1.95029221e-01],
       [2.12411984e+00],
       [3.22754768e-02],
       [8.36598225e-01],
       [1.92550107e-01],
       [1.01286404e+00],
       [9.48476795e-02],
       [0.00000000e+00],
       [0.00000000e+00],
       [2.04028904e-01],
       [2.53027332e-01],
       [0.00000000e+00],
       [5.47041558e-02],
       [1.76612630e-01],
       [6.08067031e-01],
       [4.60599461e-01],
       [2.65064489e-01],
       [0.00000000e+00],
       [1.23513517e-01],
       [1.86206858e-01],
       [1.62940367e-01],
       [2.95370665e-01],
       [2.28274454e+00],
       [0.00000000e+00],
       [5.11672858e-01],
       [2.64814695e-01],
       [6.72311741e-02],
       [2.12647092e-01],
       [1.66920644e-01],
       [2.28081275e-01],
       [1.01127791e-01],
       [7.80808498e-01],
       [3.87557819e-02],
       [7.24356798e-01],
       [9.32453475e-02],
       [3.41227381e-01],
       [6.78925884e-01],
       [4.78058641e-01],
       [0.00000000e+00],
       [4.07000803e-01],
       [1.97141718e-01],
       [3.79971520e-01],
       [1.07763032e-01],
       [4.58170503e-02],
       [6.60803373e-02],
       [0.00000000e+00],
       [2.43823885e-01],
       [4.25792839e-01],
       [3.17935961e-01],
       [2.38004931e-01],
       [3.97351206e-01],
       [4.81521746e-02],
       [6.16594742e-02],
       [2.32723297e-01],
       [3.39136860e-01],
       [6.88368394e-01],
       [2.69964529e-01],
       [2.00740137e-01],
       [1.87156769e-01],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.59371679e-01],
       [1.41620253e-01],
       [1.30536280e-01],
       [8.35160386e-03],
       [0.00000000e+00],
       [9.74466264e-01],
       [3.97101727e-01],
       [3.25088555e-01],
       [1.41133803e-02],
       [8.31911548e-01],
       [3.59605508e-01],
       [1.31688022e-01],
       [4.47425912e-02],
       [2.39521009e-02],
       [7.88961642e-02],
       [7.22489691e-01],
       [3.29653373e-01],
       [7.22473193e-01],
       [2.01218497e-01],
       [2.36225688e+00],
       [3.09616083e-01],
       [6.53059183e-01],
       [2.75598133e-01],
       [8.20713017e-01],
       [7.40516730e-01],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.27263270e-01],
       [8.92012318e-01],
       [0.00000000e+00],
       [4.02713629e-01],
       [1.41803998e+00],
       [5.36938231e-01],
       [9.14367492e-01],
       [6.55336116e-02],
       [1.24513744e-02],
       [4.42001105e-01],
       [3.17649682e-01],
       [0.00000000e+00],
       [1.01495490e+00],
       [3.84966413e-01],
       [5.22801994e-01],
       [1.98094578e-01],
       [9.51381853e-01],
       [0.00000000e+00],
       [4.60098717e-01],
       [2.28409456e-01],
       [9.90799188e-01],
       [1.16113981e+00],
       [1.25955547e+00],
       [2.08771122e-01],
       [3.17825736e-01],
       [1.41481205e+00],
       [9.62817553e-03],
       [0.00000000e+00],
       [5.44988270e-01],
       [6.22124509e-01],
       [1.40349055e+00],
       [1.00617341e+00],
       [4.29582112e-01],
       [5.22564828e-01],
       [3.71701557e-01],
       [0.00000000e+00],
       [3.36949354e-02],
       [5.50994426e-02],
       [6.38977243e-01],
       [1.88580574e-02],
       [4.43896598e-01],
       [4.23621827e-01],
       [1.25262960e-01],
       [1.59853166e+00],
       [3.19385222e-03],
       [3.82128114e-01],
       [1.12755997e+00],
       [3.33304978e-01],
       [1.42916061e+00],
       [2.05020906e-01],
       [4.02658409e-01],
       [4.87142105e-01],
       [1.08571747e+00],
       [2.17971883e-02],
       [4.92418404e-01],
       [4.38531661e-02],
       [1.08601777e+00],
       [0.00000000e+00],
       [3.50162463e-01],
       [3.37174781e-01],
       [1.05108080e+00],
       [3.46056201e-01],
       [3.70703758e-01],
       [6.94842641e-03],
       [1.19067256e-01],
       [4.85294586e-02],
       [2.09801993e-02],
       [3.28042403e-01],
       [1.67290807e-01],
       [2.65195991e-01],
       [1.87783765e-01],
       [2.16650471e-01],
       [6.56865318e-01],
       [1.51753892e-01],
       [9.08036733e-01],
       [7.56125427e-02],
       [8.06135630e-01],
       [3.27049730e-01],
       [1.39640901e+00],
       [9.97618506e-02],
       [7.46671412e-02],
       [0.00000000e+00],
       [7.15086283e-01],
       [3.32827901e-01],
       [0.00000000e+00],
       [6.40278586e-01],
       [3.21242791e-01],
       [9.95205922e-01],
       [0.00000000e+00],
       [5.42033070e-01],
       [5.58042349e-01],
       [1.13125426e-01],
       [1.26416978e-01],
       [4.16895264e-01],
       [1.68365972e-01],
       [0.00000000e+00],
       [7.88980232e-01],
       [2.89434397e-01],
       [6.28757761e-01],
       [4.94589685e-01],
       [1.71026377e-01],
       [2.92468152e-01],
       [1.75356140e-01],
       [5.32001432e-04],
       [1.51801073e+00],
       [0.00000000e+00],
       [1.66478460e-01],
       [0.00000000e+00],
       [1.99643045e-01],
       [9.03944568e-01],
       [3.98577531e-02],
       [2.33700158e-01],
       [7.30565817e-01],
       [9.88354325e-01],
       [6.97694041e-01],
       [8.40380546e-01],
       [1.32193771e+00],
       [5.49922762e-01],
       [0.00000000e+00],
       [1.06478720e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [4.60274015e-01],
       [0.00000000e+00],
       [1.17295459e+00],
       [3.01275438e-01],
       [9.79817234e-02],
       [2.74029965e-01],
       [8.06769253e-01],
       [0.00000000e+00],
       [4.12367079e-01],
       [6.31453632e-01],
       [5.85079024e-01],
       [9.44904731e-01],
       [3.50274739e-01],
       [2.95589537e+00],
       [1.71277517e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [8.40044596e-02],
       [1.47429580e+00],
       [8.94804917e-01],
       [2.44803758e-01],
       [2.84031354e-01],
       [5.36217540e-02],
       [3.01425539e-01],
       [4.04635895e-01],
       [1.23580197e-01],
       [1.78282515e-01],
       [4.24392027e-01],
       [1.09276350e+00],
       [5.40626889e-02],
       [6.77611570e-01],
       [2.57191417e-02],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.23656996e+00],
       [1.00996116e+00],
       [8.88025432e-01],
       [1.52217003e+00],
       [1.23075330e+00],
       [1.22295115e+00],
       [4.60211636e-01],
       [1.51608219e-01],
       [3.86856413e-01],
       [4.19137752e-02],
       [6.28237087e-01],
       [3.15016221e-01],
       [0.00000000e+00],
       [0.00000000e+00],
       [6.81119173e-01],
       [1.90679211e-03],
       [1.62426098e-01],
       [3.88307869e-01],
       [2.56212355e-01],
       [2.92175573e-01],
       [9.95426681e-02],
       [1.94884731e-01],
       [5.31327839e-01],
       [1.39416309e+00],
       [3.95018826e-01],
       [3.60784757e-01],
       [4.09064993e-01],
       [1.17104413e-01],
       [1.11463322e-01],
       [2.16726208e-01],
       [2.96879233e-01],
       [8.47703166e-01],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.50997134e+00],
       [4.89840346e-01],
       [5.32306651e-02],
       [2.64955397e-03],
       [3.20984780e-01],
       [4.11459151e-01],
       [3.94748834e-01],
       [1.24037804e+00],
       [6.89841973e-01],
       [3.19156791e-01],
       [1.53116942e+00],
       [0.00000000e+00],
       [1.19582895e-01],
       [0.00000000e+00],
       [5.21614881e-02],
       [4.53315654e-02],
       [1.60891040e+00],
       [5.77101818e-01],
       [1.90035044e+00],
       [1.01569651e+00],
       [9.44618448e-03],
       [1.46564263e-01],
       [1.80505962e-01],
       [9.35224937e-01],
       [8.48047577e-01],
       [1.29832412e-01],
       [1.51485068e+00],
       [1.46522212e-01],
       [1.89352681e+00],
       [7.78241166e-02],
       [8.90947256e-01],
       [1.84262267e-01],
       [2.14748870e-01],
       [5.37578469e-01],
       [0.00000000e+00],
       [3.93130682e-01],
       [5.12609391e-01],
       [2.39214345e-01],
       [3.10384478e-01],
       [0.00000000e+00],
       [2.87170809e-01],
       [2.04495393e-01],
       [6.99534043e-01],
       [7.47717914e-01],
       [1.59195425e+00],
       [1.80544675e-01],
       [4.38592902e-02],
       [9.55827553e-02],
       [1.91526261e-01],
       [4.47990884e-01],
       [1.74222263e-01],
       [0.00000000e+00],
       [5.40480356e-01],
       [0.00000000e+00],
       [1.85061381e+00],
       [2.28207359e+00],
       [0.00000000e+00],
       [5.73496640e-02],
       [1.51013139e-01],
       [5.30454215e-01],
       [5.62707012e-01],
       [2.50617290e-01],
       [2.25385688e-01],
       [0.00000000e+00],
       [2.48757212e-01],
       [5.41171004e-01],
       [4.81186636e-02],
       [1.17538763e+00],
       [3.50903973e-01],
       [3.13387982e-01],
       [3.79019665e-02],
       [3.60554458e-01],
       [4.73803791e-01],
       [1.38150103e-01],
       [0.00000000e+00],
       [3.75276239e-01],
       [3.45610873e-01],
       [6.06270194e-01],
       [9.06947705e-01],
       [4.54900036e-02],
       [2.18861206e-01],
       [2.54362856e-01],
       [8.68353550e-02],
       [1.39780371e+00],
       [3.17677229e-01],
       [0.00000000e+00],
       [4.86845624e-02],
       [3.33254266e-01],
       [0.00000000e+00],
       [1.30636893e+00],
       [2.31702175e-01],
       [2.68455438e-01],
       [5.97258755e-01],
       [7.78964065e-01],
       [3.39543392e-01],
       [3.98298959e-01],
       [0.00000000e+00],
       [0.00000000e+00],
       [6.40601606e-01],
       [1.01451028e+00],
       [2.10296481e-01],
       [1.28487640e-01],
       [1.61133220e-01],
       [8.58593305e-02],
       [1.49089187e-01],
       [1.84109966e+00],
       [2.09564680e-01],
       [1.39770142e+00],
       [2.25160829e-01],
       [5.02232584e-01],
       [1.25545732e+00],
       [2.05701556e-01],
       [6.13510811e-01],
       [8.60101714e-01],
       [1.04307006e-01],
       [9.86270724e-04],
       [4.92651023e-02],
       [0.00000000e+00],
       [9.32811881e-01],
       [0.00000000e+00],
       [2.92003988e-01],
       [2.46437217e-01],
       [2.21774254e-01],
       [0.00000000e+00],
       [3.86866873e-02],
       [2.61107646e-01],
       [3.08532374e-01],
       [5.79352793e-01],
       [4.66216908e-02],
       [2.45385010e+00],
       [3.52334929e-01],
       [0.00000000e+00],
       [5.19689678e-01],
       [9.37333785e-01],
       [6.94086196e-01],
       [1.33176417e+00],
       [3.80442449e-01],
       [1.09620049e-01],
       [7.82603791e-01],
       [9.77495030e-01],
       [8.37768589e-01],
       [8.33849736e-02],
       [5.34948019e-02],
       [0.00000000e+00],
       [3.23534093e-01],
       [0.00000000e+00],
       [8.46179551e-01],
       [1.08034207e+00],
       [6.65521133e-01],
       [0.00000000e+00],
       [8.48174070e-01],
       [0.00000000e+00],
       [3.41374977e-02],
       [1.71582501e+00],
       [3.30901465e-01],
       [3.52206505e-01],
       [5.59184352e-01],
       [2.93341374e-01],
       [5.88916814e-01],
       [2.70138627e-01],
       [0.00000000e+00],
       [2.27423467e-01],
       [6.04751471e-01],
       [1.48017619e-01],
       [4.74955548e-02],
       [1.24752912e+00],
       [4.76798773e-01],
       [4.40826032e-01],
       [4.34547407e-02],
       [1.63209091e-01],
       [1.25106633e-01],
       [2.70150066e-01],
       [1.81386967e-02],
       [1.38530634e+00],
       [5.21713031e-01],
       [1.28925780e-01],
       [7.82243585e-02],
       [6.73562571e-01],
       [9.14266436e-03],
       [1.51180551e+00],
       [4.28345672e-01],
       [0.00000000e+00],
       [5.55275147e-01],
       [0.00000000e+00],
       [3.06939140e-01],
       [2.60045478e-01],
       [1.93398439e-01],
       [1.37317929e+00],
       [7.64098170e-02],
       [2.36681818e-01],
       [2.03614652e-01],
       [7.47035886e-01],
       [4.51022843e-01],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.20351066e+00],
       [5.73312085e-01],
       [1.68045765e+00],
       [4.91419312e-01],
       [2.70770124e-01],
       [4.93016514e-02],
       [6.43174792e-02],
       [3.48700330e-01],
       [1.49430395e-01],
       [2.73024741e-01],
       [2.72258770e-01],
       [4.40528051e-01],
       [1.61711141e-01],
       [6.69976511e-01],
       [8.95694770e-01],
       [1.13382738e+00],
       [1.81808353e-01],
       [1.78942097e-01],
       [1.41950418e-01],
       [3.10504092e-01],
       [1.87784427e-01],
       [0.00000000e+00],
       [3.61718518e-01],
       [6.12681006e-02],
       [9.16026610e-02],
       [2.66866070e-01],
       [8.50983944e-03],
       [3.04722849e-01],
       [1.79252812e-01],
       [1.82824452e-01],
       [4.73930611e-02],
       [0.00000000e+00],
       [2.57763288e-01],
       [1.48539345e-01],
       [1.20890605e-01],
       [1.80104997e-01],
       [4.31295540e-01],
       [0.00000000e+00],
       [0.00000000e+00],
       [6.49222822e-01],
       [0.00000000e+00],
       [6.05870679e-01],
       [3.09546744e-01],
       [1.67109941e-02],
       [1.77506831e-01],
       [5.06641929e-01],
       [4.30163834e-02],
       [3.17776570e-01],
       [1.39852675e-01],
       [3.53788050e-02],
       [2.84631328e-01],
       [6.74487233e-01],
       [2.32119413e-01],
       [0.00000000e+00],
       [1.20201551e-01],
       [1.03769727e-01],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [3.16918334e-01],
       [0.00000000e+00],
       [2.65623034e-01],
       [2.93295830e-02],
       [5.22615638e-02],
       [1.01558030e-01],
       [1.49720064e-01],
       [1.34293245e-01],
       [3.93152209e-01],
       [5.67945140e-01],
       [5.21974583e-02],
       [7.37790962e-03],
       [2.21253542e-01],
       [6.68751986e-02],
       [0.00000000e+00],
       [1.07638608e+00],
       [6.85369301e-02],
       [1.73821479e-01],
       [1.47416282e-01],
       [0.00000000e+00],
       [3.03254626e-01],
       [8.34107367e-02],
       [2.52039397e-01],
       [1.61315348e-02],
       [2.82622268e-01],
       [3.48549364e-01],
       [7.84966161e-02],
       [6.45104655e-02],
       [1.56724579e-01],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.05937178e+00],
       [0.00000000e+00],
       [1.68775546e-01],
       [1.51297572e-01],
       [6.77017403e-02],
       [1.02595478e-01],
       [1.95536137e-01],
       [4.73672919e-01],
       [0.00000000e+00],
       [3.52294365e-02],
       [1.45358264e-02],
       [4.48501069e-02],
       [1.03712245e-01],
       [0.00000000e+00],
       [4.18165867e-01],
       [0.00000000e+00],
       [3.05721167e-01],
       [3.76524039e-02],
       [2.39002562e-01],
       [2.73285506e-02],
       [1.06481253e-01],
       [2.87965297e-01],
       [4.41371613e-02],
       [0.00000000e+00],
       [3.80647871e-02],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00],
       [5.49498486e-01],
       [2.58311371e-01],
       [0.00000000e+00],
       [5.50447654e-02],
       [0.00000000e+00],

In [191]:
y_test['ltv_30d']

4117    2.395777
4118    0.000000
4119    2.217846
4120    0.000000
4121    2.739300
          ...
4973    0.000000
4974    0.000000
4975    0.000000
4976    0.000000
4977    0.000000
Name: ltv_30d, Length: 861, dtype: float64

In [209]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [211]:
rmse_log = np.sqrt(mean_squared_error(y_test.drop(columns = ['joining_date']),y_pred_baseline))
mae_log = mean_absolute_error(y_test.drop(columns = ['joining_date']),y_pred_baseline)
r2 = r2_score(y_test.drop(columns = ['joining_date']),y_pred_baseline)

In [212]:
rmse_log, mae_log, r2

(np.float64(0.7051085579591273),
 np.float64(0.43800573101134366),
 0.28474952642838003)

In [224]:
baseline.coef_

AttributeError: 'Pipeline' object has no attribute 'coef_'

In [213]:
# surrogate assumption check

In [214]:
y_test_eval = y_test.copy()

In [218]:
y_test_eval['platform'] = X_test['MAX(platform)']
y_test_eval['country'] = X_test['MAX(country)']

In [215]:
y_test_eval['y_pred'] = y_pred_baseline

In [221]:
cohort_metrics = y_test_eval.groupby(['country']).apply(lambda x: pd.Series({'rmse_log':np.sqrt(mean_squared_error(x['ltv_30d'],x['y_pred'])),
'maelog': mean_absolute_error(x['ltv_30d'],x['y_pred']),
'r2': r2_score(x['ltv_30d'],x['y_pred'])}))

/var/folders/qh/wcp4hdh55d56zf2h540jdxlr0000gn/T/ipykernel_62040/3952090448.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  cohort_metrics = y_test_eval.groupby(['country']).apply(lambda x: pd.Series({'rmse_log':np.sqrt(mean_squared_error(x['ltv_30d'],x['y_pred'])),

In [222]:
cohort_metrics

         rmse_log    maelog        r2
country
CA       0.603472  0.378530  0.301625
IN       0.772240  0.480676  0.236365
UK       0.714213  0.436215  0.310676
US       0.706560  0.447693  0.285822

In [ ]:
# sql: event level -> user level, get features like 1d retention, 7d retention
# python: 1. check skew, log transform y; 2. split X and y based on joining date 3. feature engineering 4. modeling 5. eval overral 6. slice analysis 7.interpretation

## Practice 2

In [ ]:
Check stationary!

In [230]:
df

,user_id,date,sessions,play_time,spend,creator_id,platform,country
0,0,2025-01-07,1,11.888733,0.000000,373,ios,US
1,0,2025-01-08,1,19.548648,0.000000,492,ios,US
2,0,2025-01-10,3,16.037809,0.000000,475,ios,US
3,0,2025-01-13,1,16.777639,0.000000,563,ios,US
4,0,2025-01-14,3,35.272466,0.000000,274,ios,US
...,...,...,...,...,...,...,...,...
70553,4999,2025-01-26,3,32.599466,0.000000,688,web,IN
70554,4999,2025-01-27,2,16.721781,0.000000,450,web,IN
70555,4999,2025-01-28,2,18.727887,8.605824,83,web,IN
70556,4999,2025-01-29,2,18.667530,0.000000,767,web,IN
70557,4999,2025-01-30,3,57.009896,2.185158,560,web,IN

In [ ]:
 - suggorate metrics to predict LTV - need assumptions(check)
    - revenue - primary metric
 - Features:
    - volume: number of seesions, total play time, total spend 
    - retention: active days in 7 days, d1 retention, d7 retention
    - marketplace: # of unique creator
    - cohort: platform, country
- train and test
    - train: day 0-6 
    - test: day 7-29 

- feature engineering

- baseline - 7d average for 30d
- advanced model - linear regression

In [ ]:
with first_day_t as(
    select 
     user_id, 
     date as event_date,
     sessions,
     play_time,
     spend,
     creator_id,
     platform,
     country,
     MIN(date) over(partition by user_id) as first_day
    from df_table
),
day_diff_t as(
    select 
        *,
        DATEDIFF('day', first_day, event_date) as day_diff
    from first_day_t
)

select 
    user_id,
    max(platform),
    max(country),
    SUM(CASE WHEN day_diff between 0 and 6 then sessions else 0 end) as total_session_7d,
    SUM(CASE WHEN day_diff between 0 and 6 then play_time else 0 end) as total_playtime_7d, 
    SUM(CASE WHEN day_diff between 0 and 6 then spend else 0 end) as total_spend_7d,
    COUNT(DISTINCT CASE WEHN day_diff between 0 and 6 THEN creator_id END) AS unique_creator_ct_7d,
    COUNT(DISTINCT CASE WEHN day_diff between 0 and 6 THEN event_date END) AS active_days_7d,
    MAX(CASE WHEN day_diff = 1 THEN 1 ELSE 0 END) AS d1_retention_flag,
    MAX(CASE WHEN day_diff = 6 THEN 1 ELSE 0 END) AS d7_retention_flag,
    SUM(CASE WHEN day_diff between 7 and 29 then spend else 0 end) as ltv_30d
from day_diff_t
group by user_id

In [265]:
processed_df = pd.read_csv("/Users/zhuangdiezhou/Documents/Documents - Zhuangdie Alan Zhou's MacBook Pro - 1/Hi_Sexy/Interview/Roblox/user_activity_processed_updated.csv")

In [266]:
processed_df

,user_id,MAX(platform),MAX(country),joining_date,unique_creators,total_session_7d,total_playtime_7d,total_spend_7d,active_days_7d,d1_retention_flag,d7_retention_flag,ltv_30d
0,0,ios,US,2025-01-07,19,6,64.252830,0.000000,4,1,1,0.000000
1,1,ios,US,2025-01-26,2,2,14.305001,0.000000,2,0,0,0.000000
2,2,ios,UK,2025-01-02,19,7,102.255638,0.000000,3,0,0,0.000000
3,3,android,IN,2025-01-19,6,3,31.861878,0.000000,3,0,1,0.000000
4,4,android,CA,2025-02-05,6,4,32.449207,0.000000,3,1,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
4973,4995,android,CA,2025-01-21,16,7,64.361059,0.000000,5,1,1,1.569322
4974,4996,web,IN,2025-01-20,16,6,77.450134,0.000000,5,1,0,17.278959
4975,4997,ios,US,2025-01-04,15,7,68.683273,0.371573,4,1,0,0.000000
4976,4998,android,IN,2025-01-23,26,17,237.395735,0.000000,6,1,1,3.197765
4977,4999,web,IN,2025-01-11,20,27,437.237004,0.000000,7,1,1,10.790982

In [267]:
processed_df.describe(include = 'all')

,user_id,MAX(platform),MAX(country),joining_date,unique_creators,total_session_7d,total_playtime_7d,total_spend_7d,active_days_7d,d1_retention_flag,d7_retention_flag,ltv_30d
count,4978.000000,4978,4978,4978,4978.000000,4978.000000,4978.000000,4978.000000,4978.000000,4978.000000,4978.000000,4978.000000
unique,NaN,3,4,45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,web,US,2025-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1716,1277,198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,2500.483126,NaN,NaN,NaN,14.032543,9.167738,114.566627,0.945910,4.361189,0.588188,0.508437,1.915623
std,1443.721875,NaN,NaN,NaN,9.794480,8.237568,105.341417,3.171391,1.846891,0.492211,0.499979,5.114650
min,0.000000,NaN,NaN,NaN,1.000000,1.000000,5.073930,0.000000,1.000000,0.000000,0.000000,0.000000
25%,1251.250000,NaN,NaN,NaN,6.000000,3.000000,42.178059,0.000000,3.000000,0.000000,0.000000,0.000000
50%,2499.500000,NaN,NaN,NaN,11.000000,6.000000,77.171421,0.000000,4.000000,1.000000,1.000000,0.000000
75%,3751.750000,NaN,NaN,NaN,19.000000,12.000000,152.329670,0.000000,6.000000,1.000000,1.000000,0.000000
max,4999.000000,NaN,NaN,NaN,51.000000,55.000000,798.519567,44.112869,7.000000,1.000000,1.000000,55.597312

In [268]:
processed_df.isna().sum()

user_id              0
MAX(platform)        0
MAX(country)         0
joining_date         0
unique_creators      0
total_session_7d     0
total_playtime_7d    0
total_spend_7d       0
active_days_7d       0
d1_retention_flag    0
d7_retention_flag    0
ltv_30d              0
dtype: int64

In [269]:
num_cols = processed_df.select_dtypes(include = 'number').columns
num_cols

Index(['user_id', 'unique_creators', 'total_session_7d', 'total_playtime_7d',
       'total_spend_7d', 'active_days_7d', 'd1_retention_flag',
       'd7_retention_flag', 'ltv_30d'],
      dtype='object')

In [270]:
processed_df[num_cols].skew()

user_id             -0.000363
unique_creators      1.037530
total_session_7d     1.721187
total_playtime_7d    1.819218
total_spend_7d       5.064800
active_days_7d      -0.080272
d1_retention_flag   -0.358478
d7_retention_flag   -0.033763
ltv_30d              3.955807
dtype: float64

In [271]:
processed_df['ltv_30d'] = np.log1p(processed_df['ltv_30d'])

In [272]:
# split training and test

In [273]:
processed_df = processed_df.sort_values(by = 'joining_date').reset_index(drop = True)

In [274]:
cutoff_ind = int(len(processed_df['joining_date'])*0.8)
cutoff_ind

3982

In [275]:
cutoff_date = processed_df.iloc[cutoff_ind]['joining_date']

In [276]:
features = ['MAX(platform)', 'MAX(country)', 'joining_date',
       'unique_creators', 'total_session_7d', 'total_playtime_7d',
       'total_spend_7d', 'active_days_7d', 'd1_retention_flag',
       'd7_retention_flag',]
target = ['joining_date','ltv_30d']

In [277]:
processed_df.columns

Index(['user_id', 'MAX(platform)', 'MAX(country)', 'joining_date',
       'unique_creators', 'total_session_7d', 'total_playtime_7d',
       'total_spend_7d', 'active_days_7d', 'd1_retention_flag',
       'd7_retention_flag', 'ltv_30d'],
      dtype='object')

In [347]:
X_train = processed_df[processed_df['joining_date'] <= cutoff_date][features].drop(columns = 'joining_date')
y_train = processed_df[processed_df['joining_date'] <= cutoff_date][target].drop(columns = 'joining_date')

X_test = processed_df[processed_df['joining_date'] > cutoff_date][features].drop(columns = 'joining_date')
y_test = processed_df[processed_df['joining_date'] > cutoff_date][target].drop(columns = 'joining_date')

In [279]:
X_train.shape, X_test.shape

((4117, 9), (861, 9))

In [281]:
# Baseline
baseline_pred = X_test['total_spend_7d']/7 * (30-7)

In [286]:
baseline_pred = np.log1p(baseline_pred)

In [287]:
baseline_pred

4117    0.000000
4118    0.000000
4119    1.795792
4120    0.000000
4121    0.000000
          ...
4973    0.000000
4974    0.000000
4975    0.000000
4976    0.000000
4977    0.000000
Name: total_spend_7d, Length: 861, dtype: float64

In [288]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [334]:
mae_base = mean_absolute_error(y_test, baseline_pred)
rmse_bae = np.sqrt(mean_squared_error(y_test, baseline_pred))
r2_base = r2_score(y_test, baseline_pred)

In [335]:
print('mae_base',mae_base)
print('rmse_bae',rmse_bae)
print('r2_base',r2_base)

mae_base 0.5457414690186173
rmse_bae 1.1345008881805416
r2_base -0.8376900254053457

In [291]:
# stronger model

In [292]:
num_cols

Index(['user_id', 'unique_creators', 'total_session_7d', 'total_playtime_7d',
       'total_spend_7d', 'active_days_7d', 'd1_retention_flag',
       'd7_retention_flag', 'ltv_30d'],
      dtype='object')

In [298]:
cat_cols = X_train.select_dtypes(include = 'object').columns
cat_cols

Index(['MAX(platform)', 'MAX(country)'], dtype='object')

In [294]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split

In [ ]:
from import OneHotEncoder
from import Pipeline
from import train_test_split
from import ColumnTransformer

In [295]:
cat_pipeline = Pipeline([
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

In [296]:
cat_pipeline

Pipeline(steps=[('onehot',
                 OneHotEncoder(handle_unknown='ignore', sparse_output=False))])

In [313]:
preprocessor = ColumnTransformer([
    ('cat', cat_pipeline, cat_cols),
    ('num','passthrough', ['unique_creators', 'total_session_7d', 'total_playtime_7d',
       'total_spend_7d', 'active_days_7d', 'd1_retention_flag',
       'd7_retention_flag'])
])

In [314]:
preprocessor

ColumnTransformer(transformers=[('cat',
                                 Pipeline(steps=[('onehot',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 Index(['MAX(platform)', 'MAX(country)'], dtype='object')),
                                ('num', 'passthrough',
                                 ['unique_creators', 'total_session_7d',
                                  'total_playtime_7d', 'total_spend_7d',
                                  'active_days_7d', 'd1_retention_flag',
                                  'd7_retention_flag'])])

In [315]:
from sklearn.linear_model import LinearRegression

In [316]:
model = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [317]:
model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  Index(['MAX(platform)', 'MAX(country)'], dtype='object')),
                                                 ('num', 'passthrough',
                                                  ['unique_creators',
                                                   'total_session_7d',
                                                   'total_playtime_7d',
                                                   'total_spend_7d',
                                                   'active_days_7d',
                                                   'd1_retention_flag',
                                                   'd7_retention_flag'])])),
                ('regressor', LinearRegression())])

In [318]:
model.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  Index(['MAX(platform)', 'MAX(country)'], dtype='object')),
                                                 ('num', 'passthrough',
                                                  ['unique_creators',
                                                   'total_session_7d',
                                                   'total_playtime_7d',
                                                   'total_spend_7d',
                                                   'active_days_7d',
                                                   'd1_retention_flag',
                                                   'd7_retention_flag'])])),
                ('regressor', LinearRegression())])

In [337]:
y_pred = model.predict(X_test)

In [321]:
y_pred = np.maximum(y_pred,0)

In [338]:
y_pred

array([[ 3.95397080e-01],
       [-9.13598385e-02],
       [ 5.07640454e-01],
       [ 1.50239968e+00],
       [-8.56132104e-02],
       [-1.05110233e-01],
       [ 2.64349371e-01],
       [ 2.09950038e-01],
       [ 8.30463081e-02],
       [ 6.96931779e-01],
       [ 5.57072146e-01],
       [-5.79330309e-02],
       [ 1.03351266e+00],
       [ 1.39127882e+00],
       [ 4.05825193e-01],
       [ 4.19469260e-01],
       [ 1.83143270e-01],
       [ 1.15794011e-01],
       [ 1.00997332e+00],
       [ 2.39413650e-01],
       [ 2.80611810e-01],
       [ 4.40400134e-01],
       [ 1.18758741e+00],
       [ 2.52291651e-01],
       [ 5.82272285e-01],
       [ 9.69060631e-01],
       [-3.00660199e-02],
       [ 1.89565012e+00],
       [ 1.75216795e-01],
       [ 4.86362775e-01],
       [ 2.07571698e+00],
       [ 1.49952931e-01],
       [ 2.42347407e-01],
       [ 1.85623365e+00],
       [ 5.30709046e-02],
       [ 3.77694115e-01],
       [ 5.97233133e-01],
       [ 6.99146649e-01],
       [ 8.61969093e-02],
       [ 2.53664983e-01],
       [ 4.78336365e-01],
       [ 1.89653903e+00],
       [ 2.49811002e-01],
       [ 9.81046040e-01],
       [ 5.16255567e-01],
       [ 7.12316132e-02],
       [ 1.03245977e+00],
       [ 2.00811193e-01],
       [ 8.03436236e-01],
       [ 1.96380736e+00],
       [ 1.06291121e-01],
       [ 8.27108768e-02],
       [ 2.06599851e-01],
       [ 7.46766729e-01],
       [-9.54783485e-03],
       [ 2.86049066e-01],
       [ 1.09239735e+00],
       [-3.92815083e-02],
       [ 8.89667632e-01],
       [ 1.80695686e-01],
       [ 2.17880529e-01],
       [ 1.40291299e-01],
       [ 1.16010883e-01],
       [-6.85542145e-02],
       [ 9.19973164e-01],
       [ 7.13524910e-01],
       [ 2.48905640e-01],
       [ 3.79307428e-01],
       [ 7.92597206e-01],
       [ 9.42445386e-02],
       [ 1.14142706e+00],
       [ 8.04173293e-02],
       [ 2.88371962e-01],
       [-3.27230756e-02],
       [ 2.75488897e-01],
       [ 2.42492795e-01],
       [ 1.24870233e-01],
       [ 1.43845132e+00],
       [ 4.60468099e-01],
       [ 1.03742833e-01],
       [ 1.96021130e-01],
       [ 2.44187974e-01],
       [ 1.10868821e-01],
       [-7.92537373e-02],
       [ 1.02288952e+00],
       [-3.56801307e-03],
       [ 3.82469831e-01],
       [ 1.76863543e+00],
       [ 2.04330091e-01],
       [-6.16248938e-03],
       [ 2.23478255e-01],
       [ 1.35422988e+00],
       [-3.25702737e-02],
       [ 3.74169317e-01],
       [ 9.05352981e-01],
       [ 1.11942032e-01],
       [-3.56172947e-02],
       [ 1.19121414e-01],
       [ 1.51555531e-01],
       [ 3.63369919e-01],
       [ 2.24836568e-01],
       [ 2.68001977e+00],
       [-8.52458041e-02],
       [ 8.96022062e-01],
       [ 2.11242270e-01],
       [ 7.63036895e-01],
       [-6.83786647e-02],
       [ 1.29434218e-01],
       [ 4.27870675e-01],
       [ 1.21422771e-01],
       [ 6.43647412e-02],
       [ 1.19172910e+00],
       [-1.19176167e-01],
       [-1.47418052e-02],
       [ 1.23430439e-01],
       [ 4.23398669e-01],
       [ 2.82916745e-01],
       [ 5.37966403e-01],
       [ 8.23745364e-01],
       [ 1.40361513e+00],
       [ 2.31306635e-01],
       [ 1.39350914e+00],
       [ 8.89909383e-01],
       [ 6.22017101e-01],
       [ 1.66441777e-01],
       [-4.03157018e-02],
       [ 1.88653881e+00],
       [ 1.21955503e+00],
       [ 3.60209389e-01],
       [ 3.82844871e-01],
       [ 3.36516888e-02],
       [ 2.34942162e-01],
       [ 8.03348394e-01],
       [ 1.60244705e-01],
       [ 4.57808074e-01],
       [ 3.16236106e-01],
       [ 2.25386740e-01],
       [ 4.88212393e-01],
       [-4.22885809e-02],
       [ 2.35033881e-01],
       [ 1.48808230e-01],
       [-3.23588519e-02],
       [-6.62140945e-02],
       [ 4.13915719e-01],
       [ 1.97302142e-01],
       [ 7.50046922e-01],
       [ 1.33428448e+00],
       [ 2.02237129e-01],
       [-7.66106360e-02],
       [ 5.80425703e-01],
       [ 1.47092377e+00],
       [ 3.60776184e-01],
       [ 1.29075107e+00],
       [ 4.23561510e-02],
       [ 5.38819005e-02],
       [ 6.43088189e-01],
       [ 1.12017759e+00],
       [-1.22793681e-01],
       [ 6.75369737e-01],
       [ 2.36782886e-02],
       [ 1.80548051e-01],
       [-4.31481034e-02],
       [-7.35252020e-02],
       [ 1.63916295e-01],
       [ 1.16514251e-01],
       [ 1.34220496e-01],
       [-3.73539957e-02],
       [ 4.65636316e-02],
       [ 9.82982343e-01],
       [ 4.00821510e-01],
       [ 3.29284843e-01],
       [ 1.46326091e-02],
       [ 8.43934030e-01],
       [ 7.93809226e-02],
       [ 3.67487878e-01],
       [ 1.34436604e-01],
       [ 2.73595680e-01],
       [ 6.97136965e-01],
       [ 3.47249972e-01],
       [ 2.37520033e-01],
       [-1.08937962e-01],
       [ 4.12162243e-01],
       [ 2.01806946e-01],
       [ 3.83815916e-01],
       [ 1.08041983e-01],
       [ 4.68931450e-02],
       [ 6.85954775e-02],
       [-3.54814942e-02],
       [ 2.07604280e-01],
       [ 4.33035613e-01],
       [ 3.22922082e-01],
       [ 2.38729639e-01],
       [ 4.02759707e-01],
       [ 5.17634831e-02],
       [ 3.00011034e-02],
       [ 8.50932268e-03],
       [ 2.55682715e-02],
       [ 1.38988041e+00],
       [ 7.05244684e-01],
       [ 4.53196629e-01],
       [-6.51656161e-02],
       [ 1.02585125e+00],
       [ 3.90191057e-01],
       [ 4.97230112e-01],
       [-1.09052209e-01],
       [ 2.02409377e-01],
       [ 9.57082107e-01],
       [ 2.13676066e-01],
       [ 4.67979550e-01],
       [ 2.32894378e-01],
       [ 1.00436981e+00],
       [ 1.17513322e+00],
       [ 1.27578131e+00],
       [ 3.23193985e-01],
       [ 1.38812193e+00],
       [ 1.37525283e-02],
       [ 3.21075488e-01],
       [ 9.23968968e-01],
       [ 7.90906301e-01],
       [ 3.32829829e-01],
       [ 7.35942232e-01],
       [ 2.03929982e-01],
       [ 2.34150899e+00],
       [ 6.85168003e-01],
       [ 3.13913457e-01],
       [ 6.63286219e-01],
       [ 2.80948032e-01],
       [ 7.13222154e-01],
       [ 6.87434576e-02],
       [ 5.41658824e-01],
       [-1.49061161e-01],
       [-5.28133512e-02],
       [ 1.28974202e-01],
       [ 8.55885732e-01],
       [-6.01869533e-02],
       [ 4.06763934e-01],
       [ 4.47550722e-01],
       [ 2.04193776e-01],
       [ 3.48504417e-01],
       [ 4.98347907e-01],
       [ 8.36843461e-01],
       [ 1.28692157e-01],
       [ 1.53578078e-01],
       [ 7.09845844e-01],
       [-4.41365820e-02],
       [ 7.34090185e-01],
       [ 1.33899904e+00],
       [ 4.23108333e-01],
       [ 7.59590250e-01],
       [ 6.74643983e-01],
       [ 6.95982197e-02],
       [-1.03366647e-01],
       [ 9.11807207e-02],
       [-8.15621575e-02],
       [ 3.63375169e-01],
       [-3.47251284e-02],
       [ 3.79390352e-04],
       [ 3.31398262e-01],
       [ 5.24333551e-01],
       [ 6.31098775e-01],
       [ 9.57054871e-01],
       [ 2.88078576e-01],
       [-1.37654380e-01],
       [-3.73908216e-02],
       [ 3.49559820e-01],
       [ 1.44043534e-01],
       [ 1.76012268e+00],
       [ 1.20389747e+00],
       [ 2.77942632e-01],
       [ 4.21659191e-01],
       [ 4.59353747e-01],
       [ 1.95787168e-02],
       [ 3.53328530e-04],
       [ 2.43024667e-01],
       [ 8.36524370e-01],
       [ 1.45028967e+00],
       [ 4.22239058e-01],
       [ 4.31974727e-01],
       [ 1.56998879e-01],
       [ 1.24301260e-01],
       [ 1.45426862e-01],
       [ 1.66368407e-01],
       [ 3.01888379e-01],
       [ 2.30652324e+00],
       [-1.84140849e-02],
       [ 5.05692328e-01],
       [ 3.04020106e-02],
       [ 6.42924708e-02],
       [ 2.14387179e-01],
       [ 1.68551115e-01],
       [ 2.32066672e-01],
       [ 1.04795948e-01],
       [ 7.59570673e-01],
       [ 4.07199679e-02],
       [ 7.33972096e-01],
       [-1.38823917e-01],
       [ 2.65626768e-01],
       [ 2.69175910e-01],
       [ 1.00126879e+00],
       [ 5.66089021e-02],
       [ 2.78627652e-02],
       [ 1.56253328e-01],
       [ 2.11902731e+00],
       [ 3.53954487e-02],
       [ 8.49300198e-01],
       [ 1.66303372e-01],
       [ 9.64744068e-02],
       [ 6.11922938e-01],
       [-8.19659787e-02],
       [-9.90699845e-02],
       [ 2.07257972e-01],
       [ 2.58145521e-01],
       [-5.97842160e-02],
       [ 5.56081989e-02],
       [ 1.79701011e-01],
       [ 1.49083110e+00],
       [ 5.46692059e-02],
       [ 6.82518575e-01],
       [ 2.88918291e-02],
       [-6.92311578e-02],
       [ 2.98156897e-01],
       [ 1.22631032e+00],
       [ 1.01358905e+00],
       [ 8.97801677e-01],
       [ 1.54168931e+00],
       [ 1.24487384e+00],
       [ 4.66439020e-01],
       [ 3.91022179e-01],
       [ 1.52066131e-01],
       [ 3.93522802e-01],
       [ 4.13229169e-02],
       [ 6.14025530e-01],
       [ 3.22054283e-01],
       [-8.22116391e-02],
       [-9.03700543e-02],
       [ 6.89125415e-01],
       [ 3.91952551e-03],
       [ 1.64007406e-01],
       [ 1.10315582e+00],
       [ 4.14046216e-01],
       [ 1.82259732e-01],
       [ 1.26030562e-01],
       [ 1.00725442e-01],
       [ 2.73925565e-01],
       [ 8.15243179e-01],
       [-7.84772847e-02],
       [ 4.19390919e-01],
       [ 6.38923993e-01],
       [ 5.96573552e-01],
       [ 9.08859788e-01],
       [ 3.53872154e-01],
       [ 2.95070424e+00],
       [ 1.72872951e+00],
       [-4.51223536e-02],
       [-7.02517333e-02],
       [ 8.59940107e-02],
       [ 1.49580111e+00],
       [ 9.10383744e-01],
       [ 2.46852472e-01],
       [ 2.87302658e-01],
       [ 5.50947350e-02],
       [ 3.12673372e-01],
       [ 4.08568456e-01],
       [ 1.23454109e+00],
       [ 2.56826164e-01],
       [ 1.21299903e+00],
       [ 1.03339262e-01],
       [ 7.99821138e-02],
       [-2.74188605e-02],
       [ 1.86205065e-01],
       [ 5.31928261e-02],
       [ 4.65046748e-02],
       [ 1.62556690e+00],
       [ 5.86412335e-01],
       [ 1.92176981e+00],
       [ 1.02390740e+00],
       [ 1.26418821e-02],
       [ 1.46772188e-01],
       [ 1.29368980e-01],
       [ 9.13605754e-01],
       [ 5.44625356e-01],
       [ 2.17922132e-01],
       [ 1.85312868e-01],
       [ 9.02479734e-01],
       [ 1.87874074e+00],
       [ 1.51291892e-01],
       [ 1.53159705e+00],
       [ 8.61247950e-01],
       [-5.82491664e-02],
       [ 8.38574018e-02],
       [ 3.22574028e-01],
       [ 6.97353544e-01],
       [ 1.97503637e-01],
       [ 5.33846735e-01],
       [ 1.36766230e+00],
       [ 3.97940208e-01],
       [ 3.66828765e-01],
       [ 4.15394873e-01],
       [ 1.19556954e-01],
       [ 1.17917884e-01],
       [ 1.82807829e-01],
       [ 2.99426278e-01],
       [ 8.35089872e-01],
       [-5.08678050e-02],
       [-5.28853596e-02],
       [ 1.52518227e+00],
       [ 4.93084376e-01],
       [ 5.48309501e-02],
       [ 5.05920942e-03],
       [ 3.27456433e-01],
       [ 1.54821268e+00],
       [ 4.19047731e-01],
       [ 4.00103034e-01],
       [ 3.07423303e-01],
       [-1.55864609e-01],
       [-5.23173486e-02],
       [ 3.22751857e-01],
       [ 1.10934511e+00],
       [ 2.35151461e-02],
       [ 5.03109221e-01],
       [ 4.59637247e-02],
       [ 1.18698246e+00],
       [ 2.10119791e-01],
       [ 1.06573162e+00],
       [-3.09405975e-02],
       [ 3.53833234e-01],
       [ 3.42541053e-01],
       [ 1.07458097e+00],
       [ 3.50518823e-01],
       [ 3.74912742e-01],
       [ 1.01421324e-02],
       [ 8.08138817e-02],
       [ 5.45872104e-02],
       [ 2.15640077e-02],
       [ 3.33335622e-01],
       [ 1.68800786e-01],
       [ 2.65185332e-01],
       [ 1.91578614e-01],
       [ 2.22297842e-01],
       [ 4.06910978e-01],
       [ 6.43268779e-01],
       [ 1.44535934e+00],
       [ 3.90795215e-01],
       [ 4.34316542e-01],
       [ 9.30933922e-03],
       [ 1.42180987e+00],
       [ 1.01523290e+00],
       [ 3.77296460e-01],
       [ 6.26717681e-01],
       [ 5.49311899e-01],
       [-5.27271004e-02],
       [ 5.30033337e-01],
       [-8.56160123e-02],
       [ 3.40838477e-01],
       [ 5.82697628e-02],
       [ 6.45257803e-01],
       [ 2.07115556e-02],
       [ 4.47212767e-01],
       [ 3.91359766e-01],
       [ 1.16203765e-01],
       [ 3.68470356e-02],
       [ 1.57837225e+00],
       [ 5.57257771e-03],
       [ 1.13864726e+00],
       [ 4.94935302e-01],
       [ 1.54693607e-01],
       [ 6.35529229e-01],
       [ 5.58870618e-02],
       [ 3.00838229e-01],
       [ 1.82549740e-01],
       [ 2.25517522e-03],
       [ 1.53732621e+00],
       [-5.49702551e-03],
       [ 1.65819219e-01],
       [-8.73539577e-02],
       [ 2.03083962e-01],
       [ 9.14404531e-01],
       [ 4.05512976e-02],
       [ 2.35366669e-01],
       [ 7.16973844e-01],
       [ 9.97720924e-01],
       [ 7.05902611e-01],
       [ 8.16723947e-01],
       [ 1.33999274e+00],
       [ 5.55230165e-01],
       [-4.98244617e-02],
       [ 1.07917060e+00],
       [ 2.70009733e-03],
       [-7.13330679e-02],
       [ 1.74536512e-01],
       [ 4.66643283e-01],
       [ 4.98129588e-01],
       [ 2.94406968e-01],
       [ 8.21201434e-01],
       [ 3.33652938e-01],
       [ 1.39165739e+00],
       [ 1.00624848e-01],
       [ 7.58281226e-02],
       [-8.92220026e-03],
       [ 7.22389577e-01],
       [ 3.38885755e-01],
       [-3.50472020e-02],
       [ 6.55100745e-01],
       [ 9.18363437e-01],
       [ 1.00953616e+00],
       [-1.31567391e-02],
       [ 5.48342300e-01],
       [ 5.69270119e-01],
       [ 1.17122855e-01],
       [ 1.28619992e-01],
       [ 4.24063743e-01],
       [ 1.70270761e-01],
       [-6.22365852e-02],
       [ 7.54592650e-01],
       [-6.46025985e-02],
       [ 8.59912426e-01],
       [-1.04804588e-01],
       [ 3.49180850e-02],
       [ 1.69060558e+00],
       [ 3.34516884e-01],
       [ 3.15566987e-01],
       [ 5.64067575e-01],
       [ 2.97062595e-01],
       [ 6.03318791e-01],
       [ 2.73790528e-01],
       [-1.38897187e-01],
       [ 2.27148978e-01],
       [ 5.67497759e-01],
       [ 1.50612553e-01],
       [ 5.12029506e-02],
       [ 1.26030742e+00],
       [ 4.89435884e-01],
       [ 1.09290346e+00],
       [ 8.57195759e-01],
       [-7.00814989e-02],
       [ 7.02243256e-01],
       [ 3.11927545e-01],
       [ 5.88451058e-01],
       [ 4.84374144e-02],
       [ 2.43569378e+00],
       [ 1.64470134e-01],
       [ 3.58476211e-01],
       [-5.24960844e-02],
       [ 5.25693174e-01],
       [ 9.48823184e-01],
       [ 1.34336217e+00],
       [ 3.28959311e-01],
       [ 3.84034599e-01],
       [ 1.08739931e-01],
       [ 4.10251473e-02],
       [ 7.93201621e-01],
       [ 9.93581412e-01],
       [ 8.09720484e-01],
       [ 8.63476354e-02],
       [ 5.50091073e-02],
       [-2.65589562e-02],
       [ 4.45068694e-01],
       [ 4.47005940e-02],
       [ 3.08346268e-01],
       [ 1.29701956e-01],
       [ 1.21382360e+00],
       [ 5.80470685e-01],
       [ 1.66615856e+00],
       [ 2.77425782e-01],
       [ 4.94249391e-01],
       [ 2.74693172e-01],
       [ 4.97029180e-02],
       [ 6.63675143e-02],
       [ 3.54680338e-01],
       [ 1.49381414e-01],
       [ 1.80100720e-01],
       [ 2.34745252e-01],
       [ 4.48347322e-01],
       [ 1.61662256e-01],
       [ 6.76780451e-01],
       [ 9.05537850e-01],
       [ 1.14616271e+00],
       [ 1.82734349e-01],
       [ 1.45493499e-01],
       [-1.13593544e-01],
       [-2.94057019e-02],
       [ 7.58481080e-01],
       [ 2.08031303e-01],
       [ 2.75027397e-01],
       [ 2.07561634e-02],
       [ 1.35511408e+00],
       [ 5.23510654e-01],
       [ 1.30034529e-01],
       [ 7.82048627e-02],
       [ 6.82908784e-01],
       [ 1.15542568e-02],
       [ 1.52443286e+00],
       [ 4.34987096e-01],
       [-6.30772949e-02],
       [ 5.61162656e-01],
       [-1.36312017e-02],
       [ 4.56257150e-01],
       [ 2.64184591e-01],
       [ 1.97703466e-01],
       [ 1.35113198e+00],
       [ 7.83190539e-02],
       [ 2.44252682e-01],
       [ 2.64184695e-01],
       [ 6.75185119e-01],
       [-5.64045696e-02],
       [ 6.48622294e-01],
       [ 6.31498114e-02],
       [ 5.11460379e-01],
       [ 5.66943051e-01],
       [ 2.52809512e-01],
       [ 2.26015443e-01],
       [-1.47918560e-01],
       [ 2.52791793e-01],
       [ 5.05779344e-01],
       [ 4.71074781e-02],
       [ 1.18704494e+00],
       [ 3.16566686e-01],
       [ 2.30640653e+00],
       [ 3.17741571e-01],
       [ 3.74346137e-02],
       [ 3.64680298e-01],
       [ 4.44756446e-01],
       [ 1.44594141e-01],
       [-2.11394276e-02],
       [ 3.77393713e-01],
       [-5.33313221e-02],
       [ 3.50582403e-01],
       [-7.85644400e-02],
       [-6.13052176e-02],
       [ 3.98351004e-01],
       [ 5.13984392e-01],
       [ 2.16425918e-01],
       [ 2.73423024e-01],
       [-1.03616111e-01],
       [ 2.89677873e-01],
       [ 2.10549290e-01],
       [ 7.10652217e-01],
       [ 7.59506763e-01],
       [ 1.58791194e+00],
       [ 1.84501283e-01],
       [ 4.57892621e-02],
       [ 1.86832372e+00],
       [ 9.79007740e-02],
       [ 1.93347602e-01],
       [ 4.54524139e-01],
       [ 1.78835878e-01],
       [ 5.49874587e-01],
       [-9.86727530e-02],
       [ 1.55260952e-01],
       [ 6.14492545e-01],
       [ 2.12520863e-01],
       [ 4.77351207e-02],
       [ 8.74744617e-02],
       [ 1.51335314e-01],
       [ 1.82197907e+00],
       [ 2.12694640e-01],
       [ 1.41685961e+00],
       [ 2.26471737e-01],
       [ 1.25501274e+00],
       [ 2.08566993e-01],
       [ 6.28639714e-01],
       [ 8.65478203e-01],
       [ 1.06567001e-01],
       [-5.78408058e-04],
       [ 4.96782661e-02],
       [-1.29829800e-02],
       [ 9.41918720e-01],
       [-6.48499345e-02],
       [ 2.98147074e-01],
       [ 2.48148263e-01],
       [ 1.61995389e-01],
       [ 2.22879199e-01],
       [ 8.82366039e-01],
       [ 1.12116892e-01],
       [ 1.02683414e+00],
       [ 2.22055681e-01],
       [ 2.61094858e-01],
       [ 8.64484516e-02],
       [ 1.41017869e+00],
       [ 3.24766078e-01],
       [-1.08122978e-01],
       [ 5.37671306e-02],
       [ 3.08002271e-01],
       [-1.06736014e-01],
       [ 1.29276345e+00],
       [ 2.32019303e-01],
       [ 2.72693247e-01],
       [ 5.86983606e-01],
       [ 7.88287467e-01],
       [ 3.03477524e-01],
       [ 4.03727733e-01],
       [-4.98096068e-02],
       [-1.58905276e-02],
       [ 5.08456098e-01],
       [ 4.00558249e-01],
       [ 1.40330971e-01],
       [ 1.51675497e-01],
       [ 1.02383293e-01],
       [ 5.77179317e-02],
       [ 5.71441553e-02],
       [ 3.40869450e-02],
       [-1.17383628e-01],
       [ 2.22527985e-01],
       [ 3.22061487e-01],
       [-1.29220540e-01],
       [-3.24199698e-03],
       [-4.44407632e-02],
       [ 1.07500185e-01],
       [ 2.66196302e-01],
       [ 8.91514220e-03],
       [ 1.04916388e+00],
       [ 6.88919928e-02],
       [ 1.58562362e-01],
       [ 6.64976812e-02],
       [ 8.27146552e-02],
       [ 3.53817125e-01],
       [ 2.85551891e-01],
       [ 1.57772273e-02],
       [-5.72324871e-02],
       [ 8.28853993e-02],
       [ 3.05031818e-01],
       [ 2.56549704e-01],
       [-5.72595362e-02],
       [ 1.50423562e-01],
       [ 1.77828484e-01],
       [ 7.09361935e-02],
       [-7.75089178e-02],
       [ 1.24752523e-01],
       [ 5.72888674e-01],
       [ 2.36095761e-01],
       [ 4.39338280e-01],
       [-4.19789817e-02],
       [-4.74693416e-02],
       [ 1.84696512e-01],
       [ 1.80143705e-01],
       [ 2.71621236e-01],
       [ 3.09899170e-01],
       [ 9.85720896e-03],
       [ 2.64562616e-01],
       [ 9.35853066e-02],
       [ 6.55811872e-02],
       [ 3.21801524e-01],
       [-9.72398323e-02],
       [ 1.92036587e-01],
       [ 3.15120367e-01],
       [ 4.90866102e-02],
       [ 1.52260025e-01],
       [ 6.82855304e-01],
       [ 1.81200505e-01],
       [ 2.86326425e-01],
       [ 4.07060493e-02],
       [ 1.44101157e-01],
       [ 3.22098258e-01],
       [ 4.79163932e-02],
       [ 5.11727411e-01],
       [ 1.79132649e-01],
       [ 1.22570147e-01],
       [ 1.70850424e-02],
       [ 2.69580425e-01],
       [ 6.14592915e-01],
       [-4.84616100e-02],
       [ 6.54773044e-01],
       [-1.42620492e-01],
       [-8.23808625e-02],
       [ 3.79892213e-02],
       [ 2.43150931e-01],
       [-4.62715418e-02],
       [ 3.02912910e-02],
       [ 1.09179080e-01],

In [339]:
# y

In [340]:
mae = mean_absolute_error(y_test["ltv_30d"],y_pred)
rmse = np.sqrt(mean_squared_error(y_test["ltv_30d"],y_pred))
r2 = r2_score(y_test["ltv_30d"],y_pred)
print('mae',mae)
print('rmse',rmse)
print('r2',r2)

mae 0.45041057135771345
rmse 0.70885193134148
r2 0.2825797489697752

In [341]:
print('mae_base',mae_base)
print('rmse_bae',rmse_bae)
print('r2_base',r2_base)

mae_base 0.5457414690186173
rmse_bae 1.1345008881805416
r2_base -0.8376900254053457

In [343]:
float((mae-mae_base)/mae_base*100)

-17.468142531358886

In [344]:
float((rmse-rmse_bae)/rmse*100)

-60.04765424473549

In [348]:
y_test['country'] = X_test['MAX(country)']

In [351]:
y_test['pred'] = y_pred

In [352]:
y_test.head()

       ltv_30d country      pred
4117  0.000000      CA  0.395397
4118  0.000000      US -0.091360
4119  1.905651      IN  0.507640
4120  0.000000      IN  1.502400
4121  0.000000      CA -0.085613

In [353]:
cohort_metrics = y_test.groupby(['country']).apply(lambda x: pd.Series({'mae':mean_absolute_error(x["ltv_30d"],x['pred']),
'rmse':np.sqrt(mean_squared_error(x["ltv_30d"],x['pred'])), 
'r2':r2_score(x["ltv_30d"],x['pred'])}))

/var/folders/qh/wcp4hdh55d56zf2h540jdxlr0000gn/T/ipykernel_62040/337856722.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  cohort_metrics = y_test.groupby(['country']).apply(lambda x: pd.Series({'mae':mean_absolute_error(x["ltv_30d"],x['pred']),

In [355]:
cohort_metrics

              mae      rmse        r2
country
CA       0.390574  0.605143  0.297752
IN       0.486971  0.776313  0.236403
UK       0.449061  0.716509  0.308765
US       0.465766  0.712831  0.282289

In [ ]:
 feature engineering and scale and productionization. ?????????

## Practice 3

In [356]:
df

,user_id,date,sessions,play_time,spend,creator_id,platform,country
0,0,2025-01-07,1,11.888733,0.000000,373,ios,US
1,0,2025-01-08,1,19.548648,0.000000,492,ios,US
2,0,2025-01-10,3,16.037809,0.000000,475,ios,US
3,0,2025-01-13,1,16.777639,0.000000,563,ios,US
4,0,2025-01-14,3,35.272466,0.000000,274,ios,US
...,...,...,...,...,...,...,...,...
70553,4999,2025-01-26,3,32.599466,0.000000,688,web,IN
70554,4999,2025-01-27,2,16.721781,0.000000,450,web,IN
70555,4999,2025-01-28,2,18.727887,8.605824,83,web,IN
70556,4999,2025-01-29,2,18.667530,0.000000,767,web,IN
70557,4999,2025-01-30,3,57.009896,2.185158,560,web,IN

In [ ]:
# train -> day 0-6; test -> day 7-29
# features:
    # 1. 7d total spend, (mention spend velocity(last 3d spend/(first 4d spend + 1)))
    # 2. number of total sessions, total play time
    # 3. d1 retention, active_days_7d
    # 4. platform, country
    # 5. # of unique creators

In [ ]:
with first_date as
(select
    *,
    MIN(date) over(partition by user_id) as first_date
from df_table),
day_diff as
(select
    *,
    DATEDIFF('day', first_date, date) as day_diff
from first_date
)
select
    user_id,
    first_date,
    SUM(CASE WHEN day_diff BETWEEN 0 AND 6 THEN spend ELSE 0 END) as total_spend_7d,
    SUM(CASE WHEN day_diff BETWEEN 0 AND 6 THEN sessions ELSE 0 END) as total_sessions_7d,
    SUM(CASE WHEN day_diff BETWEEN 0 AND 6 THEN play_time ELSE 0 END) as total_playtime_7d,
    MAX(CASE WHEN day_diff = 1 THEN 1 ELSE 0 END) as d1_retention_flag,
    COUNT(DISTINCT CASE WHEN day_diff BETWEEN 0 AND 6 THEN date END) as active_days_7d,
    MAX(platform) as platform,
    MAX(country) as country,
    COUNT(DISTINCT CASE WHEN day_diff BETWEEN 0 AND 6 THEN creator_id END) as nunique_creators,
    SUM(CASE WHEN day_diff BETWEEN 7 AND 29 THEN spend ELSE 0 END) as ltv_30d
from day_diff
group by user_id

# END
# name cannotstart with number
# day 7 retention need to be caucious, use active 7 days
# joining day you need to include that!

In [357]:
processed_df = pd.read_csv("/Users/zhuangdiezhou/Documents/Documents - Zhuangdie Alan Zhou's MacBook Pro - 1/Hi_Sexy/Interview/Roblox/user_activity_after_sql_final.csv")

In [359]:
processed_df.head()

,user_id,joining_date,total_spend_7d,total_sessions_7d,total_playtime_7d,d1_retention_flag,active_days_7d,platform,country,nunique_creators,ltv_30d
0,0,2025-01-07,0.0,6,64.252830,1,4,ios,US,4,0.0
1,1,2025-01-26,0.0,2,14.305001,0,2,ios,US,2,0.0
2,2,2025-01-02,0.0,7,102.255638,0,3,ios,UK,3,0.0
3,3,2025-01-19,0.0,3,31.861878,0,3,android,IN,3,0.0
4,4,2025-02-05,0.0,4,32.449207,1,3,android,CA,3,0.0

In [360]:
processed_df.describe(include = 'all')

,user_id,joining_date,total_spend_7d,total_sessions_7d,total_playtime_7d,d1_retention_flag,active_days_7d,platform,country,nunique_creators,ltv_30d
count,4978.000000,4978,4978.000000,4978.000000,4978.000000,4978.000000,4978.000000,4978,4978,4978.000000,4978.000000
unique,NaN,45,NaN,NaN,NaN,NaN,NaN,3,4,NaN,NaN
top,NaN,2025-01-29,NaN,NaN,NaN,NaN,NaN,web,US,NaN,NaN
freq,NaN,198,NaN,NaN,NaN,NaN,NaN,1716,1277,NaN,NaN
mean,2500.483126,NaN,0.945910,9.167738,114.566627,0.588188,4.361189,NaN,NaN,4.349538,1.915623
std,1443.721875,NaN,3.171391,8.237568,105.341417,0.492211,1.846891,NaN,NaN,1.840310,5.114650
min,0.000000,NaN,0.000000,1.000000,5.073930,0.000000,1.000000,NaN,NaN,1.000000,0.000000
25%,1251.250000,NaN,0.000000,3.000000,42.178059,0.000000,3.000000,NaN,NaN,3.000000,0.000000
50%,2499.500000,NaN,0.000000,6.000000,77.171421,1.000000,4.000000,NaN,NaN,4.000000,0.000000
75%,3751.750000,NaN,0.000000,12.000000,152.329670,1.000000,6.000000,NaN,NaN,6.000000,0.000000
max,4999.000000,NaN,44.112869,55.000000,798.519567,1.000000,7.000000,NaN,NaN,7.000000,55.597312

In [362]:
num_cols = processed_df.select_dtypes(include = 'number').columns
processed_df[num_cols].skew()

user_id             -0.000363
total_spend_7d       5.064800
total_sessions_7d    1.721187
total_playtime_7d    1.819218
d1_retention_flag   -0.358478
active_days_7d      -0.080272
nunique_creators    -0.078620
ltv_30d              3.955807
dtype: float64

In [363]:
processed_df['ltv_30d_log'] = np.log1p(processed_df['ltv_30d'])

In [ ]:
# split train and test, using joining date

In [365]:
processed_df = processed_df.sort_values(by = 'joining_date').reset_index(drop = True)
processed_df.head()

,user_id,joining_date,total_spend_7d,total_sessions_7d,total_playtime_7d,d1_retention_flag,active_days_7d,platform,country,nunique_creators,ltv_30d,ltv_30d_log
0,2499,2025-01-01,0.0,7,80.359712,1,5,web,UK,5,0.000000,0.000000
1,2127,2025-01-01,0.0,8,90.376932,1,6,ios,UK,6,3.909909,1.591255
2,2084,2025-01-01,0.0,11,138.710523,1,5,web,IN,5,0.510291,0.412302
3,267,2025-01-01,0.0,5,50.855062,1,4,android,US,4,0.000000,0.000000
4,694,2025-01-01,0.0,39,608.039224,1,7,android,US,7,7.960739,2.192853

In [366]:
idx = int(processed_df.shape[0]*0.8)
idx

3982

In [367]:
idx_date = processed_df.loc[3982]['joining_date']
idx_date

'2025-01-26'

In [368]:
processed_df.columns

Index(['user_id', 'joining_date', 'total_spend_7d', 'total_sessions_7d',
       'total_playtime_7d', 'd1_retention_flag', 'active_days_7d', 'platform',
       'country', 'nunique_creators', 'ltv_30d', 'ltv_30d_log'],
      dtype='object')

In [373]:
features = ['joining_date', 'total_spend_7d', 'total_sessions_7d',
       'total_playtime_7d', 'd1_retention_flag', 'active_days_7d', 'platform',
       'country', 'nunique_creators']
target = ['ltv_30d_log']

In [374]:
processed_df[processed_df['joining_date']<=idx_date].shape[0]/processed_df.shape[0]

0.8270389714744878

In [376]:
X_train = processed_df[processed_df['joining_date']<= idx_date][features]
y_train = processed_df[processed_df['joining_date']<= idx_date][target]

X_test = processed_df[processed_df['joining_date']> idx_date][features]
y_test = processed_df[processed_df['joining_date']> idx_date][target]

In [377]:
X_train.head()

,joining_date,total_spend_7d,total_sessions_7d,total_playtime_7d,d1_retention_flag,active_days_7d,platform,country,nunique_creators
0,2025-01-01,0.0,7,80.359712,1,5,web,UK,5
1,2025-01-01,0.0,8,90.376932,1,6,ios,UK,6
2,2025-01-01,0.0,11,138.710523,1,5,web,IN,5
3,2025-01-01,0.0,5,50.855062,1,4,android,US,4
4,2025-01-01,0.0,39,608.039224,1,7,android,US,7

In [378]:
y_train.head()

   ltv_30d_log
0     0.000000
1     1.591255
2     0.412302
3     0.000000
4     2.192853

In [ ]:
# baseline model

In [382]:
y_pred_base = X_test['total_spend_7d']/7 * (30-7)
y_pred_base

4117    0.000000
4118    0.000000
4119    0.674637
4120    0.000000
4121    0.000000
          ...
4973    0.000000
4974    0.000000
4975    0.000000
4976    0.000000
4977    0.000000
Name: total_spend_7d, Length: 861, dtype: float64

In [383]:
y_pred_base_log = np.log1p(y_pred_base)
y_pred_base_log

4117    0.000000
4118    0.000000
4119    0.515597
4120    0.000000
4121    0.000000
          ...
4973    0.000000
4974    0.000000
4975    0.000000
4976    0.000000
4977    0.000000
Name: total_spend_7d, Length: 861, dtype: float64

In [384]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [419]:
mae_base = mean_absolute_error(y_test['ltv_30d_log'],y_pred_base_log)
rmse_base = np.sqrt(mean_squared_error(y_test['ltv_30d_log'],y_pred_base_log))
r2_base = r2_score(y_test['ltv_30d_log'],y_pred_base_log)

In [420]:
print('mae_base',mae_base)
print('rmse_base',rmse_base)
print('r2_base',r2_base)

mae_base 0.5457414690186172
rmse_base 1.1345008881805416
r2_base -0.8376900254053452

In [387]:
# regression - stronger model

In [388]:
X_train.head()

,joining_date,total_spend_7d,total_sessions_7d,total_playtime_7d,d1_retention_flag,active_days_7d,platform,country,nunique_creators
0,2025-01-01,0.0,7,80.359712,1,5,web,UK,5
1,2025-01-01,0.0,8,90.376932,1,6,ios,UK,6
2,2025-01-01,0.0,11,138.710523,1,5,web,IN,5
3,2025-01-01,0.0,5,50.855062,1,4,android,US,4
4,2025-01-01,0.0,39,608.039224,1,7,android,US,7

In [393]:
X_train[['platform','country']].nunique()

platform    3
country     4
dtype: int64

In [394]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [397]:
num_pipeline = Pipeline([
    ('norm', StandardScaler())
])

In [398]:
cat_pipeline = Pipeline([
    ('onehot', OneHotEncoder(handle_unknown = 'ignore', sparse_output = False))
])

In [399]:
X_train.columns

Index(['joining_date', 'total_spend_7d', 'total_sessions_7d',
       'total_playtime_7d', 'd1_retention_flag', 'active_days_7d', 'platform',
       'country', 'nunique_creators'],
      dtype='object')

In [400]:
preprocessor = ColumnTransformer([
    ('num',num_pipeline,['total_spend_7d', 'total_sessions_7d',
       'total_playtime_7d','active_days_7d','nunique_creators']),
    ('cat', cat_pipeline, ['d1_retention_flag', 'platform', 'country'])
])

In [401]:
preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('norm', StandardScaler())]),
                                 ['total_spend_7d', 'total_sessions_7d',
                                  'total_playtime_7d', 'active_days_7d',
                                  'nunique_creators']),
                                ('cat',
                                 Pipeline(steps=[('onehot',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['d1_retention_flag', 'platform', 'country'])])

In [402]:
from sklearn.linear_model import LinearRegression

In [403]:
model = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [404]:
model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('norm',
                                                                   StandardScaler())]),
                                                  ['total_spend_7d',
                                                   'total_sessions_7d',
                                                   'total_playtime_7d',
                                                   'active_days_7d',
                                                   'nunique_creators']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['d1_retention_flag',
                                                   'platform', 'country'])])),
                ('regressor', LinearRegression())])

In [407]:
X_train.drop(columns = 'joining_date', inplace = True)

In [409]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('norm',
                                                                   StandardScaler())]),
                                                  ['total_spend_7d',
                                                   'total_sessions_7d',
                                                   'total_playtime_7d',
                                                   'active_days_7d',
                                                   'nunique_creators']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['d1_retention_flag',
                                                   'platform', 'country'])])),
                ('regressor', LinearRegression())])

In [410]:
X_test.drop(columns = 'joining_date', inplace = True)

In [412]:
y_pred = model.predict(X_test)
y_pred

array([[ 1.11630885e-01],
       [ 7.00009532e-02],
       [ 1.15227314e+00],
       [ 9.56338599e-02],
       [ 7.67343403e-01],
       [ 9.75171919e-02],
       [ 5.26716537e-01],
       [ 3.47962105e-01],
       [ 3.03295561e-02],
       [ 8.45687840e-01],
       [ 3.54973396e-02],
       [ 1.82982859e-01],
       [ 3.42249193e-01],
       [ 3.07071849e-01],
       [ 1.33516958e-01],
       [ 1.91148218e-01],
       [ 2.13866116e+00],
       [-2.76057681e-02],
       [ 9.96906145e-02],
       [ 9.65024705e-01],
       [ 6.98058960e-02],
       [ 2.09798165e-01],
       [ 5.62435450e-01],
       [ 8.47812959e-02],
       [ 2.22701275e-01],
       [ 1.15870970e+00],
       [ 7.05040225e-02],
       [ 1.33685200e-01],
       [ 3.26257824e-02],
       [ 9.19201813e-01],
       [ 3.97547541e-01],
       [ 1.78226446e+00],
       [ 1.18207933e-01],
       [ 1.46165445e-01],
       [ 4.13424379e-01],
       [ 1.84320804e-01],
       [ 2.50362114e-01],
       [ 7.69574392e-01],
       [ 4.29640422e-01],
       [ 1.80019935e+00],
       [ 1.98366819e-01],
       [ 3.63330808e-01],
       [ 1.33301990e+00],
       [ 2.81733372e-02],
       [ 1.30006550e-01],
       [ 1.10572225e+00],
       [ 8.20480740e-01],
       [ 3.79659767e-01],
       [ 1.14460352e+00],
       [ 6.46700242e-03],
       [ 6.40144538e-02],
       [ 5.00304656e-01],
       [ 1.18825830e+00],
       [ 2.54016454e-01],
       [ 7.68333220e-01],
       [ 1.58251319e-01],
       [ 1.55415036e-01],
       [ 5.87234831e-02],
       [ 1.33543782e-01],
       [ 3.66207269e-01],
       [ 1.33721153e-01],
       [ 5.05856692e-01],
       [ 4.34000617e-01],
       [ 2.70474509e-01],
       [ 2.75063216e-01],
       [ 1.11663271e+00],
       [ 7.51592231e-01],
       [ 2.39054647e-01],
       [ 1.07224168e+00],
       [ 1.91997565e-01],
       [ 2.92669960e-01],
       [ 3.55872710e-01],
       [ 3.75191536e-01],
       [ 2.25823451e-01],
       [ 3.70257603e-01],
       [ 6.09445485e-04],
       [ 4.46970939e-01],
       [ 1.74741288e-01],
       [ 4.81805251e-02],
       [ 9.12761400e-02],
       [ 8.63106056e-01],
       [ 1.15631351e+00],
       [ 4.64197122e-01],
       [ 3.85783126e-01],
       [ 4.95358019e-01],
       [ 4.62932632e-01],
       [ 9.13144928e-01],
       [ 7.51370810e-01],
       [ 1.61594746e-01],
       [ 5.40686506e-01],
       [ 1.48611415e+00],
       [ 3.37605570e-01],
       [ 2.00171322e+00],
       [ 1.81877632e-01],
       [ 1.34524583e-01],
       [ 1.70632955e+00],
       [ 6.29182698e-02],
       [ 4.82563706e-01],
       [ 1.75916309e-01],
       [ 7.17124944e-01],
       [ 2.41590645e-01],
       [ 2.14532627e-01],
       [ 4.80262094e-01],
       [ 6.47190403e-01],
       [ 1.40691275e-01],
       [ 2.24441384e-01],
       [ 7.16845206e-01],
       [ 2.91206203e-01],
       [ 6.38571870e-04],
       [-3.03585598e-04],
       [ 5.42793051e-01],
       [ 5.96486940e-03],
       [ 6.84300062e-01],
       [ 3.52798695e-01],
       [ 3.16848663e-01],
       [ 1.12507265e+00],
       [ 8.81516343e-01],
       [ 4.00323471e-01],
       [ 2.41733998e-01],
       [ 7.49967852e-01],
       [ 1.24969004e-01],
       [ 3.44111551e-01],
       [ 1.27418923e-01],
       [ 1.50547368e-01],
       [ 2.07630024e-01],
       [ 9.72799097e-02],
       [ 7.67162854e-01],
       [ 8.13020656e-01],
       [ 1.61364873e-01],
       [ 2.86904438e-01],
       [ 8.16436700e-01],
       [ 6.27274420e-02],
       [ 1.81059852e+00],
       [ 2.57542844e-01],
       [ 3.17204528e-01],
       [ 2.99484966e-01],
       [ 9.09050882e-01],
       [ 3.18416771e-01],
       [ 4.03060152e-01],
       [ 1.66301641e-01],
       [ 8.70884495e-01],
       [ 5.05232457e-01],
       [ 8.34314773e-01],
       [ 1.93065922e+00],
       [ 1.76948627e-01],
       [ 1.02383239e+00],
       [ 3.50171813e-01],
       [ 1.61374214e-01],
       [ 8.97846612e-01],
       [ 3.34336140e-01],
       [ 1.22642906e+00],
       [ 2.39702213e-01],
       [ 3.87207226e-01],
       [ 1.60442587e-01],
       [ 9.19745961e-02],
       [ 2.76523222e-02],
       [ 1.92750418e-01],
       [ 6.96153207e-02],
       [ 9.56913503e-01],
       [ 1.78375100e+00],
       [ 1.61745752e+00],
       [ 2.39987287e-01],
       [ 1.55486620e-01],
       [-5.48775779e-03],
       [ 1.62665124e-01],
       [ 2.90078575e-01],
       [ 1.66631110e+00],
       [ 1.01232636e+00],
       [ 1.55427400e-01],
       [ 4.34603908e-01],
       [ 4.35802500e-01],
       [ 9.41153200e-02],
       [ 2.07761776e-01],
       [ 3.84691108e-01],
       [ 4.26226448e-01],
       [ 6.59064587e-01],
       [ 1.26908638e+00],
       [ 5.93728350e-01],
       [ 2.36143518e-01],
       [ 5.91446974e-03],
       [ 8.15627225e-01],
       [ 1.90400643e-01],
       [ 2.55044182e-01],
       [ 4.32887020e-01],
       [ 3.33539743e-01],
       [ 2.70616553e-01],
       [ 1.05660953e+00],
       [ 2.08473302e-01],
       [ 2.21787136e-01],
       [ 1.01588363e-01],
       [ 1.56561704e-01],
       [ 1.04543051e+00],
       [ 3.24045538e-02],
       [ 1.27521864e-01],
       [ 2.23469825e-01],
       [ 3.32660460e-01],
       [ 4.28908879e-01],
       [ 3.22229221e-01],
       [ 4.85076515e-01],
       [ 2.23737162e-01],
       [ 1.66109249e-01],
       [ 1.01019805e-01],
       [ 4.78111102e-01],
       [ 1.03233655e+00],
       [ 2.88944921e-01],
       [ 1.17093791e+00],
       [ 3.39404993e-01],
       [ 5.95880292e-01],
       [ 9.69681656e-02],
       [ 5.85830253e-02],
       [ 1.33393396e-01],
       [ 2.90704051e-01],
       [ 3.53256985e-01],
       [ 1.57125563e-01],
       [ 6.33207692e-02],
       [ 2.56182422e-01],
       [ 2.10000380e-01],
       [ 4.91374901e-01],
       [ 2.29086946e-01],
       [-3.35721685e-02],
       [ 1.42286012e-01],
       [ 1.81867030e-01],
       [ 1.93554654e-01],
       [ 3.79778104e-01],
       [ 1.88597700e+00],
       [ 3.01278953e-02],
       [ 4.83941521e-01],
       [ 3.34104641e-02],
       [ 2.88709916e-01],
       [ 6.56608097e-02],
       [ 9.63045800e-02],
       [ 3.52178331e-01],
       [ 4.29274807e-01],
       [ 6.05664569e-01],
       [ 3.27916536e-01],
       [ 8.52304683e-01],
       [ 5.47986887e-01],
       [ 4.61148527e-01],
       [ 2.56502743e-01],
       [ 8.75183272e-01],
       [ 6.39424446e-02],
       [ 3.16653964e-01],
       [ 3.96087598e-01],
       [ 2.39407251e-01],
       [ 1.34120439e-01],
       [ 9.68640468e-02],
       [ 1.55048390e-01],
       [ 3.69369058e-02],
       [ 5.67627656e-01],
       [ 4.19444976e-01],
       [ 2.84906381e-01],
       [ 3.83445428e-02],
       [ 5.11632781e-01],
       [ 3.43466620e-01],
       [ 1.29281562e-01],
       [ 3.67475285e-01],
       [ 5.08935436e-01],
       [ 5.77220427e-01],
       [ 2.58632714e-01],
       [ 2.88269203e-01],
       [ 7.88261385e-01],
       [ 1.95173442e-01],
       [ 9.35580203e-02],
       [ 3.50425104e-01],
       [ 6.66836426e-01],
       [ 1.87960324e-01],
       [ 3.23480984e-02],
       [ 1.28931493e-01],
       [ 5.32615378e-01],
       [ 2.88425503e-01],
       [ 3.32385964e-01],
       [ 9.76908539e-02],
       [ 9.77663271e-01],
       [ 5.91093271e-01],
       [ 1.60914223e-01],
       [ 1.91077963e-01],
       [ 1.66396079e-01],
       [ 6.94881747e-02],
       [ 9.73345578e-01],
       [ 1.76154525e-01],
       [ 1.46674918e+00],
       [ 1.22589735e-01],
       [ 2.14984118e+00],
       [ 2.57285066e-01],
       [ 7.24597433e-01],
       [ 3.33497807e-01],
       [ 1.45160026e+00],
       [ 5.18942604e-01],
       [ 2.19119507e-01],
       [ 1.71173333e-01],
       [ 9.61225666e-02],
       [ 3.89419395e-01],
       [ 6.37625240e-02],
       [ 3.41275338e-01],
       [ 1.18530208e+00],
       [ 2.21457015e-01],
       [ 6.76405770e-01],
       [ 3.07911490e-01],
       [ 9.68434782e-02],
       [ 1.10712657e+00],
       [ 1.39727784e-01],
       [ 3.33824846e-02],
       [ 7.89557239e-01],
       [ 2.68647804e-01],
       [ 1.38376703e-01],
       [ 2.85857317e-01],
       [ 3.21347597e-01],
       [ 2.67332902e-01],
       [ 4.94133091e-01],
       [ 3.06413400e-01],
       [ 7.48025049e-01],
       [ 7.65921701e-01],
       [ 1.31511353e+00],
       [ 2.52147729e-01],
       [ 2.41000093e-01],
       [ 1.16875638e+00],
       [ 4.86581663e-02],
       [ 2.86292169e-01],
       [ 2.30430841e-01],
       [ 3.06669342e-01],
       [ 1.44447752e+00],
       [ 4.62201708e-01],
       [ 2.03969220e-01],
       [ 6.23837895e-01],
       [ 3.15139745e-01],
       [ 6.98427478e-02],
       [ 3.91159311e-01],
       [ 2.59986419e-01],
       [ 2.33864942e-01],
       [ 1.96586415e-01],
       [ 9.23710758e-02],
       [ 9.90125152e-01],
       [ 1.61262074e-01],
       [ 9.04711127e-01],
       [ 1.44631874e-01],
       [ 6.40970284e-01],
       [ 7.19695713e-01],
       [ 4.42860936e-01],
       [ 8.61374057e-01],
       [ 3.81025707e-01],
       [ 3.01630172e-01],
       [ 4.79981875e-01],
       [ 1.72050375e+00],
       [ 1.54730485e-01],
       [ 5.88504318e-01],
       [ 1.90267098e-01],
       [ 1.16434199e+00],
       [ 1.60754809e-01],
       [ 2.07623858e-01],
       [ 2.97677934e-01],
       [ 2.14740826e+00],
       [ 3.20761852e-01],
       [ 2.09397418e-01],
       [ 1.87779313e-01],
       [ 1.99740810e-01],
       [ 5.09031759e-01],
       [ 6.25748691e-02],
       [ 3.34521864e-01],
       [ 9.66420480e-02],
       [ 1.46269376e-02],
       [ 3.02975163e-01],
       [ 3.83801283e-01],
       [ 4.84825096e-01],
       [ 1.56367368e-01],
       [ 6.56443675e-01],
       [ 1.95431081e-01],
       [ 1.10229391e+00],
       [ 3.30491307e-01],
       [ 8.79792297e-01],
       [ 1.01282607e-01],
       [ 1.32821469e-01],
       [ 1.24707058e-01],
       [ 4.50601507e-01],
       [ 3.49949622e-01],
       [ 8.55213441e-02],
       [ 1.08592787e+00],
       [ 1.91857618e-01],
       [ 1.08898983e+00],
       [ 4.29232590e-01],
       [ 2.51456516e-01],
       [ 7.69758612e-01],
       [ 2.19674601e-01],
       [ 1.29897555e-01],
       [ 4.58552564e-01],
       [ 9.60978910e-02],
       [ 2.18988122e-01],
       [ 6.10647007e-01],
       [ 5.51227122e-01],
       [ 3.97028605e-01],
       [ 1.75867078e-01],
       [ 2.51817488e-01],
       [ 5.25842959e-01],
       [ 4.94462323e-01],
       [ 1.76078653e-01],
       [ 1.24672202e+00],
       [ 6.08590713e-02],
       [ 5.81634749e-03],
       [ 2.59131227e-01],
       [ 1.55699968e-01],
       [ 6.60484855e-01],
       [ 8.03661673e-02],
       [ 1.02276609e-01],
       [ 8.08534424e-01],
       [ 3.63040353e-01],
       [ 6.93809834e-01],
       [ 1.60959141e+00],
       [ 1.19866038e+00],
       [ 2.73905436e-01],
       [ 1.24922500e-01],
       [ 9.14659501e-01],
       [ 3.25067340e-01],
       [ 1.27747740e-01],
       [ 3.54150259e-01],
       [ 2.71959474e-01],
       [ 1.02884384e+00],
       [ 4.34126207e-01],
       [ 1.42779844e-01],
       [-3.41110307e-02],
       [ 6.11758873e-01],
       [ 2.11189845e-01],
       [ 4.31537995e-01],
       [ 4.14344699e-01],
       [ 8.65283878e-01],
       [ 4.53052981e-01],
       [ 1.88765932e-01],
       [ 2.43740901e+00],
       [ 8.64558383e-01],
       [ 1.99182469e-01],
       [ 2.45531743e-01],
       [ 2.93900328e-01],
       [ 1.92628995e+00],
       [ 1.26326073e+00],
       [ 1.92813578e-01],
       [ 2.54663228e-01],
       [ 9.68805020e-02],
       [ 9.59248059e-01],
       [ 2.07185967e-01],
       [ 1.60621421e-01],
       [ 4.23256954e-01],
       [ 1.09678295e+00],
       [ 6.10013810e-01],
       [ 1.12030046e-01],
       [ 2.88510204e-01],
       [ 2.72570569e-01],
       [ 9.63649181e-02],
       [ 9.39503009e-02],
       [ 9.83317212e-01],
       [ 7.21609794e-01],
       [ 7.74033556e-01],
       [ 1.89856000e+00],
       [ 7.98594998e-01],
       [ 6.05225714e-01],
       [ 3.68278718e-01],
       [ 1.32323211e-01],
       [ 3.31397728e-01],
       [ 5.41261690e-03],
       [ 1.13036549e+00],
       [ 4.43501127e-01],
       [ 5.96664473e-03],
       [ 9.20506508e-02],
       [ 4.14251837e-01],
       [ 1.28875678e-01],
       [ 1.64315476e-01],
       [ 1.27842103e-01],
       [ 4.78130760e-02],
       [ 3.62006883e-01],
       [ 2.37602896e-01],
       [ 2.08282228e-01],
       [ 6.94920211e-02],
       [ 1.27555009e+00],
       [ 2.74898197e-01],
       [ 4.52025715e-01],
       [ 3.45016163e-01],
       [ 1.78199203e-01],
       [ 6.72185172e-01],
       [ 5.35072198e-01],
       [ 1.76274547e-01],
       [ 7.44605995e-01],
       [ 3.78123462e-02],
       [ 1.89605049e-01],
       [ 9.94741438e-01],
       [ 2.06640807e-01],
       [ 9.65239567e-02],
       [ 3.03298658e-01],
       [ 3.48443636e-01],
       [ 6.75940414e-01],
       [ 3.38158228e-01],
       [ 1.27099960e+00],
       [ 5.15921206e-01],
       [ 1.25686390e-01],
       [ 1.07540603e+00],
       [ 1.33067871e-01],
       [ 1.96167566e-01],
       [ 9.66951536e-02],
       [ 1.28191469e-01],
       [ 1.11567695e-01],
       [ 1.22005247e+00],
       [ 5.57691928e-01],
       [ 1.83392685e+00],
       [ 4.97492620e-01],
       [ 2.87249828e-01],
       [ 3.00292417e-02],
       [ 4.11900386e-01],
       [ 8.07389034e-01],
       [ 7.51982062e-01],
       [ 3.63843691e-02],
       [ 1.45943859e+00],
       [ 3.85569973e-01],
       [ 1.38756506e+00],
       [ 1.22585109e-01],
       [ 6.37736281e-01],
       [ 9.47572063e-02],
       [ 2.44481945e-01],
       [ 4.18052889e-01],
       [ 2.60090924e-01],
       [ 2.91451445e-01],
       [-2.09729302e-04],
       [ 3.92382690e-01],
       [ 5.18939459e-01],
       [ 2.03175944e-01],
       [ 1.60631492e-01],
       [ 3.50652805e-01],
       [ 9.19140162e-01],
       [ 8.68779532e-01],
       [ 7.24095996e-01],
       [ 3.10029178e-01],
       [ 1.29625739e-01],
       [ 2.57303474e-01],
       [ 1.01324705e-01],
       [ 3.65362869e-01],
       [ 2.05149097e-01],
       [-5.29690893e-03],
       [ 6.09804779e-01],
       [ 1.41037826e-01],
       [ 9.77299453e-01],
       [ 1.63890390e+00],
       [ 2.76760837e-01],
       [ 6.44853739e-01],
       [ 3.67976140e-01],
       [ 4.93044653e-01],
       [ 2.11063444e-01],
       [ 1.45115347e-01],
       [ 1.18466022e-01],
       [ 4.97089932e-01],
       [ 3.88450311e-01],
       [ 3.13155213e-01],
       [ 3.68819502e-02],
       [ 6.34463805e-01],
       [ 6.20815808e-01],
       [ 2.03699119e-01],
       [ 8.43593259e-02],
       [ 2.58167502e-01],
       [ 5.70153221e-01],
       [ 5.30435347e-01],
       [ 1.51180867e-01],
       [ 1.11726318e-01],
       [ 3.35207810e-01],
       [ 3.98762709e-01],
       [ 6.07340786e-01],
       [ 1.30548983e-01],
       [ 2.28542863e-01],
       [ 6.41331284e-01],
       [ 7.84878099e-02],
       [ 8.35069358e-01],
       [ 4.13284844e-01],
       [ 9.79330848e-02],
       [ 4.94883437e-01],
       [ 1.06169721e+00],
       [ 1.45079793e-02],
       [ 1.01890936e+00],
       [-6.56704445e-04],
       [ 2.90842523e-01],
       [ 8.06613453e-01],
       [ 6.06090822e-01],
       [ 7.84859647e-01],
       [ 4.00058921e-01],
       [ 9.96482079e-02],
       [ 2.67968277e-01],
       [ 5.65152979e-01],
       [ 1.05849965e+00],
       [ 1.92021376e-01],
       [ 4.82862177e-01],
       [ 6.94676786e-02],
       [ 9.58726124e-02],
       [ 6.05380466e-02],
       [ 1.39446206e+00],
       [ 1.30143837e-01],
       [ 1.54399414e+00],
       [ 9.45464215e-02],
       [ 3.70052105e-01],
       [ 9.05621951e-01],
       [ 1.60495447e-01],
       [ 1.24704566e+00],
       [ 1.12768976e-01],
       [ 2.08465474e-01],
       [ 2.03445707e-02],
       [ 3.21509305e-02],
       [ 1.16882548e-01],
       [ 5.30905836e-01],
       [ 1.08098808e-01],
       [ 4.81797508e-01],
       [ 1.76408061e-01],
       [ 1.82362356e-01],
       [-3.38563977e-02],
       [ 2.26369804e-01],
       [ 2.14414651e-01],
       [ 1.53660914e-01],
       [ 4.76741218e-01],
       [ 1.46726964e-01],
       [ 1.69683225e+00],
       [ 4.28961736e-01],
       [ 1.64494656e-01],
       [ 2.71423017e-01],
       [ 5.90279001e-01],
       [ 4.81455809e-01],
       [ 7.51406848e-01],
       [ 2.30406458e-01],
       [-3.40115129e-02],
       [ 6.42664256e-01],
       [ 1.28305356e+00],
       [ 1.08389779e+00],
       [ 2.10602768e-01],
       [ 9.67647631e-02],
       [ 6.39458747e-02],
       [ 3.16221247e-01],
       [ 2.98388362e-01],
       [ 6.04415079e-01],
       [ 8.04192188e-01],
       [ 7.17763024e-01],
       [ 3.38013012e-02],
       [ 7.86931824e-01],
       [ 3.39407620e-02],
       [ 1.33368588e-01],
       [ 1.23574087e+00],
       [ 3.85982486e-01],
       [ 4.60493344e-01],
       [ 1.54635211e-01],
       [ 2.25490403e-01],
       [ 1.16328510e+00],
       [ 3.18477454e-01],
       [-3.36712037e-02],
       [ 1.19655980e-01],
       [ 3.41414683e-01],
       [ 5.95611262e-02],
       [ 3.17751594e-01],
       [ 7.69018878e-01],
       [ 1.20681601e+00],
       [ 2.08186704e-01],
       [ 1.62860098e-01],
       [ 8.03315530e-02],
       [ 5.12474542e-01],
       [ 2.54218405e-01],
       [ 3.21783515e-01],
       [ 8.70380611e-01],
       [ 1.76071476e-01],
       [ 1.12784484e-01],
       [ 8.36232621e-02],
       [ 6.83717908e-01],
       [ 3.07436796e-01],
       [ 7.38887240e-01],
       [ 4.75783741e-01],
       [ 3.44982885e-02],
       [ 2.89850010e-01],
       [ 6.61935853e-04],
       [ 1.80738281e-01],
       [ 2.91235195e-01],
       [ 2.40617219e-01],
       [ 6.45886926e-01],
       [ 1.44049409e-01],
       [ 6.86711233e-01],
       [ 2.86074547e-01],
       [ 1.45023708e+00],
       [ 3.83003203e-01],
       [ 2.19014931e-01],
       [ 1.76847285e-01],
       [ 1.44236742e+00],
       [ 3.44768204e-01],
       [ 1.26864184e+00],
       [ 2.11310268e-01],
       [ 3.51341377e-01],
       [ 3.21842514e-02],
       [ 1.65699204e-01],
       [ 3.66794719e-01],
       [-6.67866141e-04],
       [ 1.88982557e-01],
       [ 1.01299833e-01],
       [ 4.12793922e-01],
       [ 8.47421091e-02],
       [ 2.18504922e-01],
       [ 1.00650815e+00],
       [ 6.19323789e-01],
       [ 3.33974532e-02],
       [ 9.79731463e-02],
       [ 1.86326770e-01],
       [ 2.34380037e-01],
       [ 3.38190128e-01],
       [ 5.96104688e-02],
       [ 2.28405467e-01],
       [ 3.32682283e-01],
       [ 1.61198551e-01],
       [ 2.89393538e-01],
       [ 1.27122396e-01],
       [ 2.22697209e-01],
       [ 1.96508990e-01],
       [ 1.50183164e-01],
       [ 2.78331416e-01],
       [ 1.93316734e-01],
       [ 4.16808001e-01],
       [ 2.03398666e-01],
       [ 1.13794361e-01],
       [ 1.81870518e-01],
       [ 4.61168554e-01],
       [ 1.60669017e-01],
       [ 2.97738144e-02],
       [ 3.26551295e-01],
       [ 9.28530307e-02],
       [ 5.29967528e-01],
       [ 2.35533313e-01],
       [ 3.28702466e-02],
       [ 9.66646525e-02],
       [ 3.20400703e-01],
       [ 3.63629968e-01],
       [ 2.06972174e-01],
       [ 2.36855541e-01],
       [ 3.98711103e-01],
       [ 1.60873262e-01],
       [ 5.78402554e-01],
       [ 2.87439747e-01],
       [ 1.86322483e-01],
       [ 4.15924090e-01],
       [ 3.51337547e-01],
       [ 6.96541031e-02],
       [ 8.52219561e-02],
       [ 4.26286463e-02],
       [ 3.23175705e-01],
       [ 4.74345854e-02],
       [ 2.68705770e-04],
       [ 3.47584712e-01],
       [ 2.85373080e-01],
       [ 9.43517859e-02],
       [ 1.10138150e-01],
       [ 5.61085763e-01],
       [ 3.80888345e-01],
       [ 1.91898877e-01],
       [ 3.68715258e-01],
       [ 6.54435033e-02],
       [ 1.81887637e-01],
       [ 1.10272353e-01],
       [ 3.59737073e-02],
       [ 6.71599614e-01],
       [ 1.70909895e-01],
       [ 2.53240048e-01],
       [ 9.35594328e-02],
       [-7.58257635e-04],
       [ 1.13666776e-01],
       [ 5.74737673e-03],
       [ 3.32159580e-01],
       [ 6.49842219e-02],
       [ 2.08440138e-01],
       [ 4.48992121e-01],
       [ 4.52607600e-01],
       [ 1.65875145e-01],
       [ 1.33305052e-01],
       [ 1.75461149e-01],
       [-3.37186285e-02],
       [ 1.25133805e-01],
       [ 3.36734657e-01],
       [ 1.22888378e-05],
       [ 6.87442318e-03],

In [417]:
mae = mean_absolute_error(y_test['ltv_30d_log'],y_pred)
rmse = np.sqrt(mean_squared_error(y_test['ltv_30d_log'], y_pred))
r2 = r2_score(y_test['ltv_30d_log'], y_pred)

In [418]:
print('mae',mae)
print('rmse',rmse)
print('r2',r2)

mae 0.4859991048628692
rmse 0.7413373563166228
r2 0.2153168125385576

In [421]:
print('mae_base',mae_base)
print('rmse_base',rmse_base)
print('r2_base',r2_base)

mae_base 0.5457414690186172
rmse_base 1.1345008881805416
r2_base -0.8376900254053452

In [422]:
# slice analysis

In [424]:
X_test

,total_spend_7d,total_sessions_7d,total_playtime_7d,d1_retention_flag,active_days_7d,platform,country,nunique_creators
4117,0.000000,3,25.171890,0,2,ios,CA,2
4118,0.000000,2,25.546162,0,2,android,CA,2
4119,0.205324,23,244.130490,1,7,web,CA,7
4120,0.000000,2,17.892521,0,2,ios,IN,2
4121,0.000000,15,193.350842,1,7,web,UK,7
...,...,...,...,...,...,...,...,...
4973,0.000000,1,16.979310,0,1,android,US,1
4974,0.000000,1,19.540930,0,1,web,CA,1
4975,0.000000,3,38.767414,0,3,web,UK,3
4976,0.000000,1,13.558387,0,1,android,US,1
4977,0.000000,1,16.229255,0,1,android,UK,1

In [430]:
y_test['pred'] = y_pred
y_test['platform'] = X_test['platform']
y_test['country'] = X_test['country']
y_test

      ltv_30d_log      pred platform country
4117     2.395777  0.111631      ios      CA
4118     0.000000  0.070001  android      CA
4119     2.217846  1.152273      web      CA
4120     0.000000  0.095634      ios      IN
4121     2.739300  0.767343      web      UK
...           ...       ...      ...     ...
4973     0.000000 -0.027566  android      US
4974     0.000000  0.033964      web      CA
4975     0.000000  0.160915      web      UK
4976     0.000000 -0.027795  android      US
4977     0.000000  0.005932  android      UK

[861 rows x 4 columns]

In [431]:
y_eval = y_test.groupby(['platform']).apply(lambda x:pd.Series({'mae':mean_absolute_error(x['ltv_30d_log'],x['pred']),
    'rmse':np.sqrt(mean_squared_error(x['ltv_30d_log'],x['pred'])),
    'r2': r2_score(x['ltv_30d_log'],x['pred'])}))

/var/folders/qh/wcp4hdh55d56zf2h540jdxlr0000gn/T/ipykernel_62040/3855858483.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  y_eval = y_test.groupby(['platform']).apply(lambda x:pd.Series({'mae':mean_absolute_error(x['ltv_30d_log'],x['pred']),

In [432]:
y_eval

               mae      rmse        r2
platform
android   0.438971  0.707327  0.182608
ios       0.514561  0.777499  0.250249
web       0.498738  0.732795  0.189026

In [433]:
y_eval_country = y_test.groupby(['country']).apply(lambda x:pd.Series({'mae':mean_absolute_error(x['ltv_30d_log'],x['pred']),
    'rmse':np.sqrt(mean_squared_error(x['ltv_30d_log'],x['pred'])),
    'r2': r2_score(x['ltv_30d_log'],x['pred'])}))

/var/folders/qh/wcp4hdh55d56zf2h540jdxlr0000gn/T/ipykernel_62040/2287924537.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  y_eval_country = y_test.groupby(['country']).apply(lambda x:pd.Series({'mae':mean_absolute_error(x['ltv_30d_log'],x['pred']),

In [434]:
y_eval_country

              mae      rmse        r2
country
CA       0.420179  0.633508  0.230377
IN       0.533562  0.812387  0.163789
UK       0.489926  0.741450  0.259805
US       0.490794  0.752006  0.201236

In [ ]:
# suggested user heterogeneity

In [ ]:
# SQL problems: missing END, 7d retention, naming cannot start with number, did not include joining day!!!
# Python problems: confusion around train and test split, feature engineering forgot features, pipeline forget syntax

## Practice 4

In [435]:
df

,user_id,date,sessions,play_time,spend,creator_id,platform,country
0,0,2025-01-07,1,11.888733,0.000000,373,ios,US
1,0,2025-01-08,1,19.548648,0.000000,492,ios,US
2,0,2025-01-10,3,16.037809,0.000000,475,ios,US
3,0,2025-01-13,1,16.777639,0.000000,563,ios,US
4,0,2025-01-14,3,35.272466,0.000000,274,ios,US
...,...,...,...,...,...,...,...,...
70553,4999,2025-01-26,3,32.599466,0.000000,688,web,IN
70554,4999,2025-01-27,2,16.721781,0.000000,450,web,IN
70555,4999,2025-01-28,2,18.727887,8.605824,83,web,IN
70556,4999,2025-01-29,2,18.667530,0.000000,767,web,IN
70557,4999,2025-01-30,3,57.009896,2.185158,560,web,IN

In [ ]:
# features day 0-6
    # total spend in 7d, number of sessions , total playtime
    # d1 retention, number of actice days in 7d
    # nunique of creators
    # platform, country
# target day 7-29
    # sum of total spend of  day 7-29

In [ ]:
with join_date_t as 
(select
    *,
    MIN(date) over(partition by user_id) as joining_date
from df_table),
date_diff_t as
(select
    *,
    DATEDIFF('day', joining_date, date) as day_diff
from join_date_t
)

select
    user_id,
    MIN(joining_date),
    MAX(platform) as platform,
    MAX(country) as country,
    SUM(CASE WHEN day_diff BETWEEN 0 AND 6 THEN spend ELSE 0 END) as total_spend_7d,
    SUM(CASE WHEN day_diff BETWEEN 0 AND 6 THEN sessions ELSE 0 END) as total_sessions_7d,
    SUM(CASE WHEN day_diff BETWEEN 0 AND 6 THEN play_time ELSE 0 END) as total_play_time_7d,
    MAX(CASE WHEN day_diff = 1 THEN 1 ELSE 0 END) as d1_retention_flag,
    COUNT(DISTINCT CASE WHEN day_diff BETWEEN 0 AND 6 THEN date END) as active_days_7d,
    COUNT(DISTINCT CASE WHEN day_diff BETWEEN 0 AND 6 THEN creator_id END) as ncreator_7d,
    SUM(CASE WHEN day_diff BETWEEN 7 AND 29 THEN spend ELSE 0 END) as ltv_30d
from date_diff_t
group by user_id

In [436]:
processed_df = pd.read_csv("/Users/zhuangdiezhou/Documents/Documents - Zhuangdie Alan Zhou's MacBook Pro - 1/Hi_Sexy/Interview/Roblox/user_activity_after_sql_final.csv")

In [437]:
processed_df.head()

,user_id,joining_date,total_spend_7d,total_sessions_7d,total_playtime_7d,d1_retention_flag,active_days_7d,platform,country,nunique_creators,ltv_30d
0,0,2025-01-07,0.0,6,64.252830,1,4,ios,US,4,0.0
1,1,2025-01-26,0.0,2,14.305001,0,2,ios,US,2,0.0
2,2,2025-01-02,0.0,7,102.255638,0,3,ios,UK,3,0.0
3,3,2025-01-19,0.0,3,31.861878,0,3,android,IN,3,0.0
4,4,2025-02-05,0.0,4,32.449207,1,3,android,CA,3,0.0

In [440]:
processed_df.describe(include = 'all')

,user_id,joining_date,total_spend_7d,total_sessions_7d,total_playtime_7d,d1_retention_flag,active_days_7d,platform,country,nunique_creators,ltv_30d
count,4978.000000,4978,4978.000000,4978.000000,4978.000000,4978.000000,4978.000000,4978,4978,4978.000000,4978.000000
unique,NaN,45,NaN,NaN,NaN,NaN,NaN,3,4,NaN,NaN
top,NaN,2025-01-29,NaN,NaN,NaN,NaN,NaN,web,US,NaN,NaN
freq,NaN,198,NaN,NaN,NaN,NaN,NaN,1716,1277,NaN,NaN
mean,2500.483126,NaN,0.945910,9.167738,114.566627,0.588188,4.361189,NaN,NaN,4.349538,1.915623
std,1443.721875,NaN,3.171391,8.237568,105.341417,0.492211,1.846891,NaN,NaN,1.840310,5.114650
min,0.000000,NaN,0.000000,1.000000,5.073930,0.000000,1.000000,NaN,NaN,1.000000,0.000000
25%,1251.250000,NaN,0.000000,3.000000,42.178059,0.000000,3.000000,NaN,NaN,3.000000,0.000000
50%,2499.500000,NaN,0.000000,6.000000,77.171421,1.000000,4.000000,NaN,NaN,4.000000,0.000000
75%,3751.750000,NaN,0.000000,12.000000,152.329670,1.000000,6.000000,NaN,NaN,6.000000,0.000000
max,4999.000000,NaN,44.112869,55.000000,798.519567,1.000000,7.000000,NaN,NaN,7.000000,55.597312

In [441]:
processed_df['ltv_30d'].skew()

np.float64(3.9558069791818)

In [442]:
processed_df['ltv_30d_log'] = np.log1p(processed_df['ltv_30d'])

In [443]:
processed_df.head()

,user_id,joining_date,total_spend_7d,total_sessions_7d,total_playtime_7d,d1_retention_flag,active_days_7d,platform,country,nunique_creators,ltv_30d,ltv_30d_log
0,0,2025-01-07,0.0,6,64.252830,1,4,ios,US,4,0.0,0.0
1,1,2025-01-26,0.0,2,14.305001,0,2,ios,US,2,0.0,0.0
2,2,2025-01-02,0.0,7,102.255638,0,3,ios,UK,3,0.0,0.0
3,3,2025-01-19,0.0,3,31.861878,0,3,android,IN,3,0.0,0.0
4,4,2025-02-05,0.0,4,32.449207,1,3,android,CA,3,0.0,0.0

In [447]:
processed_df = processed_df.sort_values(by = 'joining_date').reset_index(drop = True)

In [448]:
processed_df.head()

,user_id,joining_date,total_spend_7d,total_sessions_7d,total_playtime_7d,d1_retention_flag,active_days_7d,platform,country,nunique_creators,ltv_30d,ltv_30d_log
0,2499,2025-01-01,0.0,7,80.359712,1,5,web,UK,5,0.000000,0.000000
1,2127,2025-01-01,0.0,8,90.376932,1,6,ios,UK,6,3.909909,1.591255
2,2084,2025-01-01,0.0,11,138.710523,1,5,web,IN,5,0.510291,0.412302
3,267,2025-01-01,0.0,5,50.855062,1,4,android,US,4,0.000000,0.000000
4,694,2025-01-01,0.0,39,608.039224,1,7,android,US,7,7.960739,2.192853

In [449]:
idx = int(processed_df.shape[0]*0.8)
idx

3982

In [450]:
date_cutoff = processed_df.loc[idx]['joining_date']
date_cutoff

'2025-01-26'

In [451]:
processed_df.columns

Index(['user_id', 'joining_date', 'total_spend_7d', 'total_sessions_7d',
       'total_playtime_7d', 'd1_retention_flag', 'active_days_7d', 'platform',
       'country', 'nunique_creators', 'ltv_30d', 'ltv_30d_log'],
      dtype='object')

In [452]:
train = processed_df[processed_df['joining_date']<=date_cutoff]
test = processed_df[processed_df['joining_date']>date_cutoff]

In [453]:
train.shape, test.shape

((4117, 12), (861, 12))

In [454]:
features = ['total_spend_7d', 'total_sessions_7d',
       'total_playtime_7d', 'd1_retention_flag', 'active_days_7d', 'platform',
       'country', 'nunique_creators']
target = ['ltv_30d_log']

In [455]:
X_train = train[features]
y_train = train[target]

X_test = test[features]
y_test = test[target]

In [457]:
X_train.head(), y_train.head()

(   total_spend_7d  total_sessions_7d  total_playtime_7d  d1_retention_flag  \
 0             0.0                  7          80.359712                  1
 1             0.0                  8          90.376932                  1
 2             0.0                 11         138.710523                  1
 3             0.0                  5          50.855062                  1
 4             0.0                 39         608.039224                  1

    active_days_7d platform country  nunique_creators
 0               5      web      UK                 5
 1               6      ios      UK                 6
 2               5      web      IN                 5
 3               4  android      US                 4
 4               7  android      US                 7  ,
    ltv_30d_log
 0     0.000000
 1     1.591255
 2     0.412302
 3     0.000000
 4     2.192853)

In [458]:
# baseline
y_pred_base = X_test['total_spend_7d']/7*(30-7)
y_pred_base

4117    0.000000
4118    0.000000
4119    0.674637
4120    0.000000
4121    0.000000
          ...
4973    0.000000
4974    0.000000
4975    0.000000
4976    0.000000
4977    0.000000
Name: total_spend_7d, Length: 861, dtype: float64

In [459]:
y_pred_base_log = np.log1p(y_pred_base)
y_pred_base_log

4117    0.000000
4118    0.000000
4119    0.515597
4120    0.000000
4121    0.000000
          ...
4973    0.000000
4974    0.000000
4975    0.000000
4976    0.000000
4977    0.000000
Name: total_spend_7d, Length: 861, dtype: float64

In [460]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [461]:
mae_base = mean_absolute_error(y_test['ltv_30d_log'], y_pred_base_log)
rmse_base = np.sqrt(mean_squared_error(y_test['ltv_30d_log'], y_pred_base_log))
r2_base = r2_score(y_test['ltv_30d_log'], y_pred_base_log)

In [462]:
print('mae_base',mae_base)
print('rmse_base',rmse_base)
print('r2_base',r2_base)

mae_base 0.5457414690186172
rmse_base 1.1345008881805416
r2_base -0.8376900254053452

In [463]:
# feature engineering

In [464]:
X_train.head()

,total_spend_7d,total_sessions_7d,total_playtime_7d,d1_retention_flag,active_days_7d,platform,country,nunique_creators
0,0.0,7,80.359712,1,5,web,UK,5
1,0.0,8,90.376932,1,6,ios,UK,6
2,0.0,11,138.710523,1,5,web,IN,5
3,0.0,5,50.855062,1,4,android,US,4
4,0.0,39,608.039224,1,7,android,US,7

In [465]:
num_cols = X_train.select_dtypes(include = 'number').columns
num_cols

Index(['total_spend_7d', 'total_sessions_7d', 'total_playtime_7d',
       'd1_retention_flag', 'active_days_7d', 'nunique_creators'],
      dtype='object')

In [469]:
num_cols = num_cols.drop('d1_retention_flag')

In [470]:
num_cols

Index(['total_spend_7d', 'total_sessions_7d', 'total_playtime_7d',
       'active_days_7d', 'nunique_creators'],
      dtype='object')

In [471]:
cat_cols = ['d1_retention_flag','platform','country']

In [472]:
X_train[cat_cols].nunique()

d1_retention_flag    2
platform             3
country              4
dtype: int64

In [473]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [474]:
num_pipeline = Pipeline([
    ('norm',StandardScaler())
])

In [475]:
cat_pipeline = Pipeline([
    ('onehot',OneHotEncoder(handle_unknown = 'ignore', sparse_output = False))
])

In [478]:
num_pipeline

Pipeline(steps=[('norm', StandardScaler())])

In [479]:
cat_pipeline

Pipeline(steps=[('onehot',
                 OneHotEncoder(handle_unknown='ignore', sparse_output=False))])

In [481]:
preprocessor = ColumnTransformer([
    ('num', num_pipeline, num_cols),
    ('cat', cat_pipeline, cat_cols)
    
],remainder = 'drop')

In [482]:
preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('norm', StandardScaler())]),
                                 Index(['total_spend_7d', 'total_sessions_7d', 'total_playtime_7d',
       'active_days_7d', 'nunique_creators'],
      dtype='object')),
                                ('cat',
                                 Pipeline(steps=[('onehot',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['d1_retention_flag', 'platform', 'country'])])

In [483]:
from sklearn.linear_model import LinearRegression

In [485]:
model = Pipeline([
    ('preprocessor',preprocessor),
    ('regressor', LinearRegression())
])

In [486]:
model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('norm',
                                                                   StandardScaler())]),
                                                  Index(['total_spend_7d', 'total_sessions_7d', 'total_playtime_7d',
       'active_days_7d', 'nunique_creators'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['d1_retention_flag',
                                                   'platform', 'country'])])),
                ('regressor', LinearRegression())])

In [487]:
model.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('norm',
                                                                   StandardScaler())]),
                                                  Index(['total_spend_7d', 'total_sessions_7d', 'total_playtime_7d',
       'active_days_7d', 'nunique_creators'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['d1_retention_flag',
                                                   'platform', 'country'])])),
                ('regressor', LinearRegression())])

In [489]:
y_pred = model.predict(X_test)
y_pred

array([[ 1.11630885e-01],
       [ 7.00009532e-02],
       [ 1.15227314e+00],
       [ 9.56338599e-02],
       [ 7.67343403e-01],
       [ 9.75171919e-02],
       [ 5.26716537e-01],
       [ 3.47962105e-01],
       [ 3.03295561e-02],
       [ 8.45687840e-01],
       [ 3.54973396e-02],
       [ 1.82982859e-01],
       [ 3.42249193e-01],
       [ 3.07071849e-01],
       [ 1.33516958e-01],
       [ 1.91148218e-01],
       [ 2.13866116e+00],
       [-2.76057681e-02],
       [ 9.96906145e-02],
       [ 9.65024705e-01],
       [ 6.98058960e-02],
       [ 2.09798165e-01],
       [ 5.62435450e-01],
       [ 8.47812959e-02],
       [ 2.22701275e-01],
       [ 1.15870970e+00],
       [ 7.05040225e-02],
       [ 1.33685200e-01],
       [ 3.26257824e-02],
       [ 9.19201813e-01],
       [ 3.97547541e-01],
       [ 1.78226446e+00],
       [ 1.18207933e-01],
       [ 1.46165445e-01],
       [ 4.13424379e-01],
       [ 1.84320804e-01],
       [ 2.50362114e-01],
       [ 7.69574392e-01],
       [ 4.29640422e-01],
       [ 1.80019935e+00],
       [ 1.98366819e-01],
       [ 3.63330808e-01],
       [ 1.33301990e+00],
       [ 2.81733372e-02],
       [ 1.30006550e-01],
       [ 1.10572225e+00],
       [ 8.20480740e-01],
       [ 3.79659767e-01],
       [ 1.14460352e+00],
       [ 6.46700242e-03],
       [ 6.40144538e-02],
       [ 5.00304656e-01],
       [ 1.18825830e+00],
       [ 2.54016454e-01],
       [ 7.68333220e-01],
       [ 1.58251319e-01],
       [ 1.55415036e-01],
       [ 5.87234831e-02],
       [ 1.33543782e-01],
       [ 3.66207269e-01],
       [ 1.33721153e-01],
       [ 5.05856692e-01],
       [ 4.34000617e-01],
       [ 2.70474509e-01],
       [ 2.75063216e-01],
       [ 1.11663271e+00],
       [ 7.51592231e-01],
       [ 2.39054647e-01],
       [ 1.07224168e+00],
       [ 1.91997565e-01],
       [ 2.92669960e-01],
       [ 3.55872710e-01],
       [ 3.75191536e-01],
       [ 2.25823451e-01],
       [ 3.70257603e-01],
       [ 6.09445485e-04],
       [ 4.46970939e-01],
       [ 1.74741288e-01],
       [ 4.81805251e-02],
       [ 9.12761400e-02],
       [ 8.63106056e-01],
       [ 1.15631351e+00],
       [ 4.64197122e-01],
       [ 3.85783126e-01],
       [ 4.95358019e-01],
       [ 4.62932632e-01],
       [ 9.13144928e-01],
       [ 7.51370810e-01],
       [ 1.61594746e-01],
       [ 5.40686506e-01],
       [ 1.48611415e+00],
       [ 3.37605570e-01],
       [ 2.00171322e+00],
       [ 1.81877632e-01],
       [ 1.34524583e-01],
       [ 1.70632955e+00],
       [ 6.29182698e-02],
       [ 4.82563706e-01],
       [ 1.75916309e-01],
       [ 7.17124944e-01],
       [ 2.41590645e-01],
       [ 2.14532627e-01],
       [ 4.80262094e-01],
       [ 6.47190403e-01],
       [ 1.40691275e-01],
       [ 2.24441384e-01],
       [ 7.16845206e-01],
       [ 2.91206203e-01],
       [ 6.38571870e-04],
       [-3.03585598e-04],
       [ 5.42793051e-01],
       [ 5.96486940e-03],
       [ 6.84300062e-01],
       [ 3.52798695e-01],
       [ 3.16848663e-01],
       [ 1.12507265e+00],
       [ 8.81516343e-01],
       [ 4.00323471e-01],
       [ 2.41733998e-01],
       [ 7.49967852e-01],
       [ 1.24969004e-01],
       [ 3.44111551e-01],
       [ 1.27418923e-01],
       [ 1.50547368e-01],
       [ 2.07630024e-01],
       [ 9.72799097e-02],
       [ 7.67162854e-01],
       [ 8.13020656e-01],
       [ 1.61364873e-01],
       [ 2.86904438e-01],
       [ 8.16436700e-01],
       [ 6.27274420e-02],
       [ 1.81059852e+00],
       [ 2.57542844e-01],
       [ 3.17204528e-01],
       [ 2.99484966e-01],
       [ 9.09050882e-01],
       [ 3.18416771e-01],
       [ 4.03060152e-01],
       [ 1.66301641e-01],
       [ 8.70884495e-01],
       [ 5.05232457e-01],
       [ 8.34314773e-01],
       [ 1.93065922e+00],
       [ 1.76948627e-01],
       [ 1.02383239e+00],
       [ 3.50171813e-01],
       [ 1.61374214e-01],
       [ 8.97846612e-01],
       [ 3.34336140e-01],
       [ 1.22642906e+00],
       [ 2.39702213e-01],
       [ 3.87207226e-01],
       [ 1.60442587e-01],
       [ 9.19745961e-02],
       [ 2.76523222e-02],
       [ 1.92750418e-01],
       [ 6.96153207e-02],
       [ 9.56913503e-01],
       [ 1.78375100e+00],
       [ 1.61745752e+00],
       [ 2.39987287e-01],
       [ 1.55486620e-01],
       [-5.48775779e-03],
       [ 1.62665124e-01],
       [ 2.90078575e-01],
       [ 1.66631110e+00],
       [ 1.01232636e+00],
       [ 1.55427400e-01],
       [ 4.34603908e-01],
       [ 4.35802500e-01],
       [ 9.41153200e-02],
       [ 2.07761776e-01],
       [ 3.84691108e-01],
       [ 4.26226448e-01],
       [ 6.59064587e-01],
       [ 1.26908638e+00],
       [ 5.93728350e-01],
       [ 2.36143518e-01],
       [ 5.91446974e-03],
       [ 8.15627225e-01],
       [ 1.90400643e-01],
       [ 2.55044182e-01],
       [ 4.32887020e-01],
       [ 3.33539743e-01],
       [ 2.70616553e-01],
       [ 1.05660953e+00],
       [ 2.08473302e-01],
       [ 2.21787136e-01],
       [ 1.01588363e-01],
       [ 1.56561704e-01],
       [ 1.04543051e+00],
       [ 3.24045538e-02],
       [ 1.27521864e-01],
       [ 2.23469825e-01],
       [ 3.32660460e-01],
       [ 4.28908879e-01],
       [ 3.22229221e-01],
       [ 4.85076515e-01],
       [ 2.23737162e-01],
       [ 1.66109249e-01],
       [ 1.01019805e-01],
       [ 4.78111102e-01],
       [ 1.03233655e+00],
       [ 2.88944921e-01],
       [ 1.17093791e+00],
       [ 3.39404993e-01],
       [ 5.95880292e-01],
       [ 9.69681656e-02],
       [ 5.85830253e-02],
       [ 1.33393396e-01],
       [ 2.90704051e-01],
       [ 3.53256985e-01],
       [ 1.57125563e-01],
       [ 6.33207692e-02],
       [ 2.56182422e-01],
       [ 2.10000380e-01],
       [ 4.91374901e-01],
       [ 2.29086946e-01],
       [-3.35721685e-02],
       [ 1.42286012e-01],
       [ 1.81867030e-01],
       [ 1.93554654e-01],
       [ 3.79778104e-01],
       [ 1.88597700e+00],
       [ 3.01278953e-02],
       [ 4.83941521e-01],
       [ 3.34104641e-02],
       [ 2.88709916e-01],
       [ 6.56608097e-02],
       [ 9.63045800e-02],
       [ 3.52178331e-01],
       [ 4.29274807e-01],
       [ 6.05664569e-01],
       [ 3.27916536e-01],
       [ 8.52304683e-01],
       [ 5.47986887e-01],
       [ 4.61148527e-01],
       [ 2.56502743e-01],
       [ 8.75183272e-01],
       [ 6.39424446e-02],
       [ 3.16653964e-01],
       [ 3.96087598e-01],
       [ 2.39407251e-01],
       [ 1.34120439e-01],
       [ 9.68640468e-02],
       [ 1.55048390e-01],
       [ 3.69369058e-02],
       [ 5.67627656e-01],
       [ 4.19444976e-01],
       [ 2.84906381e-01],
       [ 3.83445428e-02],
       [ 5.11632781e-01],
       [ 3.43466620e-01],
       [ 1.29281562e-01],
       [ 3.67475285e-01],
       [ 5.08935436e-01],
       [ 5.77220427e-01],
       [ 2.58632714e-01],
       [ 2.88269203e-01],
       [ 7.88261385e-01],
       [ 1.95173442e-01],
       [ 9.35580203e-02],
       [ 3.50425104e-01],
       [ 6.66836426e-01],
       [ 1.87960324e-01],
       [ 3.23480984e-02],
       [ 1.28931493e-01],
       [ 5.32615378e-01],
       [ 2.88425503e-01],
       [ 3.32385964e-01],
       [ 9.76908539e-02],
       [ 9.77663271e-01],
       [ 5.91093271e-01],
       [ 1.60914223e-01],
       [ 1.91077963e-01],
       [ 1.66396079e-01],
       [ 6.94881747e-02],
       [ 9.73345578e-01],
       [ 1.76154525e-01],
       [ 1.46674918e+00],
       [ 1.22589735e-01],
       [ 2.14984118e+00],
       [ 2.57285066e-01],
       [ 7.24597433e-01],
       [ 3.33497807e-01],
       [ 1.45160026e+00],
       [ 5.18942604e-01],
       [ 2.19119507e-01],
       [ 1.71173333e-01],
       [ 9.61225666e-02],
       [ 3.89419395e-01],
       [ 6.37625240e-02],
       [ 3.41275338e-01],
       [ 1.18530208e+00],
       [ 2.21457015e-01],
       [ 6.76405770e-01],
       [ 3.07911490e-01],
       [ 9.68434782e-02],
       [ 1.10712657e+00],
       [ 1.39727784e-01],
       [ 3.33824846e-02],
       [ 7.89557239e-01],
       [ 2.68647804e-01],
       [ 1.38376703e-01],
       [ 2.85857317e-01],
       [ 3.21347597e-01],
       [ 2.67332902e-01],
       [ 4.94133091e-01],
       [ 3.06413400e-01],
       [ 7.48025049e-01],
       [ 7.65921701e-01],
       [ 1.31511353e+00],
       [ 2.52147729e-01],
       [ 2.41000093e-01],
       [ 1.16875638e+00],
       [ 4.86581663e-02],
       [ 2.86292169e-01],
       [ 2.30430841e-01],
       [ 3.06669342e-01],
       [ 1.44447752e+00],
       [ 4.62201708e-01],
       [ 2.03969220e-01],
       [ 6.23837895e-01],
       [ 3.15139745e-01],
       [ 6.98427478e-02],
       [ 3.91159311e-01],
       [ 2.59986419e-01],
       [ 2.33864942e-01],
       [ 1.96586415e-01],
       [ 9.23710758e-02],
       [ 9.90125152e-01],
       [ 1.61262074e-01],
       [ 9.04711127e-01],
       [ 1.44631874e-01],
       [ 6.40970284e-01],
       [ 7.19695713e-01],
       [ 4.42860936e-01],
       [ 8.61374057e-01],
       [ 3.81025707e-01],
       [ 3.01630172e-01],
       [ 4.79981875e-01],
       [ 1.72050375e+00],
       [ 1.54730485e-01],
       [ 5.88504318e-01],
       [ 1.90267098e-01],
       [ 1.16434199e+00],
       [ 1.60754809e-01],
       [ 2.07623858e-01],
       [ 2.97677934e-01],
       [ 2.14740826e+00],
       [ 3.20761852e-01],
       [ 2.09397418e-01],
       [ 1.87779313e-01],
       [ 1.99740810e-01],
       [ 5.09031759e-01],
       [ 6.25748691e-02],
       [ 3.34521864e-01],
       [ 9.66420480e-02],
       [ 1.46269376e-02],
       [ 3.02975163e-01],
       [ 3.83801283e-01],
       [ 4.84825096e-01],
       [ 1.56367368e-01],
       [ 6.56443675e-01],
       [ 1.95431081e-01],
       [ 1.10229391e+00],
       [ 3.30491307e-01],
       [ 8.79792297e-01],
       [ 1.01282607e-01],
       [ 1.32821469e-01],
       [ 1.24707058e-01],
       [ 4.50601507e-01],
       [ 3.49949622e-01],
       [ 8.55213441e-02],
       [ 1.08592787e+00],
       [ 1.91857618e-01],
       [ 1.08898983e+00],
       [ 4.29232590e-01],
       [ 2.51456516e-01],
       [ 7.69758612e-01],
       [ 2.19674601e-01],
       [ 1.29897555e-01],
       [ 4.58552564e-01],
       [ 9.60978910e-02],
       [ 2.18988122e-01],
       [ 6.10647007e-01],
       [ 5.51227122e-01],
       [ 3.97028605e-01],
       [ 1.75867078e-01],
       [ 2.51817488e-01],
       [ 5.25842959e-01],
       [ 4.94462323e-01],
       [ 1.76078653e-01],
       [ 1.24672202e+00],
       [ 6.08590713e-02],
       [ 5.81634749e-03],
       [ 2.59131227e-01],
       [ 1.55699968e-01],
       [ 6.60484855e-01],
       [ 8.03661673e-02],
       [ 1.02276609e-01],
       [ 8.08534424e-01],
       [ 3.63040353e-01],
       [ 6.93809834e-01],
       [ 1.60959141e+00],
       [ 1.19866038e+00],
       [ 2.73905436e-01],
       [ 1.24922500e-01],
       [ 9.14659501e-01],
       [ 3.25067340e-01],
       [ 1.27747740e-01],
       [ 3.54150259e-01],
       [ 2.71959474e-01],
       [ 1.02884384e+00],
       [ 4.34126207e-01],
       [ 1.42779844e-01],
       [-3.41110307e-02],
       [ 6.11758873e-01],
       [ 2.11189845e-01],
       [ 4.31537995e-01],
       [ 4.14344699e-01],
       [ 8.65283878e-01],
       [ 4.53052981e-01],
       [ 1.88765932e-01],
       [ 2.43740901e+00],
       [ 8.64558383e-01],
       [ 1.99182469e-01],
       [ 2.45531743e-01],
       [ 2.93900328e-01],
       [ 1.92628995e+00],
       [ 1.26326073e+00],
       [ 1.92813578e-01],
       [ 2.54663228e-01],
       [ 9.68805020e-02],
       [ 9.59248059e-01],
       [ 2.07185967e-01],
       [ 1.60621421e-01],
       [ 4.23256954e-01],
       [ 1.09678295e+00],
       [ 6.10013810e-01],
       [ 1.12030046e-01],
       [ 2.88510204e-01],
       [ 2.72570569e-01],
       [ 9.63649181e-02],
       [ 9.39503009e-02],
       [ 9.83317212e-01],
       [ 7.21609794e-01],
       [ 7.74033556e-01],
       [ 1.89856000e+00],
       [ 7.98594998e-01],
       [ 6.05225714e-01],
       [ 3.68278718e-01],
       [ 1.32323211e-01],
       [ 3.31397728e-01],
       [ 5.41261690e-03],
       [ 1.13036549e+00],
       [ 4.43501127e-01],
       [ 5.96664473e-03],
       [ 9.20506508e-02],
       [ 4.14251837e-01],
       [ 1.28875678e-01],
       [ 1.64315476e-01],
       [ 1.27842103e-01],
       [ 4.78130760e-02],
       [ 3.62006883e-01],
       [ 2.37602896e-01],
       [ 2.08282228e-01],
       [ 6.94920211e-02],
       [ 1.27555009e+00],
       [ 2.74898197e-01],
       [ 4.52025715e-01],
       [ 3.45016163e-01],
       [ 1.78199203e-01],
       [ 6.72185172e-01],
       [ 5.35072198e-01],
       [ 1.76274547e-01],
       [ 7.44605995e-01],
       [ 3.78123462e-02],
       [ 1.89605049e-01],
       [ 9.94741438e-01],
       [ 2.06640807e-01],
       [ 9.65239567e-02],
       [ 3.03298658e-01],
       [ 3.48443636e-01],
       [ 6.75940414e-01],
       [ 3.38158228e-01],
       [ 1.27099960e+00],
       [ 5.15921206e-01],
       [ 1.25686390e-01],
       [ 1.07540603e+00],
       [ 1.33067871e-01],
       [ 1.96167566e-01],
       [ 9.66951536e-02],
       [ 1.28191469e-01],
       [ 1.11567695e-01],
       [ 1.22005247e+00],
       [ 5.57691928e-01],
       [ 1.83392685e+00],
       [ 4.97492620e-01],
       [ 2.87249828e-01],
       [ 3.00292417e-02],
       [ 4.11900386e-01],
       [ 8.07389034e-01],
       [ 7.51982062e-01],
       [ 3.63843691e-02],
       [ 1.45943859e+00],
       [ 3.85569973e-01],
       [ 1.38756506e+00],
       [ 1.22585109e-01],
       [ 6.37736281e-01],
       [ 9.47572063e-02],
       [ 2.44481945e-01],
       [ 4.18052889e-01],
       [ 2.60090924e-01],
       [ 2.91451445e-01],
       [-2.09729302e-04],
       [ 3.92382690e-01],
       [ 5.18939459e-01],
       [ 2.03175944e-01],
       [ 1.60631492e-01],
       [ 3.50652805e-01],
       [ 9.19140162e-01],
       [ 8.68779532e-01],
       [ 7.24095996e-01],
       [ 3.10029178e-01],
       [ 1.29625739e-01],
       [ 2.57303474e-01],
       [ 1.01324705e-01],
       [ 3.65362869e-01],
       [ 2.05149097e-01],
       [-5.29690893e-03],
       [ 6.09804779e-01],
       [ 1.41037826e-01],
       [ 9.77299453e-01],
       [ 1.63890390e+00],
       [ 2.76760837e-01],
       [ 6.44853739e-01],
       [ 3.67976140e-01],
       [ 4.93044653e-01],
       [ 2.11063444e-01],
       [ 1.45115347e-01],
       [ 1.18466022e-01],
       [ 4.97089932e-01],
       [ 3.88450311e-01],
       [ 3.13155213e-01],
       [ 3.68819502e-02],
       [ 6.34463805e-01],
       [ 6.20815808e-01],
       [ 2.03699119e-01],
       [ 8.43593259e-02],
       [ 2.58167502e-01],
       [ 5.70153221e-01],
       [ 5.30435347e-01],
       [ 1.51180867e-01],
       [ 1.11726318e-01],
       [ 3.35207810e-01],
       [ 3.98762709e-01],
       [ 6.07340786e-01],
       [ 1.30548983e-01],
       [ 2.28542863e-01],
       [ 6.41331284e-01],
       [ 7.84878099e-02],
       [ 8.35069358e-01],
       [ 4.13284844e-01],
       [ 9.79330848e-02],
       [ 4.94883437e-01],
       [ 1.06169721e+00],
       [ 1.45079793e-02],
       [ 1.01890936e+00],
       [-6.56704445e-04],
       [ 2.90842523e-01],
       [ 8.06613453e-01],
       [ 6.06090822e-01],
       [ 7.84859647e-01],
       [ 4.00058921e-01],
       [ 9.96482079e-02],
       [ 2.67968277e-01],
       [ 5.65152979e-01],
       [ 1.05849965e+00],
       [ 1.92021376e-01],
       [ 4.82862177e-01],
       [ 6.94676786e-02],
       [ 9.58726124e-02],
       [ 6.05380466e-02],
       [ 1.39446206e+00],
       [ 1.30143837e-01],
       [ 1.54399414e+00],
       [ 9.45464215e-02],
       [ 3.70052105e-01],
       [ 9.05621951e-01],
       [ 1.60495447e-01],
       [ 1.24704566e+00],
       [ 1.12768976e-01],
       [ 2.08465474e-01],
       [ 2.03445707e-02],
       [ 3.21509305e-02],
       [ 1.16882548e-01],
       [ 5.30905836e-01],
       [ 1.08098808e-01],
       [ 4.81797508e-01],
       [ 1.76408061e-01],
       [ 1.82362356e-01],
       [-3.38563977e-02],
       [ 2.26369804e-01],
       [ 2.14414651e-01],
       [ 1.53660914e-01],
       [ 4.76741218e-01],
       [ 1.46726964e-01],
       [ 1.69683225e+00],
       [ 4.28961736e-01],
       [ 1.64494656e-01],
       [ 2.71423017e-01],
       [ 5.90279001e-01],
       [ 4.81455809e-01],
       [ 7.51406848e-01],
       [ 2.30406458e-01],
       [-3.40115129e-02],
       [ 6.42664256e-01],
       [ 1.28305356e+00],
       [ 1.08389779e+00],
       [ 2.10602768e-01],
       [ 9.67647631e-02],
       [ 6.39458747e-02],
       [ 3.16221247e-01],
       [ 2.98388362e-01],
       [ 6.04415079e-01],
       [ 8.04192188e-01],
       [ 7.17763024e-01],
       [ 3.38013012e-02],
       [ 7.86931824e-01],
       [ 3.39407620e-02],
       [ 1.33368588e-01],
       [ 1.23574087e+00],
       [ 3.85982486e-01],
       [ 4.60493344e-01],
       [ 1.54635211e-01],
       [ 2.25490403e-01],
       [ 1.16328510e+00],
       [ 3.18477454e-01],
       [-3.36712037e-02],
       [ 1.19655980e-01],
       [ 3.41414683e-01],
       [ 5.95611262e-02],
       [ 3.17751594e-01],
       [ 7.69018878e-01],
       [ 1.20681601e+00],
       [ 2.08186704e-01],
       [ 1.62860098e-01],
       [ 8.03315530e-02],
       [ 5.12474542e-01],
       [ 2.54218405e-01],
       [ 3.21783515e-01],
       [ 8.70380611e-01],
       [ 1.76071476e-01],
       [ 1.12784484e-01],
       [ 8.36232621e-02],
       [ 6.83717908e-01],
       [ 3.07436796e-01],
       [ 7.38887240e-01],
       [ 4.75783741e-01],
       [ 3.44982885e-02],
       [ 2.89850010e-01],
       [ 6.61935853e-04],
       [ 1.80738281e-01],
       [ 2.91235195e-01],
       [ 2.40617219e-01],
       [ 6.45886926e-01],
       [ 1.44049409e-01],
       [ 6.86711233e-01],
       [ 2.86074547e-01],
       [ 1.45023708e+00],
       [ 3.83003203e-01],
       [ 2.19014931e-01],
       [ 1.76847285e-01],
       [ 1.44236742e+00],
       [ 3.44768204e-01],
       [ 1.26864184e+00],
       [ 2.11310268e-01],
       [ 3.51341377e-01],
       [ 3.21842514e-02],
       [ 1.65699204e-01],
       [ 3.66794719e-01],
       [-6.67866141e-04],
       [ 1.88982557e-01],
       [ 1.01299833e-01],
       [ 4.12793922e-01],
       [ 8.47421091e-02],
       [ 2.18504922e-01],
       [ 1.00650815e+00],
       [ 6.19323789e-01],
       [ 3.33974532e-02],
       [ 9.79731463e-02],
       [ 1.86326770e-01],
       [ 2.34380037e-01],
       [ 3.38190128e-01],
       [ 5.96104688e-02],
       [ 2.28405467e-01],
       [ 3.32682283e-01],
       [ 1.61198551e-01],
       [ 2.89393538e-01],
       [ 1.27122396e-01],
       [ 2.22697209e-01],
       [ 1.96508990e-01],
       [ 1.50183164e-01],
       [ 2.78331416e-01],
       [ 1.93316734e-01],
       [ 4.16808001e-01],
       [ 2.03398666e-01],
       [ 1.13794361e-01],
       [ 1.81870518e-01],
       [ 4.61168554e-01],
       [ 1.60669017e-01],
       [ 2.97738144e-02],
       [ 3.26551295e-01],
       [ 9.28530307e-02],
       [ 5.29967528e-01],
       [ 2.35533313e-01],
       [ 3.28702466e-02],
       [ 9.66646525e-02],
       [ 3.20400703e-01],
       [ 3.63629968e-01],
       [ 2.06972174e-01],
       [ 2.36855541e-01],
       [ 3.98711103e-01],
       [ 1.60873262e-01],
       [ 5.78402554e-01],
       [ 2.87439747e-01],
       [ 1.86322483e-01],
       [ 4.15924090e-01],
       [ 3.51337547e-01],
       [ 6.96541031e-02],
       [ 8.52219561e-02],
       [ 4.26286463e-02],
       [ 3.23175705e-01],
       [ 4.74345854e-02],
       [ 2.68705770e-04],
       [ 3.47584712e-01],
       [ 2.85373080e-01],
       [ 9.43517859e-02],
       [ 1.10138150e-01],
       [ 5.61085763e-01],
       [ 3.80888345e-01],
       [ 1.91898877e-01],
       [ 3.68715258e-01],
       [ 6.54435033e-02],
       [ 1.81887637e-01],
       [ 1.10272353e-01],
       [ 3.59737073e-02],
       [ 6.71599614e-01],
       [ 1.70909895e-01],
       [ 2.53240048e-01],
       [ 9.35594328e-02],
       [-7.58257635e-04],
       [ 1.13666776e-01],
       [ 5.74737673e-03],
       [ 3.32159580e-01],
       [ 6.49842219e-02],
       [ 2.08440138e-01],
       [ 4.48992121e-01],
       [ 4.52607600e-01],
       [ 1.65875145e-01],
       [ 1.33305052e-01],
       [ 1.75461149e-01],
       [-3.37186285e-02],
       [ 1.25133805e-01],
       [ 3.36734657e-01],
       [ 1.22888378e-05],
       [ 6.87442318e-03],

In [ ]:
# LR
mae = mean_absolute_error(y_test['ltv_30d_log'], y_pred)
rmse = np.sqrt(mean_squared_error(y_test['ltv_30d_log'], y_pred))
r2 = r2_score(y_test['ltv_30d_log'], y_pred)
print('mae',mae)
print('rmse',rmse)
print('r2',r2)

mae 0.4859991048628692
rmse 0.7413373563166228
r2 0.2153168125385576

In [ ]:
# Base
print('mae_base',mae_base)
print('rmse_base',rmse_base)
print('r2_base',r2_base)

mae_base 0.5457414690186172
rmse_base 1.1345008881805416
r2_base -0.8376900254053452

In [492]:
# slicing

In [494]:
y_test['platform'] = X_test['platform']
y_test['country'] = X_test['country']
y_test

/var/folders/qh/wcp4hdh55d56zf2h540jdxlr0000gn/T/ipykernel_62040/3356009550.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y_test['platform'] = X_test['platform']
/var/folders/qh/wcp4hdh55d56zf2h540jdxlr0000gn/T/ipykernel_62040/3356009550.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y_test['country'] = X_test['country']

      ltv_30d_log platform country
4117     2.395777      ios      CA
4118     0.000000  android      CA
4119     2.217846      web      CA
4120     0.000000      ios      IN
4121     2.739300      web      UK
...           ...      ...     ...
4973     0.000000  android      US
4974     0.000000      web      CA
4975     0.000000      web      UK
4976     0.000000  android      US
4977     0.000000  android      UK

[861 rows x 3 columns]

In [497]:
y_test['pred'] = y_pred
y_test

/var/folders/qh/wcp4hdh55d56zf2h540jdxlr0000gn/T/ipykernel_62040/1681209051.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y_test['pred'] = y_pred

      ltv_30d_log platform country      pred
4117     2.395777      ios      CA  0.111631
4118     0.000000  android      CA  0.070001
4119     2.217846      web      CA  1.152273
4120     0.000000      ios      IN  0.095634
4121     2.739300      web      UK  0.767343
...           ...      ...     ...       ...
4973     0.000000  android      US -0.027566
4974     0.000000      web      CA  0.033964
4975     0.000000      web      UK  0.160915
4976     0.000000  android      US -0.027795
4977     0.000000  android      UK  0.005932

[861 rows x 4 columns]

In [500]:
cohort_platform = y_test.groupby(['platform']).apply(lambda x: pd.Series({'mae': mean_absolute_error(x['ltv_30d_log'],x['pred']), 'rmse': np.sqrt(mean_squared_error(x['ltv_30d_log'],x['pred'])), 'r2': r2_score(x['ltv_30d_log'],x['pred'])}))
cohort_platform

/var/folders/qh/wcp4hdh55d56zf2h540jdxlr0000gn/T/ipykernel_62040/3361381138.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  cohort_platform = y_test.groupby(['platform']).apply(lambda x: pd.Series({'mae': mean_absolute_error(x['ltv_30d_log'],x['pred']), 'rmse': np.sqrt(mean_squared_error(x['ltv_30d_log'],x['pred'])), 'r2': r2_score(x['ltv_30d_log'],x['pred'])}))

               mae      rmse        r2
platform
android   0.438971  0.707327  0.182608
ios       0.514561  0.777499  0.250249
web       0.498738  0.732795  0.189026

In [501]:
cohort_country = y_test.groupby(['country']).apply(lambda x: pd.Series({'mae': mean_absolute_error(x['ltv_30d_log'],x['pred']), 'rmse': np.sqrt(mean_squared_error(x['ltv_30d_log'],x['pred'])), 'r2': r2_score(x['ltv_30d_log'],x['pred'])}))
cohort_country

/var/folders/qh/wcp4hdh55d56zf2h540jdxlr0000gn/T/ipykernel_62040/2250736273.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  cohort_country = y_test.groupby(['country']).apply(lambda x: pd.Series({'mae': mean_absolute_error(x['ltv_30d_log'],x['pred']), 'rmse': np.sqrt(mean_squared_error(x['ltv_30d_log'],x['pred'])), 'r2': r2_score(x['ltv_30d_log'],x['pred'])}))

              mae      rmse        r2
country
CA       0.420179  0.633508  0.230377
IN       0.533562  0.812387  0.163789
UK       0.489926  0.741450  0.259805
US       0.490794  0.752006  0.201236

In [ ]:
# do aggregation in python

In [502]:
df

,user_id,date,sessions,play_time,spend,creator_id,platform,country
0,0,2025-01-07,1,11.888733,0.000000,373,ios,US
1,0,2025-01-08,1,19.548648,0.000000,492,ios,US
2,0,2025-01-10,3,16.037809,0.000000,475,ios,US
3,0,2025-01-13,1,16.777639,0.000000,563,ios,US
4,0,2025-01-14,3,35.272466,0.000000,274,ios,US
...,...,...,...,...,...,...,...,...
70553,4999,2025-01-26,3,32.599466,0.000000,688,web,IN
70554,4999,2025-01-27,2,16.721781,0.000000,450,web,IN
70555,4999,2025-01-28,2,18.727887,8.605824,83,web,IN
70556,4999,2025-01-29,2,18.667530,0.000000,767,web,IN
70557,4999,2025-01-30,3,57.009896,2.185158,560,web,IN

In [506]:
df_test = df.copy(deep = True)

In [511]:
df_test['join_date'] = df_test.groupby(['user_id'])['date'].transform('min')

In [513]:
df_test['day_diff'] = (df_test['date'] - df_test['join_date']).dt.days

In [514]:
df_test

,user_id,date,sessions,play_time,spend,creator_id,platform,country,join_date,day_diff
0,0,2025-01-07,1,11.888733,0.000000,373,ios,US,2025-01-07,0
1,0,2025-01-08,1,19.548648,0.000000,492,ios,US,2025-01-07,1
2,0,2025-01-10,3,16.037809,0.000000,475,ios,US,2025-01-07,3
3,0,2025-01-13,1,16.777639,0.000000,563,ios,US,2025-01-07,6
4,0,2025-01-14,3,35.272466,0.000000,274,ios,US,2025-01-07,7
...,...,...,...,...,...,...,...,...,...,...
70553,4999,2025-01-26,3,32.599466,0.000000,688,web,IN,2025-01-11,15
70554,4999,2025-01-27,2,16.721781,0.000000,450,web,IN,2025-01-11,16
70555,4999,2025-01-28,2,18.727887,8.605824,83,web,IN,2025-01-11,17
70556,4999,2025-01-29,2,18.667530,0.000000,767,web,IN,2025-01-11,18
70557,4999,2025-01-30,3,57.009896,2.185158,560,web,IN,2025-01-11,19

In [520]:
df_test_grouped = df_test.groupby(['user_id']).apply(lambda x: pd.Series({'total_session': x[(0<=x['day_diff'])&(x['day_diff']<=6)]['sessions'].sum(),
'nunique_creator': x['creator_id'].nunique()}))

/var/folders/qh/wcp4hdh55d56zf2h540jdxlr0000gn/T/ipykernel_62040/2726157698.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_test_grouped = df_test.groupby(['user_id']).apply(lambda x: pd.Series({'total_session': x[(0<=x['day_diff'])&(x['day_diff']<=6)]['sessions'].sum(),

In [521]:
df_test_grouped

         total_session  nunique_creator
user_id
0                    6               19
1                    2                2
2                    7               19
3                    3                6
4                    4                6
...                ...              ...
4995                 7               16
4996                 6               16
4997                 7               15
4998                17               26
4999                27               20

[4978 rows x 2 columns]

## Practice 5

In [522]:
df

,user_id,date,sessions,play_time,spend,creator_id,platform,country
0,0,2025-01-07,1,11.888733,0.000000,373,ios,US
1,0,2025-01-08,1,19.548648,0.000000,492,ios,US
2,0,2025-01-10,3,16.037809,0.000000,475,ios,US
3,0,2025-01-13,1,16.777639,0.000000,563,ios,US
4,0,2025-01-14,3,35.272466,0.000000,274,ios,US
...,...,...,...,...,...,...,...,...
70553,4999,2025-01-26,3,32.599466,0.000000,688,web,IN
70554,4999,2025-01-27,2,16.721781,0.000000,450,web,IN
70555,4999,2025-01-28,2,18.727887,8.605824,83,web,IN
70556,4999,2025-01-29,2,18.667530,0.000000,767,web,IN
70557,4999,2025-01-30,3,57.009896,2.185158,560,web,IN

In [ ]:
## feature day 0-6
    # total spend 7d, total play time 7d, total session in 7d
    # d1 retetion, active days in 7d
    # number of unique creator engaged
    # platform, country

## target day 7-29
    # total spend d7-29

In [524]:
df['join_date'] = df.groupby(['user_id'])['date'].transform('min')

In [526]:
df['day_diff'] = (df['date'] - df['join_date']).dt.days

In [527]:
df.head()

,user_id,date,sessions,play_time,spend,creator_id,platform,country,join_date,day_diff
0,0,2025-01-07,1,11.888733,0.0,373,ios,US,2025-01-07,0
1,0,2025-01-08,1,19.548648,0.0,492,ios,US,2025-01-07,1
2,0,2025-01-10,3,16.037809,0.0,475,ios,US,2025-01-07,3
3,0,2025-01-13,1,16.777639,0.0,563,ios,US,2025-01-07,6
4,0,2025-01-14,3,35.272466,0.0,274,ios,US,2025-01-07,7

In [617]:
def agg(r):
    return pd.Series({'total_spend_7d': r[r['day_diff']<=6]['spend'].sum(),
    'total_playtime_7d': r[r['day_diff']<=6]['play_time'].sum(),
    'total_sessions_7d': r[r['day_diff']<=6]['sessions'].sum(),
    'd1_retention':int((r['day_diff'] == 1).any()),
    'active_days_7d': r[r['day_diff'] <= 6]['date'].nunique(),
    'n_creators': r[r['day_diff'] <= 6]['creator_id'].nunique(),
    'platform':r['platform'].max(),
    'country':r['country'].max(),
    'join_date':r['join_date'].min(),
    'ltd_30d':r[(r['day_diff']>=7)&(r['day_diff']<=29)]['spend'].sum()}
    )

In [618]:
df_processed = df.groupby(['user_id']).apply(agg)

/var/folders/qh/wcp4hdh55d56zf2h540jdxlr0000gn/T/ipykernel_62040/3191654876.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_processed = df.groupby(['user_id']).apply(agg)

In [547]:
df_processed = df_processed.reset_index()

In [548]:
df_processed.head()

,user_id,total_spend_7d,total_playtime_7d,total_sessions_7d,d1_retention,active_days_7d,n_creators,platform,country,join_date,ltd_30d
0,0,0.0,64.252830,6,1,19,19,ios,US,2025-01-07,0.0
1,1,0.0,14.305001,2,0,2,2,ios,US,2025-01-26,0.0
2,2,0.0,102.255638,7,0,20,19,ios,UK,2025-01-02,0.0
3,3,0.0,31.861878,3,0,6,6,android,IN,2025-01-19,0.0
4,4,0.0,32.449207,4,1,6,6,android,CA,2025-02-05,0.0

In [549]:
df_processed.describe(include = 'all')

,user_id,total_spend_7d,total_playtime_7d,total_sessions_7d,d1_retention,active_days_7d,n_creators,platform,country,join_date,ltd_30d
count,4978.000000,4978.000000,4978.000000,4978.000000,4978.000000,4978.000000,4978.000000,4978,4978,4978,4978.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,4,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,web,US,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1716,1277,NaN,NaN
mean,2500.483126,0.945910,114.566627,9.167738,0.588188,14.173965,14.032543,NaN,NaN,2025-01-16 15:37:31.988750336,1.915623
min,0.000000,0.000000,5.073930,1.000000,0.000000,1.000000,1.000000,NaN,NaN,2025-01-01 00:00:00,0.000000
25%,1251.250000,0.000000,42.178059,3.000000,0.000000,6.250000,6.000000,NaN,NaN,2025-01-09 00:00:00,0.000000
50%,2499.500000,0.000000,77.171421,6.000000,1.000000,11.000000,11.000000,NaN,NaN,2025-01-17 00:00:00,0.000000
75%,3751.750000,0.000000,152.329670,12.000000,1.000000,19.000000,19.000000,NaN,NaN,2025-01-24 00:00:00,0.000000
max,4999.000000,44.112869,798.519567,55.000000,1.000000,52.000000,51.000000,NaN,NaN,2025-02-17 00:00:00,55.597312
std,1443.721875,3.171391,105.341417,8.237568,0.492211,9.976095,9.794480,NaN,NaN,NaN,5.114650

In [550]:
df_processed['d1_retention'] = df_processed['d1_retention'].astype('object')

In [553]:
num_cols = df_processed.select_dtypes(include = 'number').columns

In [554]:
df_processed[num_cols].skew()

user_id             -0.000363
total_spend_7d       5.064800
total_playtime_7d    1.819218
total_sessions_7d    1.721187
active_days_7d       1.055890
n_creators           1.037530
ltd_30d              3.955807
dtype: float64

In [556]:
df_processed['ltd_30d'] = np.log1p(df_processed['ltd_30d'])

In [557]:
df_processed['ltd_30d'].skew()

np.float64(1.845520596717507)

In [ ]:
# split training and testing by join date

In [560]:
df_processed = df_processed.sort_values( by = 'join_date').reset_index(drop = True)
df_processed

,index,user_id,total_spend_7d,total_playtime_7d,total_sessions_7d,d1_retention,active_days_7d,n_creators,platform,country,join_date,ltd_30d
0,2488,2499,0.000000,80.359712,7,1,6,6,web,UK,2025-01-01,0.000000
1,531,534,0.000000,244.550606,20,1,13,13,android,US,2025-01-01,0.000000
2,1513,1522,0.000000,68.261758,6,0,4,4,web,UK,2025-01-01,0.000000
3,4376,4397,0.636427,94.325682,10,1,32,31,web,IN,2025-01-01,2.162753
4,157,157,0.380716,86.734342,7,1,15,15,web,IN,2025-01-01,1.091638
...,...,...,...,...,...,...,...,...,...,...,...,...
4973,2735,2746,0.000000,16.979310,1,0,3,3,android,US,2025-02-13,0.000000
4974,2538,2549,0.000000,19.540930,1,0,1,1,web,CA,2025-02-13,0.000000
4975,3800,3819,0.000000,13.558387,1,0,1,1,android,US,2025-02-14,0.000000
4976,446,448,0.000000,38.767414,3,0,5,5,web,UK,2025-02-14,0.000000
4977,3076,3089,0.000000,16.229255,1,0,2,2,android,UK,2025-02-17,0.000000

In [561]:
idx_cutoff = int(df_processed.shape[0]*0.8)
idx_cutoff

3982

In [562]:
date_cutoff = df_processed.loc[idx_cutoff]['join_date']
date_cutoff

Timestamp('2025-01-26 00:00:00')

In [563]:
train = df_processed[df_processed['join_date']<=date_cutoff]
test = df_processed[df_processed['join_date']>date_cutoff]

In [570]:
train.shape[0], test.shape[0]

(4117, 861)

In [571]:
df_processed.columns

Index(['index', 'user_id', 'total_spend_7d', 'total_playtime_7d',
       'total_sessions_7d', 'd1_retention', 'active_days_7d', 'n_creators',
       'platform', 'country', 'join_date', 'ltd_30d'],
      dtype='object')

In [572]:
features = ['total_spend_7d', 'total_playtime_7d',
       'total_sessions_7d', 'd1_retention', 'active_days_7d', 'n_creators',
       'platform', 'country']
target = ['ltd_30d']

In [573]:
X_train = train[features]
y_train = train[target]

X_test = test[features]
y_test = test[target]

In [574]:
# baseline  - average

In [575]:
y_pred_base = X_test['total_spend_7d']/7*(30-7)

In [576]:
y_pred_base = np.log1p(y_pred_base)
y_pred_base

4117    0.000000
4118    0.000000
4119    0.000000
4120    0.000000
4121    1.795792
          ...
4973    0.000000
4974    0.000000
4975    0.000000
4976    0.000000
4977    0.000000
Name: total_spend_7d, Length: 861, dtype: float64

In [577]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [578]:
mae_bae = mean_absolute_error(y_test['ltd_30d'], y_pred_base)
rmse_bae = np.sqrt(mean_squared_error(y_test['ltd_30d'], y_pred_base))
r2_bae = r2_score(y_test['ltd_30d'], y_pred_base)

In [581]:
print('mae_bae',mae_bae)
print('rmse_bae',rmse_bae)
print('r2_bae',r2_bae)

mae_bae 0.5457414690186173
rmse_bae 1.1345008881805416
r2_bae -0.8376900254053452

In [582]:
# feature engineering

In [585]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [584]:
X_train

,total_spend_7d,total_playtime_7d,total_sessions_7d,d1_retention,active_days_7d,n_creators,platform,country
0,0.000000,80.359712,7,1,6,6,web,UK
1,0.000000,244.550606,20,1,13,13,android,US
2,0.000000,68.261758,6,0,4,4,web,UK
3,0.636427,94.325682,10,1,32,31,web,IN
4,0.380716,86.734342,7,1,15,15,web,IN
...,...,...,...,...,...,...,...,...
4112,0.000000,101.019235,7,1,20,20,ios,UK
4113,0.000000,86.225942,6,0,17,17,android,UK
4114,7.242975,521.915123,45,1,51,50,ios,IN
4115,0.000000,55.973825,6,1,6,6,android,CA
4116,0.000000,15.541008,1,0,3,3,android,UK

In [ ]:
num_pipeline = Pipeline([
    ('norm', StandardScaler())
])

In [586]:
col_pipeline = Pipeline([
    ('onehot', OneHotEncoder(handle_unknown = 'ignore', sparse_output = False))
])

In [587]:
num_pipeline

Pipeline(steps=[('norm', StandardScaler())])

In [588]:
col_pipeline

Pipeline(steps=[('onehot',
                 OneHotEncoder(handle_unknown='ignore', sparse_output=False))])

In [592]:
preprocessor = ColumnTransformer([
    ('num',num_pipeline, ['total_spend_7d', 'total_playtime_7d', 'total_sessions_7d',
       'active_days_7d', 'n_creators']),
       ('cat', col_pipeline, ['d1_retention','platform','country'])
],remainder = 'drop')

In [597]:
from sklearn.linear_model import LinearRegression

In [598]:
model = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [599]:
model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('norm',
                                                                   StandardScaler())]),
                                                  ['total_spend_7d',
                                                   'total_playtime_7d',
                                                   'total_sessions_7d',
                                                   'active_days_7d',
                                                   'n_creators']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['d1_retention', 'platform',
                                                   'country'])])),
                ('regressor', LinearRegression())])

In [600]:
model.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('norm',
                                                                   StandardScaler())]),
                                                  ['total_spend_7d',
                                                   'total_playtime_7d',
                                                   'total_sessions_7d',
                                                   'active_days_7d',
                                                   'n_creators']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['d1_retention', 'platform',
                                                   'country'])])),
                ('regressor', LinearRegression())])

In [601]:
y_pred = model.predict(X_test)

In [602]:
y_pred

array([[ 5.60781467e-02],
       [ 2.05334886e-01],
       [ 5.14600199e-01],
       [-1.43658823e-01],
       [ 4.73558922e-01],
       [ 1.42789916e+00],
       [-2.01818416e-01],
       [ 5.13729057e-01],
       [ 4.18042713e-01],
       [-3.04420800e-02],
       [ 7.87519916e-01],
       [ 5.73582359e-01],
       [ 9.59947906e-02],
       [ 1.04139201e+00],
       [ 1.32047848e+00],
       [ 6.04020291e-02],
       [ 3.96027347e-01],
       [ 1.96516960e+00],
       [ 6.97831152e-01],
       [ 1.98595764e-01],
       [ 2.91226517e-01],
       [ 5.34528324e-01],
       [ 1.18093515e+00],
       [ 4.26033535e-01],
       [ 6.64628261e-01],
       [ 1.09929330e+00],
       [-5.29978893e-03],
       [ 1.00890507e+00],
       [ 1.91369425e+00],
       [ 4.78767394e-01],
       [ 1.43835198e-01],
       [ 2.29986569e-01],
       [ 1.70652853e+00],
       [ 1.72809743e-02],
       [ 5.25290715e-01],
       [ 1.74426520e-01],
       [ 1.24175696e-01],
       [ 8.53325882e-01],
       [ 1.89548296e-01],
       [ 2.88217225e-01],
       [ 2.24912822e-01],
       [ 9.45962881e-01],
       [ 5.21948174e-01],
       [-2.17085565e-02],
       [ 1.07113827e+00],
       [ 1.66784001e-01],
       [ 9.85895532e-01],
       [ 1.55094468e-01],
       [ 1.04917698e-01],
       [ 1.10637139e-01],
       [ 1.94443869e-01],
       [ 6.09475061e-01],
       [ 2.73031467e-02],
       [ 2.12578745e-01],
       [ 1.03258491e+00],
       [ 1.80055251e+00],
       [ 4.44990138e-01],
       [ 1.72600549e+00],
       [ 1.51747931e-01],
       [ 5.78283334e-01],
       [ 8.58431673e-01],
       [ 2.11023953e-01],
       [ 8.58722900e-02],
       [ 1.21147556e-01],
       [-9.57525540e-02],
       [ 9.77687549e-01],
       [ 7.11452532e-01],
       [ 2.50613674e-01],
       [ 4.14928791e-01],
       [ 7.72961913e-01],
       [ 1.23140191e-01],
       [ 1.06022257e+00],
       [ 1.60791213e-01],
       [ 3.92511728e-01],
       [-4.56817106e-02],
       [ 3.14266283e-01],
       [ 3.52157138e-01],
       [ 1.35977256e-01],
       [ 2.29955428e-01],
       [ 1.56578149e+00],
       [-8.55419039e-03],
       [-1.35283611e-01],
       [ 6.63506774e-02],
       [-7.75536562e-02],
       [ 1.03401964e+00],
       [-5.27469808e-02],
       [ 3.54649517e-01],
       [ 1.75557749e+00],
       [ 1.33168960e-01],
       [ 3.49360295e-01],
       [ 1.04887067e-02],
       [ 1.34759662e+00],
       [ 5.23395730e-01],
       [ 8.54711916e-01],
       [ 5.34717352e-02],
       [-7.84065355e-02],
       [ 2.41470717e-01],
       [-8.92246945e-03],
       [ 9.98510308e-02],
       [ 1.95844218e-01],
       [-1.36680729e-01],
       [ 2.04515988e-01],
       [ 1.25025165e-01],
       [ 6.47403248e-02],
       [-1.22845960e-01],
       [ 9.17935870e-01],
       [ 1.46958753e-01],
       [ 8.44464217e-01],
       [-9.57197084e-02],
       [ 2.46490848e+00],
       [ 4.08650085e-01],
       [ 1.44427393e-02],
       [ 1.14737984e+00],
       [-1.49680953e-01],
       [ 4.13931940e-03],
       [ 2.60545132e-01],
       [ 4.50871185e-01],
       [ 2.66410701e-01],
       [ 5.32027423e-01],
       [ 1.54394545e+00],
       [ 8.71612393e-01],
       [ 1.35256097e+00],
       [ 1.63153710e-01],
       [ 1.03880520e+00],
       [ 6.21991157e-01],
       [ 1.58865474e-01],
       [ 1.94362207e-02],
       [ 1.79820024e+00],
       [ 1.30399868e+00],
       [ 4.04544533e-01],
       [ 4.70576365e-01],
       [ 4.90555957e-02],
       [ 2.70178042e-01],
       [ 6.88329191e-01],
       [ 2.11118848e-01],
       [ 3.94917384e-01],
       [ 4.27588381e-01],
       [ 9.06864474e-02],
       [ 3.27597413e-01],
       [ 8.32482605e-02],
       [ 2.36256381e-01],
       [ 4.96189604e-01],
       [ 2.60138967e-01],
       [ 7.18621820e-01],
       [ 1.35683862e+00],
       [ 5.84718642e-02],
       [-1.28685169e-01],
       [ 3.05009981e-01],
       [ 1.45879505e+00],
       [ 4.43225533e-01],
       [ 1.40927630e+00],
       [ 6.63966416e-01],
       [ 1.74327126e-02],
       [ 5.32609732e-01],
       [ 1.03446186e+00],
       [ 5.16551478e-02],
       [ 6.89023269e-01],
       [-3.47364262e-02],
       [ 2.21859155e-01],
       [-7.33417637e-02],
       [ 3.11758010e-01],
       [-1.07579839e-01],
       [-3.51037442e-02],
       [ 2.10018993e-01],
       [ 1.97274768e-01],
       [ 1.32131689e-01],
       [-9.60115895e-02],
       [ 1.37805382e-01],
       [ 1.00800716e+00],
       [ 4.41195234e-01],
       [ 3.50375018e-01],
       [-2.89740247e-02],
       [ 8.87046466e-01],
       [ 3.58219642e-01],
       [ 1.47266037e-01],
       [ 2.58355539e-01],
       [-6.94865513e-02],
       [ 2.45105358e-01],
       [ 5.01725164e-01],
       [ 4.33418389e-01],
       [-1.41663625e-01],
       [ 4.26398753e-01],
       [ 3.00894032e-01],
       [ 3.45656448e-01],
       [ 1.20239790e-01],
       [ 8.74593370e-04],
       [ 7.55539549e-02],
       [ 6.66714323e-01],
       [-7.63544587e-02],
       [ 2.89211518e-01],
       [ 1.05615543e-01],
       [ 1.34958230e+00],
       [ 4.83405147e-01],
       [ 1.87586430e-01],
       [-1.02196527e-01],
       [ 4.28246150e-01],
       [ 2.98586928e-01],
       [ 4.33069205e-02],
       [ 5.49925154e-01],
       [ 7.74355711e-01],
       [ 5.28658491e-01],
       [ 2.21843926e-01],
       [-1.55989506e-01],
       [ 1.15909956e+00],
       [ 4.02768882e-01],
       [ 3.95620797e-01],
       [ 2.58021675e-01],
       [-2.26857429e-02],
       [ 8.54261178e-01],
       [ 5.26405162e-01],
       [ 1.95576794e-01],
       [ 9.77194680e-01],
       [ 1.20990354e+00],
       [ 1.23546840e+00],
       [ 2.65536005e-01],
       [ 2.84128189e-01],
       [-2.33445516e-02],
       [ 2.97430852e-02],
       [ 4.95297179e-02],
       [ 4.18455191e-01],
       [ 3.14287599e-01],
       [ 7.33968068e-01],
       [ 1.82424559e-01],
       [ 2.09266859e+00],
       [ 2.81482423e-01],
       [ 7.53408158e-01],
       [ 3.22123323e-01],
       [ 1.13417123e+00],
       [ 7.85511029e-01],
       [-5.34294522e-02],
       [-4.98109222e-02],
       [ 7.38991784e-02],
       [ 8.08509973e-01],
       [-9.22929962e-02],
       [ 4.34079072e-01],
       [ 1.41927709e+00],
       [ 7.64379518e-01],
       [ 6.10446637e-01],
       [ 3.89669751e-01],
       [ 1.64401813e-01],
       [ 8.98290555e-01],
       [ 2.10838849e-01],
       [ 2.18865611e-01],
       [ 7.71009391e-01],
       [ 3.61691716e-02],
       [ 6.60267981e-01],
       [ 1.38978101e+00],
       [ 3.17088468e-01],
       [ 3.91086590e-01],
       [ 1.95075737e-02],
       [-7.69173568e-02],
       [ 1.38922214e+00],
       [-2.28765510e-02],
       [-3.85015014e-02],
       [ 3.21464362e-01],
       [-1.03576280e-01],
       [ 5.25104792e-01],
       [ 6.42875128e-01],
       [ 1.17554886e+00],
       [ 4.33376357e-01],
       [ 9.22396694e-01],
       [ 3.37951989e-01],
       [-1.07203443e-01],
       [-1.57470142e-01],
       [ 3.92491870e-01],
       [ 4.92174769e-02],
       [ 3.60474576e-02],
       [ 1.63356368e+00],
       [ 2.45592556e-01],
       [ 5.21707346e-01],
       [ 4.53202314e-01],
       [ 3.81006233e-02],
       [ 2.44810810e-02],
       [ 9.27421146e-01],
       [ 8.16230840e-01],
       [ 1.49314990e+00],
       [ 6.52607813e-01],
       [ 1.97339548e-01],
       [ 5.53052846e-01],
       [-2.28612868e-01],
       [ 1.34880493e-01],
       [ 1.40411542e-01],
       [ 1.73668920e-01],
       [ 2.08963880e+00],
       [-5.87123992e-02],
       [ 5.82698495e-01],
       [ 3.22758528e-01],
       [ 1.30117682e-01],
       [ 1.23494108e-01],
       [ 3.55157723e-01],
       [ 1.41810808e-01],
       [ 8.43805738e-01],
       [ 3.85920052e-02],
       [ 7.33089922e-01],
       [ 3.17718053e-01],
       [ 8.97449236e-02],
       [ 4.23140692e-01],
       [ 2.87914933e-02],
       [ 1.81416651e-01],
       [ 1.38683308e-01],
       [ 5.66839557e-01],
       [ 7.98308284e-02],
       [-1.71347403e-02],
       [ 2.13893281e-01],
       [ 2.08006169e+00],
       [ 8.65642565e-01],
       [ 2.02234651e-01],
       [ 1.88239786e-01],
       [ 5.04587406e-02],
       [-1.33772804e-01],
       [-6.26789096e-02],
       [ 2.35908761e-01],
       [ 3.17700515e-01],
       [ 1.13535527e+00],
       [-1.08019482e-01],
       [ 1.09103465e-02],
       [-9.58792109e-02],
       [ 1.25331952e+00],
       [ 1.41035655e+00],
       [ 8.77777491e-01],
       [-1.08176667e-01],
       [ 1.22580682e+00],
       [ 1.21407801e-01],
       [ 1.11670618e+00],
       [ 1.06427501e+00],
       [ 4.84691822e-01],
       [ 7.38972571e-01],
       [ 4.75678916e-01],
       [-6.70821370e-02],
       [ 6.69873357e-01],
       [ 4.73614251e-01],
       [-1.76696282e-01],
       [-1.37239250e-01],
       [-3.29306655e-02],
       [ 2.26879882e-01],
       [ 6.84320319e-01],
       [ 4.39490922e-01],
       [ 8.05094628e-02],
       [ 4.50027709e-03],
       [ 5.95305551e-01],
       [ 5.03996846e-01],
       [ 1.14205229e-01],
       [ 1.36948659e-01],
       [ 1.02848053e+00],
       [-7.09554349e-02],
       [ 5.21282950e-01],
       [ 8.43258901e-01],
       [ 2.45616648e-01],
       [ 2.81793123e+00],
       [ 1.75260579e+00],
       [-1.15708221e-01],
       [ 2.12204103e-02],
       [ 1.54591285e-01],
       [ 1.36955303e+00],
       [ 9.18797170e-01],
       [ 3.08031770e-01],
       [ 3.28503714e-01],
       [ 1.38829940e-02],
       [ 4.27076525e-01],
       [ 2.84802936e-01],
       [ 1.34219383e-01],
       [ 2.34756922e-01],
       [ 1.14554021e+00],
       [ 4.59853574e-01],
       [ 1.02778881e+00],
       [ 2.00965604e-01],
       [-6.56754656e-02],
       [ 6.48764446e-02],
       [-1.99006691e-03],
       [ 1.62329848e+00],
       [ 6.39970184e-01],
       [ 1.75496123e+00],
       [ 1.03497619e+00],
       [ 7.29495763e-02],
       [ 8.75283922e-02],
       [ 2.93334792e-01],
       [-3.47217870e-02],
       [ 8.49466999e-01],
       [ 6.98235044e-02],
       [ 1.37020416e+00],
       [ 2.72147956e-01],
       [ 1.75567905e+00],
       [ 7.27330828e-02],
       [ 9.02752306e-01],
       [ 1.84443923e-01],
       [ 2.83425955e-01],
       [ 6.34007121e-01],
       [ 9.25539527e-02],
       [ 8.94613986e-02],
       [-1.97547792e-02],
       [ 2.24974458e-01],
       [ 4.31943348e-01],
       [ 1.31627958e+00],
       [ 3.45567949e-01],
       [ 3.79121602e-01],
       [ 4.96221525e-01],
       [ 6.40087841e-02],
       [ 1.90149475e-01],
       [ 3.65535727e-01],
       [ 2.84166945e-01],
       [ 8.86579947e-01],
       [-1.50403408e-01],
       [-3.74525780e-02],
       [ 1.48092753e+00],
       [ 5.93575284e-01],
       [ 1.38336395e-02],
       [-1.20570214e-02],
       [ 3.62404737e-01],
       [ 4.64593595e-01],
       [ 4.81761830e-01],
       [ 1.19150877e+00],
       [ 6.78780042e-01],
       [ 1.50097894e+00],
       [ 4.11950385e-01],
       [ 4.82936107e-01],
       [ 3.51898638e-02],
       [ 1.06015252e+00],
       [-4.99307445e-02],
       [ 5.56429186e-01],
       [ 1.37693139e-01],
       [ 1.19825967e+00],
       [ 9.89522579e-04],
       [ 3.40528374e-01],
       [ 4.36120500e-01],
       [ 9.84499450e-01],
       [ 3.94603001e-01],
       [ 3.24590601e-01],
       [ 2.24157971e-02],
       [ 1.16829242e-02],
       [ 8.86093579e-02],
       [-1.93301725e-02],
       [ 2.83101089e-01],
       [ 1.23540822e-01],
       [ 1.24116218e-01],
       [ 3.18530235e-01],
       [ 3.51435930e-01],
       [ 6.82890993e-01],
       [ 5.68530901e-01],
       [ 3.53348139e-01],
       [ 3.16715226e-01],
       [ 1.50922585e+00],
       [-9.86538825e-02],
       [ 2.58682756e-02],
       [ 5.78889838e-01],
       [ 5.71026038e-01],
       [ 1.17863448e+00],
       [ 9.36263395e-01],
       [ 3.78987410e-01],
       [ 6.37994136e-01],
       [ 4.02457459e-01],
       [-1.16462281e-01],
       [ 1.36031834e-01],
       [ 9.87383382e-02],
       [ 6.31840518e-01],
       [ 1.13556951e-01],
       [ 3.31726479e-01],
       [ 4.87917135e-01],
       [ 1.34712811e-01],
       [ 1.54368360e+00],
       [-5.84334474e-02],
       [ 5.13739184e-01],
       [ 1.10406935e+00],
       [ 3.59873954e-01],
       [ 2.10288660e-01],
       [ 1.00249131e+00],
       [ 1.42812123e+00],
       [ 8.63467621e-01],
       [ 2.90060514e-01],
       [ 2.17682016e-02],
       [ 1.55219013e+00],
       [-1.21494530e-01],
       [ 3.62590056e-02],
       [ 1.35011973e-02],
       [ 1.85334985e-01],
       [ 9.12523094e-01],
       [-7.23800703e-02],
       [ 1.65857291e-01],
       [ 8.01790066e-01],
       [ 9.37963285e-01],
       [ 8.10166672e-01],
       [ 7.92880550e-01],
       [ 1.31297612e+00],
       [ 4.40298663e-01],
       [-1.04203790e-01],
       [ 1.10360126e+00],
       [-3.84702347e-02],
       [ 4.77858405e-01],
       [ 6.21249649e-02],
       [ 3.13545276e-01],
       [ 1.59482065e-01],
       [ 7.75049549e-02],
       [ 5.53182930e-01],
       [ 4.54096678e-01],
       [ 1.30686784e+00],
       [ 8.34963694e-02],
       [-6.12644211e-02],
       [ 7.45603484e-01],
       [ 3.56207623e-01],
       [-7.97292176e-02],
       [ 7.19847719e-01],
       [ 3.04981507e-01],
       [ 1.08537455e+00],
       [ 5.60288617e-02],
       [ 4.82078261e-01],
       [ 3.82669393e-01],
       [ 1.08159288e-01],
       [ 8.63295450e-01],
       [-6.27711537e-02],
       [ 1.10459375e-01],
       [ 5.01885510e-01],
       [ 4.23867699e-01],
       [ 7.69016224e-02],
       [ 1.72455401e-01],
       [ 6.66953379e-01],
       [ 6.88770163e-01],
       [-1.62337111e-01],
       [ 9.20375849e-01],
       [-2.15259659e-01],
       [ 4.70084919e-02],
       [ 1.61163238e+00],
       [ 3.66146036e-01],
       [ 3.26643401e-01],
       [ 5.14260103e-01],
       [ 3.47445814e-01],
       [ 7.27355503e-01],
       [ 3.88729150e-01],
       [-2.28626577e-01],
       [ 5.83094062e-01],
       [ 1.15741277e-02],
       [ 9.74781847e-02],
       [ 1.27705391e+00],
       [ 1.12581888e+00],
       [ 5.51242100e-01],
       [ 4.26739632e-01],
       [ 1.56957436e-01],
       [-9.29201237e-03],
       [ 7.05827215e-02],
       [ 2.05866484e-01],
       [ 4.52187704e-02],
       [ 5.82272645e-01],
       [-2.15798246e-02],
       [ 2.28687419e+00],
       [ 4.37194302e-01],
       [ 4.40866259e-02],
       [ 6.16328192e-01],
       [ 9.58874576e-01],
       [ 7.35369712e-01],
       [ 1.48298614e+00],
       [ 4.32632015e-01],
       [ 7.29394499e-01],
       [ 9.97891369e-01],
       [ 7.79223508e-01],
       [ 7.52177469e-02],
       [ 1.38669729e-02],
       [-6.21303476e-02],
       [ 3.59617210e-01],
       [ 8.69798003e-01],
       [ 3.73059739e-02],
       [ 4.75424467e-01],
       [ 3.08986792e-01],
       [ 1.16946016e+00],
       [ 6.42441649e-01],
       [ 1.72655278e+00],
       [ 3.58501062e-01],
       [ 2.37365160e-01],
       [-5.94706580e-02],
       [ 7.97740682e-02],
       [ 3.15858670e-01],
       [ 3.02143355e-02],
       [ 2.48564570e-01],
       [ 1.04863045e-01],
       [ 5.32395212e-01],
       [ 9.35020423e-02],
       [ 6.77757712e-01],
       [ 1.02706800e+00],
       [ 1.12290701e+00],
       [ 6.33942368e-02],
       [ 1.17319499e-01],
       [ 3.19078589e-01],
       [-3.10464893e-02],
       [ 1.62213146e-01],
       [-9.93310545e-02],
       [ 1.92688507e-01],
       [ 1.02235529e-01],
       [ 1.35882079e+00],
       [ 4.14643424e-01],
       [ 7.13055898e-02],
       [ 2.02199431e-02],
       [ 6.98562250e-01],
       [ 6.24609501e-02],
       [ 7.82636349e-02],
       [ 1.43587132e+00],
       [ 4.21178710e-01],
       [-1.78618872e-01],
       [ 5.13476735e-01],
       [-1.38639855e-01],
       [ 2.13886772e-01],
       [ 2.34939376e-01],
       [ 1.97168174e-01],
       [ 1.21420469e+00],
       [ 2.43908459e-02],
       [ 4.54975970e-01],
       [ 9.15579831e-01],
       [ 1.05402053e-01],
       [ 2.82091109e-01],
       [ 2.17029519e-01],
       [-5.31287976e-02],
       [ 2.21767853e-01],
       [ 3.55188256e-01],
       [ 5.79620724e-01],
       [ 1.77393389e-01],
       [ 1.63198297e-01],
       [-6.27649129e-03],
       [ 4.31222498e-01],
       [ 2.18609109e+00],
       [ 5.76988808e-01],
       [ 1.15008659e+00],
       [ 3.88224776e-01],
       [-1.62417797e-02],
       [ 3.40952005e-01],
       [ 6.46040891e-01],
       [ 9.70284646e-02],
       [-6.63338028e-02],
       [ 2.84135206e-01],
       [-3.23484212e-03],
       [ 1.73334261e+00],
       [-1.56442774e-01],
       [ 5.96014194e-01],
       [-1.55524988e-01],
       [ 1.81615521e-02],
       [ 3.44660145e-01],
       [ 3.46518337e-01],
       [ 3.21840201e-01],
       [ 4.22680554e-01],
       [-9.00437732e-02],
       [ 2.87075768e-01],
       [ 3.28890662e-01],
       [ 7.75148981e-01],
       [ 8.24320419e-01],
       [ 1.50152187e+00],
       [ 3.07327669e-01],
       [ 3.73677279e-03],
       [ 1.08444608e-01],
       [ 1.29161913e-01],
       [ 4.56531480e-01],
       [ 9.84308534e-02],
       [-1.94007336e-01],
       [ 3.68744650e-01],
       [ 6.81607401e-01],
       [ 5.79408096e-01],
       [-1.89192476e-02],
       [ 3.73009668e-02],
       [ 1.17093570e-02],
       [ 1.71033823e+00],
       [ 1.27279118e-01],
       [ 1.33838971e+00],
       [ 2.20978357e-01],
       [ 5.11723216e-01],
       [ 1.33213798e+00],
       [ 2.76651189e-01],
       [ 6.78513452e-01],
       [ 6.61704668e-01],
       [ 1.21263203e-01],
       [-1.13058585e-01],
       [ 7.43497661e-01],
       [-5.64025656e-02],
       [ 9.42017508e-01],
       [-1.84104097e-01],
       [ 3.92564712e-01],
       [ 2.47621814e-01],
       [ 1.02867472e-01],
       [ 2.20423162e-01],
       [-5.94752704e-02],
       [ 9.64519789e-01],
       [ 2.84190421e-01],
       [ 2.10248642e-01],
       [ 3.28053161e-01],
       [ 3.80936635e-02],
       [ 4.22772332e-01],
       [-1.55009570e-01],
       [ 9.81514325e-02],
       [ 4.00053306e-01],
       [-2.04972755e-01],
       [ 1.28471289e+00],
       [ 1.53361030e+00],
       [ 2.57668840e-01],
       [ 6.14643203e-01],
       [ 7.27458127e-01],
       [ 4.21588809e-01],
       [ 4.16692230e-01],
       [-1.62816942e-02],
       [ 4.98706233e-02],
       [ 1.03343104e-01],
       [ 7.03747262e-01],
       [ 2.07993212e-01],
       [ 4.63204880e-01],
       [ 4.25344139e-01],
       [ 1.60936602e-01],
       [ 5.59679984e-03],
       [ 1.11260580e-01],
       [-2.25688694e-01],
       [ 1.74634761e-02],
       [ 1.33608472e-01],
       [ 3.41995284e-01],
       [-2.43515846e-01],
       [-1.15887036e-01],
       [-7.99247819e-02],
       [ 1.22207919e-01],
       [ 2.16963806e-01],
       [ 2.77216457e-01],
       [-1.13051400e-01],
       [ 2.45350503e-01],
       [-1.16786973e-01],
       [ 1.63096112e-01],
       [ 7.97984226e-02],
       [ 4.73859069e-02],
       [ 3.67323202e-01],
       [ 1.75285708e-01],
       [-3.18285825e-02],
       [-3.04721863e-02],
       [ 2.01324692e-01],
       [-1.52616236e-01],
       [ 1.46074844e-02],
       [ 1.53252638e-01],
       [ 5.98434472e-02],
       [ 1.10136594e+00],
       [-6.11062678e-02],
       [ 1.85799787e-01],
       [-5.26859828e-02],
       [ 2.72020514e-01],
       [ 4.47211536e-01],
       [ 5.21561359e-02],
       [ 4.49016011e-02],
       [ 1.16346150e-01],
       [ 2.46671963e-01],
       [ 1.82129501e-02],
       [ 2.05117092e-01],
       [ 2.57468266e-01],
       [ 5.68642323e-02],
       [ 2.93167980e-01],
       [-2.07800713e-01],
       [ 3.28137585e-01],
       [ 3.39402925e-01],
       [ 2.32570448e-02],
       [ 1.04336204e-01],
       [ 3.70159276e-03],
       [ 2.81521730e-01],
       [ 5.19512476e-01],
       [ 7.38820976e-01],
       [ 1.80397825e-01],
       [ 1.98232153e-01],
       [ 9.38387321e-02],
       [ 1.25921558e-01],
       [ 3.03874553e-01],
       [ 4.58335954e-01],
       [ 1.17138372e-01],
       [ 9.70818293e-02],
       [ 2.62856414e-01],
       [ 8.23761107e-01],
       [-1.00564570e-01],
       [ 6.62728160e-01],
       [-1.68452248e-01],
       [-3.55859649e-02],
       [-8.29331888e-02],
       [-6.83491211e-03],
       [ 1.06661631e-01],
       [ 1.56024896e-01],
       [ 3.27082767e-02],
       [-2.47349451e-02],

In [604]:
mae= mean_absolute_error(y_test['ltd_30d'], y_pred)
rmse = np.sqrt(mean_squared_error(y_test['ltd_30d'], y_pred))
r2 = r2_score(y_test['ltd_30d'], y_pred)

In [605]:
print('mae',mae)
print('rmse',rmse)
print('r2',r2)

mae 0.459264734338118
rmse 0.7103200679172019
r2 0.2796049058366895

In [606]:
print('mae_bae',mae_bae)
print('rmse_bae',rmse_bae)
print('r2_bae',r2_bae)

mae_bae 0.5457414690186173
rmse_bae 1.1345008881805416
r2_bae -0.8376900254053452

In [607]:
# slicing analysis

In [609]:
y_test['pred'] = y_pred
y_test['country'] = X_test['country']
y_test['platform'] = X_test['platform']

/var/folders/qh/wcp4hdh55d56zf2h540jdxlr0000gn/T/ipykernel_62040/1387912454.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y_test['pred'] = y_pred
/var/folders/qh/wcp4hdh55d56zf2h540jdxlr0000gn/T/ipykernel_62040/1387912454.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y_test['country'] = X_test['country']
/var/folders/qh/wcp4hdh55d56zf2h540jdxlr0000gn/T/ipykernel_62040/1387912454.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y_test['platform'] = X_test['platform']

In [610]:
y_test

       ltd_30d      pred country platform
4117  0.000000  0.056078      CA  android
4118  0.000000  0.205335      CA      ios
4119  0.000000  0.514600      CA  android
4120  0.000000 -0.143659      US      web
4121  1.905651  0.473559      IN  android
...        ...       ...     ...      ...
4973  0.000000 -0.136675      US  android
4974  0.000000 -0.162315      CA      web
4975  0.000000 -0.209834      US  android
4976  0.000000  0.037575      UK      web
4977  0.000000 -0.140137      UK  android

[861 rows x 4 columns]

In [ ]:
cohort_country = y_test.groupby(['country']).apply(lambda x: pd.Series({'mae':mean_absolute_error(x['ltd_30d'], x['pred']),
'rmse':np.sqrt(mean_squared_error(x['ltd_30d'], x['pred'])),
'r2': r2_score(x['ltd_30d'], x['pred'])}))

/var/folders/qh/wcp4hdh55d56zf2h540jdxlr0000gn/T/ipykernel_62040/4163147039.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  cohort_country = y_test.groupby(['country']).apply(lambda x: pd.Series({'mae':mean_absolute_error(x['ltd_30d'], x['pred']),

In [612]:
cohort_platform = y_test.groupby(['platform']).apply(lambda x: pd.Series({'mae':mean_absolute_error(x['ltd_30d'], x['pred']),
'rmse':np.sqrt(mean_squared_error(x['ltd_30d'], x['pred'])),
'r2': r2_score(x['ltd_30d'], x['pred'])}))

/var/folders/qh/wcp4hdh55d56zf2h540jdxlr0000gn/T/ipykernel_62040/816810628.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  cohort_platform = y_test.groupby(['platform']).apply(lambda x: pd.Series({'mae':mean_absolute_error(x['ltd_30d'], x['pred']),

In [613]:
cohort_country

              mae      rmse        r2
country
CA       0.406157  0.620110  0.262586
IN       0.492734  0.772899  0.243104
UK       0.453331  0.712829  0.315847
US       0.476418  0.714790  0.278340

In [614]:
cohort_platform

               mae      rmse        r2
platform
android   0.406487  0.659087  0.290299
ios       0.490028  0.741662  0.317771
web       0.474901  0.721493  0.213849